
# Agent 2 — AQA GCSE Computer Science Assessment Knowledge Base

## Notebook 01: Official source discovery, download, and PostgreSQL registration

This notebook implements the first Agent 2 ingestion stage for the frozen scope:

- **Exam board:** AQA
- **Qualification:** GCSE
- **Subject:** Computer Science
- **Specification:** 8525
- **Supported question papers:** `8525/1B` (Python) and `8525/2`
- **Supported mark schemes:** shared Paper 1 mark scheme and Paper 2 mark scheme
- **Structured storage:** PostgreSQL
- **Original PDFs:** local cache
- **Embeddings:** Qdrant in a later notebook

This notebook does **not** parse individual questions yet. It first establishes a reliable document manifest in PostgreSQL.


## Pipeline implemented here

```text
Official AQA assessment-resources page
        ↓
Render the dynamic page with Playwright
        ↓
Collect official question-paper and mark-scheme PDF links
        ↓
Download new/changed PDFs to a managed cache
        ↓
Inspect the first pages with PyMuPDF
        ↓
Keep only AQA GCSE Computer Science 8525:
    - Paper 1B question papers
    - shared Paper 1 mark schemes
    - Paper 2 question papers
    - Paper 2 mark schemes
        ↓
Register document metadata and processing status in PostgreSQL
        ↓
Write a human-readable discovery manifest
```


## 1. Install dependencies

Run this cell once in the Agent 2 virtual environment. Playwright also requires its Chromium browser binary.

In [1]:

%pip install -q \
    playwright \
    requests \
    beautifulsoup4 \
    pymupdf \
    pandas \
    pydantic \
    python-dotenv \
    "sqlalchemy>=2.0" \
    "psycopg[binary]>=3.1"

!playwright install chromium

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Downloading Chrome for Testing 151.0.7922.34 (playwright chromium v1234) from https://cdn.playwright.dev/builds/cft/151.0.7922.34/win64/chrome-win64.zip
|                                                                                |   0% of 191.8 MiB
|■■■■■■■■                                                                        |  10% of 191.8 MiB
|■■■■■■■■■■■■■■■■                                                                |  20% of 191.8 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 191.8 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 191.8 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 191.8 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 191.8 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 191.8 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 191.8 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 191.8 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 191.8 MiB
Chrome for Testing 151.0.7922.34 (playwright chromium v1234) downloaded to C:\Users\hp\AppData\Local\ms-playwright\chromium-1234
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-win64.zip
|                                                                                |   0% of 1.3 MiB
|■■■■■■■■                                                                        |  10% of 1.3 MiB
|■■■■■■■■■■■■■■■■                                                                |  20% of 1.3 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 1.3 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 1.3 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 1.3 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 1.3 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  71% of 1.3 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 1.3 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 1.3 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 1.3 MiB
FFmpeg (playwright ffmpeg v1011) downloaded to C:\Users\hp\AppData\Local\ms-playwright\ffmpeg-1011
Downloading Chrome Headless Shell 151.0.7922.34 (playwright chromium-headless-shell v1234) from https://cdn.playwright.dev/builds/cft/151.0.7922.34/win64/chrome-headless-shell-win64.zip
|                                                                                |   0% of 114.5 MiB
|■■■■■■■■                                                                        |  10% of 114.5 MiB
|■■■■■■■■■■■■■■■■                                                                |  20% of 114.5 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 114.5 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 114.5 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 114.5 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 114.5 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 114.5 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 114.5 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 114.5 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 114.5 MiB
Chrome Headless Shell 151.0.7922.34 (playwright chromium-headless-shell v1234) downloaded to C:\Users\hp\AppData\Local\ms-playwright\chromium_headless_shell-1234
Downloading Winldd (playwright winldd v1007) from https://cdn.playwright.dev/dbazure/download/playwright/builds/winldd/1007/winldd-win64.zip
|■■■■■■■■                                                                        |  12% of 0.1 MiB
|■■■■■■■■■■■■■■■■                                                                |  25% of 0.1 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  38% of 0.1 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  51% of 0.1 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 0.1 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  82% of 0.1 MiB
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 0.1 MiB
Winldd (playwright winldd v1007) downloaded to C:\Users\hp\AppData\Local\ms-playwright\winldd-1007


## 2. Imports and project configuration

The notebook expects to be inside:

```text
Agent_2/
├── notebooks/
├── cache/
├── OUTPUT/
└── .env
```

The paths are created automatically if they do not already exist.

In [1]:

from __future__ import annotations

import hashlib
import json
import os
import re
import time
import uuid
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import unquote, urljoin, urlparse

import fitz  # PyMuPDF
import pandas as pd
import requests
from dotenv import load_dotenv
from pydantic import BaseModel, ConfigDict, Field, HttpUrl, field_validator
from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
from playwright.sync_api import sync_playwright
from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    create_engine,
    select,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column


AQA_SOURCE_PAGE = (
    "https://www.aqa.org.uk/subjects/computer-science/"
    "gcse/computer-science-8525/assessment-resources"
)

EXAM_BOARD = "AQA"
QUALIFICATION = "GCSE"
SUBJECT = "Computer Science"
SPECIFICATION_CODE = "8525"

# Running from Agent_2/notebooks or directly from Agent_2 is supported.
cwd = Path.cwd().resolve()
PROJECT_ROOT = cwd.parent if cwd.name.lower() == "notebooks" else cwd

CACHE_ROOT = PROJECT_ROOT / "cache"
DOWNLOAD_CACHE = CACHE_ROOT / "assessment_pdfs"
OUTPUT_DIR = PROJECT_ROOT / "OUTPUT"

for folder in (CACHE_ROOT, DOWNLOAD_CACHE, OUTPUT_DIR):
    folder.mkdir(parents=True, exist_ok=True)

load_dotenv(PROJECT_ROOT / ".env")

DATABASE_URL = os.getenv("AGENT2_DATABASE_URL", "").strip()

print(f"Project root: {PROJECT_ROOT}")
print(f"PDF cache:    {DOWNLOAD_CACHE}")
print(f"Output:       {OUTPUT_DIR}")
print(f"DB configured: {bool(DATABASE_URL)}")

Project root: C:\Users\hp\EDTECH\Agent2
PDF cache:    C:\Users\hp\EDTECH\Agent2\cache\assessment_pdfs
Output:       C:\Users\hp\EDTECH\Agent2\OUTPUT
DB configured: True


## 3. Environment variables

Create `Agent_2/.env` and add your local PostgreSQL connection:

```env
AGENT2_DATABASE_URL=postgresql+psycopg://postgres:YOUR_PASSWORD@localhost:5432/edtech
```

The same PostgreSQL database may be shared with Agent 1. Agent 2 uses separate `assessment_*` tables.

In [2]:

if not DATABASE_URL:
    raise RuntimeError(
        "AGENT2_DATABASE_URL is missing. Create Agent_2/.env using the example above, "
        "restart the kernel, and rerun the configuration cell."
    )

## 4. PostgreSQL schema

In [3]:

class Base(DeclarativeBase):
    pass


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class AssessmentDocument(Base):
    __tablename__ = "assessment_documents"
    __table_args__ = (
        UniqueConstraint("source_url", name="uq_assessment_documents_source_url"),
        CheckConstraint(
            "document_type IN ('question_paper', 'mark_scheme')",
            name="ck_assessment_documents_document_type",
        ),
        CheckConstraint(
            "document_category IN ('live_exam', 'sample_assessment', 'specimen_assessment')",
            name="ck_assessment_documents_category",
        ),
        Index("ix_assessment_documents_file_hash", "file_hash"),
        Index(
            "ix_assessment_documents_lookup",
            "specification_code",
            "year",
            "exam_series",
            "paper_code",
            "document_type",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    source_page_url: Mapped[str] = mapped_column(Text, nullable=False)
    source_url: Mapped[str] = mapped_column(Text, nullable=False)
    discovery_title: Mapped[str | None] = mapped_column(Text)
    original_file_name: Mapped[str | None] = mapped_column(Text)
    local_cache_path: Mapped[str | None] = mapped_column(Text)
    file_hash: Mapped[str | None] = mapped_column(String(64))

    exam_board: Mapped[str] = mapped_column(String(30), nullable=False, default=EXAM_BOARD)
    qualification: Mapped[str] = mapped_column(
        String(50), nullable=False, default=QUALIFICATION
    )
    subject: Mapped[str] = mapped_column(String(100), nullable=False, default=SUBJECT)
    specification_code: Mapped[str] = mapped_column(
        String(20), nullable=False, default=SPECIFICATION_CODE
    )

    year: Mapped[int | None] = mapped_column(Integer)
    exam_series: Mapped[str | None] = mapped_column(String(30))
    paper_code: Mapped[str | None] = mapped_column(String(20))
    document_type: Mapped[str] = mapped_column(String(30), nullable=False)
    document_category: Mapped[str] = mapped_column(
        String(30), nullable=False, default="live_exam"
    )
    programming_language: Mapped[str | None] = mapped_column(String(50))

    download_status: Mapped[str] = mapped_column(
        String(30), nullable=False, default="discovered"
    )
    parsing_status: Mapped[str] = mapped_column(
        String(30), nullable=False, default="pending"
    )
    error_message: Mapped[str | None] = mapped_column(Text)

    discovered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    downloaded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now, onupdate=utc_now
    )


class AssessmentIngestionRun(Base):
    __tablename__ = "assessment_ingestion_runs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    run_type: Mapped[str] = mapped_column(
        String(50), nullable=False, default="source_discovery"
    )
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="running")
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    counts: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    error_message: Mapped[str | None] = mapped_column(Text)


engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
    future=True,
)

Base.metadata.create_all(engine)

with engine.connect() as connection:
    connection.exec_driver_sql("SELECT 1")

print("PostgreSQL connection successful.")
print("Created/verified tables:")
print("- assessment_documents")
print("- assessment_ingestion_runs")

PostgreSQL connection successful.
Created/verified tables:
- assessment_documents
- assessment_ingestion_runs

## 5. Validated data structures

In [4]:

class DiscoveredLink(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    url: str
    title: str = ""
    discovered_via: str = "dom"

    @field_validator("url")
    @classmethod
    def validate_http_url(cls, value: str) -> str:
        if not value.lower().startswith(("http://", "https://")):
            raise ValueError("Only HTTP(S) URLs are accepted.")
        return value


class ClassifiedAssessmentPDF(BaseModel):
    source_url: str
    discovery_title: str = ""
    original_file_name: str
    local_cache_path: str
    file_hash: str

    exam_board: str = EXAM_BOARD
    qualification: str = QUALIFICATION
    subject: str = SUBJECT
    specification_code: str = SPECIFICATION_CODE

    year: int | None = None
    exam_series: str | None = None
    paper_code: str
    document_type: str
    document_category: str = "live_exam"
    programming_language: str | None = None

    @field_validator("document_type")
    @classmethod
    def validate_document_type(cls, value: str) -> str:
        allowed = {"question_paper", "mark_scheme"}
        if value not in allowed:
            raise ValueError(f"document_type must be one of {allowed}")
        return value

    @field_validator("paper_code")
    @classmethod
    def validate_paper_code(cls, value: str) -> str:
        allowed = {"1B", "1", "2"}
        if value not in allowed:
            raise ValueError(f"Unsupported AQA paper code: {value}")
        return value


## 6. Dynamic AQA resource discovery

The AQA assessment page loads its resource list dynamically. The function below:

1. opens the page in Chromium;
2. accepts a cookie banner when present;
3. captures PDF links from both the rendered DOM and JSON network responses;
4. follows pagination where a usable **Next** control is present;
5. keeps a deduplicated URL/title manifest.

It does not bypass authentication or anti-bot controls.

In [7]:
# ============================================================
# AQA PDF DISCOVERY
# WINDOWS + JUPYTER SAFE VERSION
#
# Playwright runs in a separate Python process, avoiding the
# Jupyter Windows SelectorEventLoop subprocess limitation.
# ============================================================

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from textwrap import dedent
from urllib.parse import unquote, urljoin

import pandas as pd
from pydantic import BaseModel, ConfigDict, field_validator


# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

AQA_SOURCE_PAGE = (
    "https://www.aqa.org.uk/subjects/computer-science/"
    "gcse/computer-science-8525/assessment-resources"
)

# Use the existing OUTPUT_DIR when it was created earlier.
# Otherwise, create an OUTPUT folder in the current directory.
if "OUTPUT_DIR" not in globals():
    OUTPUT_DIR = Path.cwd() / "OUTPUT"

OUTPUT_DIR = Path(OUTPUT_DIR).resolve()
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RUNNER_SCRIPT_PATH = OUTPUT_DIR / "_aqa_playwright_runner.py"
DISCOVERY_JSON_PATH = OUTPUT_DIR / "_aqa_discovered_links.json"


# ------------------------------------------------------------
# Result model used by later notebook cells
# ------------------------------------------------------------

class DiscoveredLink(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    url: str
    title: str = ""
    discovered_via: str = "dom"

    @field_validator("url")
    @classmethod
    def validate_http_url(cls, value: str) -> str:
        if not value.lower().startswith(("http://", "https://")):
            raise ValueError("Only HTTP or HTTPS URLs are accepted.")

        return value


# ------------------------------------------------------------
# Standalone Playwright script
#
# This script is executed outside the Jupyter event loop.
# Therefore, Playwright's Sync API can safely be used.
# ------------------------------------------------------------

runner_script = dedent(
    r'''
    from __future__ import annotations

    import argparse
    import json
    import re
    from pathlib import Path
    from typing import Any
    from urllib.parse import unquote, urljoin

    from playwright.sync_api import (
        TimeoutError as PlaywrightTimeoutError,
        sync_playwright,
    )


    PDF_URL_PATTERN = re.compile(
        r"(?i)(?:"
        r"\.pdf(?:$|[?#])"
        r"|filestore\.aqa\.org\.uk"
        r"|cdn\.sanity\.io/files/"
        r")"
    )


    def normalize_url(url: str, base_url: str) -> str:
        cleaned_url = unquote(url.strip())
        return urljoin(base_url, cleaned_url)


    def recursively_extract_pdf_strings(value: Any) -> list[str]:
        found_urls: list[str] = []

        if isinstance(value, str):
            if (
                value.lower().startswith(("http://", "https://"))
                and PDF_URL_PATTERN.search(value)
            ):
                found_urls.append(value)

            return found_urls

        if isinstance(value, dict):
            for nested_value in value.values():
                found_urls.extend(
                    recursively_extract_pdf_strings(nested_value)
                )

            return found_urls

        if isinstance(value, list):
            for item in value:
                found_urls.extend(
                    recursively_extract_pdf_strings(item)
                )

        return found_urls


    def collect_dom_pdf_links(page, source_page: str) -> list[dict]:
        results: list[dict] = []

        anchors = page.locator("a[href]")
        anchor_count = anchors.count()

        for index in range(anchor_count):
            anchor = anchors.nth(index)

            try:
                href = anchor.get_attribute("href") or ""

                if not href:
                    continue

                absolute_url = normalize_url(href, source_page)

                try:
                    raw_title = anchor.inner_text()
                except Exception:
                    raw_title = ""

                title = " ".join(raw_title.split())

                if PDF_URL_PATTERN.search(absolute_url):
                    results.append(
                        {
                            "url": absolute_url,
                            "title": title,
                            "discovered_via": "dom",
                        }
                    )

            except Exception:
                # One malformed element must not stop discovery.
                continue

        return results


    def accept_cookie_banner_if_present(page) -> None:
        button_patterns = [
            re.compile(r"accept all", re.I),
            re.compile(r"accept cookies", re.I),
            re.compile(r"allow all", re.I),
            re.compile(r"agree", re.I),
        ]

        for pattern in button_patterns:
            try:
                button = page.get_by_role(
                    "button",
                    name=pattern,
                ).first

                if button.count() and button.is_visible():
                    button.click(timeout=3_000)
                    page.wait_for_timeout(500)
                    return

            except Exception:
                continue


    def click_next_if_available(page) -> bool:
        selectors = [
            "button:has-text('Next')",
            "a:has-text('Next')",
            "[aria-label='Next']",
            "[aria-label*='next' i]",
            "[title='Next']",
            "[title*='next' i]",
        ]

        for selector in selectors:
            try:
                locator = page.locator(selector)

                if not locator.count():
                    continue

                candidate = locator.last

                if not candidate.is_visible():
                    continue

                aria_disabled = (
                    candidate.get_attribute("aria-disabled") or ""
                ).lower()

                disabled_attribute = candidate.get_attribute(
                    "disabled"
                )

                class_name = (
                    candidate.get_attribute("class") or ""
                ).lower()

                is_disabled = (
                    aria_disabled == "true"
                    or disabled_attribute is not None
                    or "disabled" in class_name
                )

                if is_disabled:
                    continue

                previous_body_text = page.locator(
                    "body"
                ).inner_text()

                candidate.scroll_into_view_if_needed()
                candidate.click(timeout=5_000)

                try:
                    page.wait_for_load_state(
                        "networkidle",
                        timeout=15_000,
                    )
                except PlaywrightTimeoutError:
                    pass

                page.wait_for_timeout(1_000)

                current_body_text = page.locator(
                    "body"
                ).inner_text()

                return current_body_text != previous_body_text

            except Exception:
                continue

        return False


    def discover_aqa_pdf_links(
        source_page: str,
        *,
        headless: bool = True,
        max_pages: int = 30,
    ) -> list[dict]:

        discovered: dict[str, dict] = {}
        network_pdf_urls: set[str] = set()

        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(
                headless=headless
            )

            context = browser.new_context(
                viewport={
                    "width": 1440,
                    "height": 1100,
                },
                user_agent=(
                    "Mozilla/5.0 "
                    "(Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 "
                    "(KHTML, like Gecko) "
                    "Chrome/130.0 Safari/537.36"
                ),
            )

            page = context.new_page()

            # ----------------------------------------------
            # Capture PDF URLs present in JSON responses
            # ----------------------------------------------

            def capture_response(response) -> None:
                try:
                    content_type = (
                        response.headers.get("content-type")
                        or ""
                    ).lower()

                    if "application/json" not in content_type:
                        return

                    payload = response.json()

                    for pdf_url in recursively_extract_pdf_strings(
                        payload
                    ):
                        network_pdf_urls.add(
                            normalize_url(
                                pdf_url,
                                source_page,
                            )
                        )

                except Exception:
                    return

            page.on("response", capture_response)

            # ----------------------------------------------
            # Open page
            # ----------------------------------------------

            page.goto(
                source_page,
                wait_until="domcontentloaded",
                timeout=60_000,
            )

            accept_cookie_banner_if_present(page)

            try:
                page.wait_for_load_state(
                    "networkidle",
                    timeout=20_000,
                )
            except PlaywrightTimeoutError:
                pass

            page.wait_for_timeout(2_000)

            # ----------------------------------------------
            # Inspect rendered result pages
            # ----------------------------------------------

            seen_page_signatures: set[tuple[str, ...]] = set()

            for page_number in range(1, max_pages + 1):
                print(
                    f"Inspecting resource page "
                    f"{page_number}/{max_pages}...",
                    flush=True,
                )

                page.evaluate(
                    "window.scrollTo("
                    "0, document.body.scrollHeight"
                    ")"
                )

                page.wait_for_timeout(1_500)

                page_links = collect_dom_pdf_links(
                    page,
                    source_page,
                )

                for link in page_links:
                    discovered[link["url"]] = link

                current_signature = tuple(
                    sorted(
                        link["url"]
                        for link in page_links
                    )
                )

                if (
                    current_signature
                    and current_signature
                    in seen_page_signatures
                ):
                    print(
                        "Repeated results page detected.",
                        flush=True,
                    )
                    break

                seen_page_signatures.add(
                    current_signature
                )

                if not click_next_if_available(page):
                    print(
                        "No enabled Next control found.",
                        flush=True,
                    )
                    break

            # Add URLs captured from JSON/API responses.
            for url in network_pdf_urls:
                discovered.setdefault(
                    url,
                    {
                        "url": url,
                        "title": "",
                        "discovered_via": "network_json",
                    },
                )

            context.close()
            browser.close()

        return sorted(
            discovered.values(),
            key=lambda item: item["url"],
        )


    def main() -> None:
        parser = argparse.ArgumentParser()

        parser.add_argument(
            "--source-page",
            required=True,
        )

        parser.add_argument(
            "--output-json",
            required=True,
        )

        parser.add_argument(
            "--max-pages",
            type=int,
            default=30,
        )

        parser.add_argument(
            "--show-browser",
            action="store_true",
        )

        arguments = parser.parse_args()

        links = discover_aqa_pdf_links(
            source_page=arguments.source_page,
            headless=not arguments.show_browser,
            max_pages=arguments.max_pages,
        )

        output_path = Path(
            arguments.output_json
        ).resolve()

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        output_path.write_text(
            json.dumps(
                links,
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )

        print(
            f"Discovered {len(links)} PDF-like links.",
            flush=True,
        )

        print(
            f"Saved result to: {output_path}",
            flush=True,
        )


    if __name__ == "__main__":
        main()
    '''
)


# Write the external Playwright runner.
RUNNER_SCRIPT_PATH.write_text(
    runner_script,
    encoding="utf-8",
)

print(
    f"Created Playwright runner:\n"
    f"{RUNNER_SCRIPT_PATH}"
)


# ------------------------------------------------------------
# Run Playwright in a separate Python process
# ------------------------------------------------------------

command = [
    sys.executable,
    str(RUNNER_SCRIPT_PATH),
    "--source-page",
    AQA_SOURCE_PAGE,
    "--output-json",
    str(DISCOVERY_JSON_PATH),
    "--max-pages",
    "30",
]

print("\nStarting external Playwright process...\n")

process = subprocess.run(
    command,
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace",
)


# Show script progress.
if process.stdout.strip():
    print(process.stdout)

if process.returncode != 0:
    print("Playwright process failed.")

    if process.stderr.strip():
        print(process.stderr)

    error_text = process.stderr.lower()

    if (
        "executable doesn't exist" in error_text
        or "browserType.launch" in process.stderr
    ):
        print(
            "\nChromium may not be installed.\n"
            "Run this in another notebook cell:\n\n"
            "!playwright install chromium"
        )

    raise RuntimeError(
        "External Playwright discovery process failed. "
        "Review the error printed above."
    )


# ------------------------------------------------------------
# Load the results back into the notebook
# ------------------------------------------------------------

if not DISCOVERY_JSON_PATH.exists():
    raise FileNotFoundError(
        "Playwright completed but did not create the "
        f"expected file: {DISCOVERY_JSON_PATH}"
    )

raw_discovered_links = json.loads(
    DISCOVERY_JSON_PATH.read_text(
        encoding="utf-8"
    )
)

discovered_links = [
    DiscoveredLink(**item)
    for item in raw_discovered_links
]


# ------------------------------------------------------------
# Display results
# ------------------------------------------------------------

print(
    f"\nTotal PDF-like links discovered: "
    f"{len(discovered_links)}"
)

discovered_links_df = pd.DataFrame(
    [
        item.model_dump()
        for item in discovered_links
    ]
)

if discovered_links_df.empty:
    print(
        "No PDF links were discovered.\n"
        "For debugging, add '--show-browser' to the "
        "command list and run the cell again."
    )

else:
    display(
        discovered_links_df.head(30)
    )

Created Playwright runner:
C:\Users\hp\EDTECH\Agent2\OUTPUT\_aqa_playwright_runner.py

Starting external Playwright process...

Inspecting resource page 1/30...
No enabled Next control found.
Discovered 18 PDF-like links.
Saved result to: C:\Users\hp\EDTECH\Agent2\OUTPUT\_aqa_discovered_links.json


Total PDF-like links discovered: 18

,url,title,discovered_via
0,https://cdn.sanity.io/files/p28bar15/green/08f...,,network_json
1,https://cdn.sanity.io/files/p28bar15/green/1a4...,,network_json
2,https://cdn.sanity.io/files/p28bar15/green/52f...,,network_json
3,https://cdn.sanity.io/files/p28bar15/green/642...,,network_json
4,https://cdn.sanity.io/files/p28bar15/green/78f...,,network_json
5,https://cdn.sanity.io/files/p28bar15/green/802...,,network_json
6,https://cdn.sanity.io/files/p28bar15/green/890...,,network_json
7,https://cdn.sanity.io/files/p28bar15/green/db8...,,network_json
8,https://cdn.sanity.io/files/p28bar15/green/f17...,,network_json
9,https://www.aqa.org.uk/files/resources.computi...,Practice questions: Paper 1 Computational thin...,dom
10,https://www.aqa.org.uk/files/resources.computi...,Mark scheme: Paper 1 Computational thinking an...,dom
11,https://www.aqa.org.uk/files/resources.computi...,Question paper: Paper 1A Computational thinkin...,dom
12,https://www.aqa.org.uk/files/resources.computi...,Question paper: Paper 2 Computing concepts - S...,dom
13,https://www.aqa.org.uk/files/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,dom
14,https://www.aqa.org.uk/files/sample-papers-and...,Mark scheme: Paper 1 Computational thinking an...,dom
15,https://www.aqa.org.uk/files/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,dom
16,https://www.aqa.org.uk/files/sample-papers-and...,Mark scheme: Paper 2 Computing concepts - June...,dom
17,https://www.aqa.org.uk/files/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,dom


## 7. Candidate filtering

The page can contain examiner reports, grade boundaries, inserts, and other resources. Before downloading, we keep links whose title or URL suggests a question paper or mark scheme.

The PDF itself is inspected after download, so this preliminary filter does not determine the final classification.

In [9]:

QUESTION_OR_MARK_SCHEME_HINTS = (
    "question paper",
    "mark scheme",
    "-qp-",
    "-ms-",
    " qp ",
    " ms ",
)


def is_likely_question_or_mark_scheme(link: DiscoveredLink) -> bool:
    combined = f" {link.title.lower()} {link.url.lower()} "
    return any(hint in combined for hint in QUESTION_OR_MARK_SCHEME_HINTS)


candidate_links = [
    link for link in discovered_links if is_likely_question_or_mark_scheme(link)
]

print(f"Question-paper/mark-scheme candidates: {len(candidate_links)}")
pd.DataFrame([item.model_dump() for item in candidate_links]).head(20)

Question-paper/mark-scheme candidates: 8

,url,title,discovered_via
0,https://www.aqa.org.uk/files/resources.computi...,Mark scheme: Paper 1 Computational thinking an...,dom
1,https://www.aqa.org.uk/files/resources.computi...,Question paper: Paper 1A Computational thinkin...,dom
2,https://www.aqa.org.uk/files/resources.computi...,Question paper: Paper 2 Computing concepts - S...,dom
3,https://www.aqa.org.uk/files/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,dom
4,https://www.aqa.org.uk/files/sample-papers-and...,Mark scheme: Paper 1 Computational thinking an...,dom
5,https://www.aqa.org.uk/files/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,dom
6,https://www.aqa.org.uk/files/sample-papers-and...,Mark scheme: Paper 2 Computing concepts - June...,dom
7,https://www.aqa.org.uk/files/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,dom

In [17]:
# ============================================================
# COMPLETE AQA 8525 COVERAGE PASS — 2022 TO 2025
#
# Purpose:
# 1. Process ALL discovered PDF URLs, including blank-title
#    network_json links.
# 2. Let PyMuPDF classification decide whether each document
#    is a supported AQA 8525 assessment document.
# 3. Read the complete manifest from PostgreSQL.
# 4. Show exactly which papers are still missing.
# ============================================================

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
from sqlalchemy import select
from sqlalchemy.orm import Session


# ------------------------------------------------------------
# Required years and documents
# ------------------------------------------------------------

REQUIRED_YEARS = [2022, 2023, 2024, 2025]

REQUIRED_DOCUMENTS = [
    {
        "requirement_key": "paper_1b_question_paper",
        "paper_code": "1B",
        "document_type": "question_paper",
        "display_name": "Paper 1B Question Paper",
    },
    {
        "requirement_key": "paper_1_mark_scheme",
        "paper_code": "1",
        "document_type": "mark_scheme",
        "display_name": "Paper 1 Mark Scheme",
    },
    {
        "requirement_key": "paper_2_question_paper",
        "paper_code": "2",
        "document_type": "question_paper",
        "display_name": "Paper 2 Question Paper",
    },
    {
        "requirement_key": "paper_2_mark_scheme",
        "paper_code": "2",
        "document_type": "mark_scheme",
        "display_name": "Paper 2 Mark Scheme",
    },
]


# ------------------------------------------------------------
# Validate discovery output
# ------------------------------------------------------------

if "discovered_links" not in globals():
    raise RuntimeError(
        "discovered_links is missing. Run the Playwright "
        "source-discovery cell first."
    )

if not discovered_links:
    raise RuntimeError(
        "The discovery stage returned zero links."
    )

print(
    f"All discovered PDF-like links available: "
    f"{len(discovered_links)}"
)


# ------------------------------------------------------------
# Important correction:
# Do not use title-based candidate filtering here.
#
# Blank-title network_json links may contain valid papers.
# The downloaded PDF itself will be checked by PyMuPDF.
# ------------------------------------------------------------

all_pdf_candidates = list(discovered_links)

candidate_source_counts = pd.Series(
    [
        link.discovered_via
        for link in all_pdf_candidates
    ]
).value_counts()

print("\nCandidates by discovery method:")
display(
    candidate_source_counts.rename_axis(
        "discovered_via"
    ).reset_index(
        name="count"
    )
)


# ------------------------------------------------------------
# Run broad ingestion
#
# Existing records will not be duplicated:
# - source URL and SHA-256 checks are already implemented
# - unchanged files are skipped
# - irrelevant PDFs are discarded after content inspection
# ------------------------------------------------------------

accepted_all_df, broad_issues_df, broad_counts = (
    run_source_ingestion(
        all_pdf_candidates,
        include_non_live=False,
        request_delay_seconds=0.35,
    )
)

print("\nBroad ingestion summary:")
print(
    json.dumps(
        broad_counts,
        indent=2,
    )
)

if not accepted_all_df.empty:
    print("\nDocuments accepted in this run:")

    display(
        accepted_all_df.sort_values(
            [
                "year",
                "paper",
                "document_type",
            ],
            ascending=[
                False,
                True,
                True,
            ],
        )
    )

if not broad_issues_df.empty:
    print("\nDownload/classification issues:")

    display(
        broad_issues_df
    )


# ------------------------------------------------------------
# Load complete Agent 2 document manifest from PostgreSQL
#
# This includes:
# - documents inserted during earlier runs
# - documents found during this broad pass
# ------------------------------------------------------------

with Session(engine) as session:
    document_records = session.scalars(
        select(AssessmentDocument).where(
            AssessmentDocument.exam_board == "AQA",
            AssessmentDocument.qualification == "GCSE",
            AssessmentDocument.subject == "Computer Science",
            AssessmentDocument.specification_code == "8525",
            AssessmentDocument.document_category == "live_exam",
            AssessmentDocument.year.in_(REQUIRED_YEARS),
            AssessmentDocument.download_status == "completed",
        )
    ).all()


manifest_rows: list[dict[str, Any]] = []

for record in document_records:
    manifest_rows.append(
        {
            "database_id": str(record.id),
            "year": record.year,
            "series": record.exam_series,
            "paper_code": record.paper_code,
            "document_type": record.document_type,
            "programming_language": (
                record.programming_language
            ),
            "file_name": record.original_file_name,
            "local_cache_path": record.local_cache_path,
            "file_hash": record.file_hash,
            "source_url": record.source_url,
            "download_status": record.download_status,
            "parsing_status": record.parsing_status,
        }
    )


complete_manifest_df = pd.DataFrame(
    manifest_rows
)

if complete_manifest_df.empty:
    raise RuntimeError(
        "No 2022–2025 AQA 8525 live assessment "
        "documents were found in PostgreSQL."
    )

complete_manifest_df = (
    complete_manifest_df
    .sort_values(
        [
            "year",
            "paper_code",
            "document_type",
        ],
        ascending=[
            False,
            True,
            True,
        ],
    )
    .reset_index(
        drop=True
    )
)

print(
    "\nComplete PostgreSQL manifest for 2022–2025:"
)

display(
    complete_manifest_df
)


# ------------------------------------------------------------
# Coverage matrix
# ------------------------------------------------------------

coverage_rows: list[dict[str, Any]] = []
missing_rows: list[dict[str, Any]] = []

for year in REQUIRED_YEARS:
    year_manifest = complete_manifest_df[
        complete_manifest_df["year"] == year
    ]

    coverage_row: dict[str, Any] = {
        "year": year
    }

    for requirement in REQUIRED_DOCUMENTS:
        matching_records = year_manifest[
            (
                year_manifest["paper_code"]
                == requirement["paper_code"]
            )
            & (
                year_manifest["document_type"]
                == requirement["document_type"]
            )
        ]

        is_present = not matching_records.empty

        coverage_row[
            requirement["requirement_key"]
        ] = "✓" if is_present else "✗"

        if not is_present:
            missing_rows.append(
                {
                    "year": year,
                    "required_document": (
                        requirement["display_name"]
                    ),
                    "paper_code": (
                        requirement["paper_code"]
                    ),
                    "document_type": (
                        requirement["document_type"]
                    ),
                    "status": "missing",
                }
            )

    coverage_rows.append(
        coverage_row
    )


coverage_df = pd.DataFrame(
    coverage_rows
)

missing_documents_df = pd.DataFrame(
    missing_rows
)

print("\nAQA 8525 knowledge-base coverage:")
display(
    coverage_df
)


# ------------------------------------------------------------
# Final completeness summary
# ------------------------------------------------------------

expected_document_count = (
    len(REQUIRED_YEARS)
    * len(REQUIRED_DOCUMENTS)
)

present_requirement_count = (
    expected_document_count
    - len(missing_rows)
)

print(
    "\n"
    + "=" * 62
)

print(
    "AQA 8525 ASSESSMENT KNOWLEDGE-BASE COVERAGE"
)

print(
    "=" * 62
)

print(
    f"Expected documents: {expected_document_count}"
)

print(
    f"Requirements met:   {present_requirement_count}"
)

print(
    f"Requirements missing: {len(missing_rows)}"
)

print(
    "=" * 62
)


if missing_rows:
    print(
        "\nKnowledge base is still incomplete."
    )

    print(
        "The following official documents are missing:"
    )

    display(
        missing_documents_df
    )

else:
    print(
        "\nAll required AQA 8525 papers and "
        "mark schemes for 2022–2025 are present."
    )

    print(
        "The document knowledge base is ready "
        "for question-level parsing."
    )


# ------------------------------------------------------------
# Save updated reports
# ------------------------------------------------------------

if "OUTPUT_DIR" not in globals():
    OUTPUT_DIR = Path.cwd() / "OUTPUT"

OUTPUT_DIR = Path(
    OUTPUT_DIR
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

coverage_path = (
    OUTPUT_DIR
    / "aqa_8525_coverage_2022_2025.csv"
)

missing_path = (
    OUTPUT_DIR
    / "aqa_8525_missing_documents_2022_2025.csv"
)

manifest_path = (
    OUTPUT_DIR
    / "aqa_8525_complete_manifest_2022_2025.csv"
)

complete_manifest_df.to_csv(
    manifest_path,
    index=False,
)

coverage_df.to_csv(
    coverage_path,
    index=False,
)

missing_documents_df.to_csv(
    missing_path,
    index=False,
)

print("\nSaved reports:")

print(
    f"- Complete manifest: {manifest_path}"
)

print(
    f"- Coverage report:   {coverage_path}"
)

print(
    f"- Missing documents: {missing_path}"
)

All discovered PDF-like links available: 18

Candidates by discovery method:

  discovered_via  count
0   network_json      9
1            dom      9

[1/18] https://cdn.sanity.io/files/p28bar15/green/08f5a15be46059e4245197df7b488272a67e0d63.pdf
[2/18] https://cdn.sanity.io/files/p28bar15/green/1a420a42fa84fcebb5313277db23675e9d1f9ed9.pdf
[3/18] https://cdn.sanity.io/files/p28bar15/green/52f67d882ddb6f4df1a8fc8f9a9670163bc5242c.pdf
[4/18] https://cdn.sanity.io/files/p28bar15/green/642bc63cc1a2bde5150267668b706cbdaa16b9fc.pdf
[5/18] https://cdn.sanity.io/files/p28bar15/green/78fcc7e4df776f18615f6664028c397690cf63fd.pdf
[6/18] https://cdn.sanity.io/files/p28bar15/green/802591934c5ab724411b6a9a723f74fcab057ed7.pdf
[7/18] https://cdn.sanity.io/files/p28bar15/green/89025a290cf740b9a0e5f2cb60974282246386aa.pdf
[8/18] https://cdn.sanity.io/files/p28bar15/green/db89078be6b59ce2fab8cac09ddae035daf0f313.pdf
[9/18] https://cdn.sanity.io/files/p28bar15/green/f178eb20adff3da987d731a14ddbeeedbfe4d15e.pdf
[10/18] Practice questions: Paper 1 Computational thinking and programming skills|Practice questions: Paper 1 Computational thinking and programming skills - Computer Science GCSE Computer Science • PDF • 4.76 MB • Published: 04 Mar 2020
[11/18] Mark scheme: Paper 1 Computational thinking and programming skills - Sample set 1 - Computer Science GCSE Computer Science • PDF • 480.36 KB • Published: 13 Dec 2019
[12/18] Question paper: Paper 1A Computational thinking and programming skills (C#) - Sample set 1 - Computer Science GCSE Computer Science • PDF • 628.49 KB • Published: 13 Dec 2019
[13/18] Question paper: Paper 2 Computing concepts - Sample set 1 (last exam 2026) - Computer Science GCSE Computer Science • PDF • 439.1 KB • Published: 13 Dec 2019
[14/18] Question paper: Paper 1B Computational thinking and programming skills (Python) - June 2022 - Computer Science GCSE Computer Science • PDF • 1.14 MB • Published: 14 Jul 2023
[15/18] Mark scheme: Paper 1 Computational thinking and programming skills - June 2023 - Computer Science GCSE Computer Science • PDF • 454.43 KB • Published: 07 Dec 2024
[16/18] Question paper: Paper 1B Computational thinking and programming skills (Python) - June 2023 - Computer Science GCSE Computer Science • PDF • 740.91 KB • Published: 07 Dec 2024
[17/18] Mark scheme: Paper 2 Computing concepts - June 2023 - Computer Science GCSE Computer Science • PDF • 362.56 KB • Published: 07 Dec 2024
[18/18] Question paper: Paper 2 Computing concepts - June 2023 - Computer Science GCSE Computer Science • PDF • 571.14 KB • Published: 07 Dec 2024

Broad ingestion summary:
{
  "candidates": 18,
  "accepted": 7,
  "irrelevant_or_excluded": 11,
  "download_failed": 0,
  "classification_failed": 0,
  "inserted": 0,
  "updated": 0,
  "skipped_unchanged": 7
}

Documents accepted in this run:

,database_id,year,series,paper,document_type,category,programming_language,file_hash,local_cache_path,source_url,database_action
0,5b99ed2b-a3ba-4d16-8e85-baf965b4cfbe,2023,June,1B,mark_scheme,live_exam,Python,04ef1087412b9376884cf60ab11bea1c23a7adecb9fb57...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://cdn.sanity.io/files/p28bar15/green/08f...,skipped_unchanged
3,5b99ed2b-a3ba-4d16-8e85-baf965b4cfbe,2023,June,1B,mark_scheme,live_exam,Python,04ef1087412b9376884cf60ab11bea1c23a7adecb9fb57...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,skipped_unchanged
4,9040b67e-56ad-4f90-b98a-8e01ca7c2ba9,2023,June,1B,question_paper,live_exam,Python,6767013c28067e540ea3942d231b2b048539a888658135...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,skipped_unchanged
1,1a21a37c-b64a-44af-9caa-2b4ec5b6f039,2023,June,2,mark_scheme,live_exam,NaN,f32360582e4f42933eabd545fd13e080fbf56ee6aa7e12...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://cdn.sanity.io/files/p28bar15/green/642...,skipped_unchanged
5,1a21a37c-b64a-44af-9caa-2b4ec5b6f039,2023,June,2,mark_scheme,live_exam,NaN,f32360582e4f42933eabd545fd13e080fbf56ee6aa7e12...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,skipped_unchanged
6,4bd83e85-0a5d-4ee2-af33-a4640f4bc830,2023,June,2,question_paper,live_exam,NaN,8433047a46c08d03325fcb0a580ba9b744386f7d7b8dbd...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,skipped_unchanged
2,65ab6d7b-67a7-4ffe-b163-0d50cbd037f8,2022,June,1B,question_paper,live_exam,Python,b8c53317b668a6cfa7cf51b520246a81b6939dbf7d7f45...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,skipped_unchanged

Complete PostgreSQL manifest for 2022–2025:

,database_id,year,series,paper_code,document_type,programming_language,file_name,local_cache_path,file_hash,source_url,download_status,parsing_status
0,5b99ed2b-a3ba-4d16-8e85-baf965b4cfbe,2023,June,1B,mark_scheme,Python,08f5a15be46059e4245197df7b488272a67e0d63.pdf,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,04ef1087412b9376884cf60ab11bea1c23a7adecb9fb57...,https://www.aqa.org.uk/files/sample-papers-and...,completed,pending
1,9040b67e-56ad-4f90-b98a-8e01ca7c2ba9,2023,June,1B,question_paper,Python,78fcc7e4df776f18615f6664028c397690cf63fd.pdf,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,6767013c28067e540ea3942d231b2b048539a888658135...,https://www.aqa.org.uk/files/sample-papers-and...,completed,pending
2,1a21a37c-b64a-44af-9caa-2b4ec5b6f039,2023,June,2,mark_scheme,NaN,642bc63cc1a2bde5150267668b706cbdaa16b9fc.pdf,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,f32360582e4f42933eabd545fd13e080fbf56ee6aa7e12...,https://www.aqa.org.uk/files/sample-papers-and...,completed,pending
3,4bd83e85-0a5d-4ee2-af33-a4640f4bc830,2023,June,2,question_paper,NaN,52f67d882ddb6f4df1a8fc8f9a9670163bc5242c.pdf,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,8433047a46c08d03325fcb0a580ba9b744386f7d7b8dbd...,https://www.aqa.org.uk/files/sample-papers-and...,completed,pending
4,65ab6d7b-67a7-4ffe-b163-0d50cbd037f8,2022,June,1B,question_paper,Python,802591934c5ab724411b6a9a723f74fcab057ed7.pdf,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,b8c53317b668a6cfa7cf51b520246a81b6939dbf7d7f45...,https://www.aqa.org.uk/files/sample-papers-and...,completed,pending

AQA 8525 knowledge-base coverage:

,year,paper_1b_question_paper,paper_1_mark_scheme,paper_2_question_paper,paper_2_mark_scheme
0,2022,✓,✗,✗,✗
1,2023,✓,✗,✓,✓
2,2024,✗,✗,✗,✗
3,2025,✗,✗,✗,✗

==============================================================
AQA 8525 ASSESSMENT KNOWLEDGE-BASE COVERAGE
==============================================================
Expected documents: 16
Requirements met:   4
Requirements missing: 12
==============================================================

Knowledge base is still incomplete.
The following official documents are missing:

    year        required_document paper_code   document_type   status
0   2022      Paper 1 Mark Scheme          1     mark_scheme  missing
1   2022   Paper 2 Question Paper          2  question_paper  missing
2   2022      Paper 2 Mark Scheme          2     mark_scheme  missing
3   2023      Paper 1 Mark Scheme          1     mark_scheme  missing
4   2024  Paper 1B Question Paper         1B  question_paper  missing
5   2024      Paper 1 Mark Scheme          1     mark_scheme  missing
6   2024   Paper 2 Question Paper          2  question_paper  missing
7   2024      Paper 2 Mark Scheme          2     mark_scheme  missing
8   2025  Paper 1B Question Paper         1B  question_paper  missing
9   2025      Paper 1 Mark Scheme          1     mark_scheme  missing
10  2025   Paper 2 Question Paper          2  question_paper  missing
11  2025      Paper 2 Mark Scheme          2     mark_scheme  missing

Saved reports:
- Complete manifest: C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_complete_manifest_2022_2025.csv
- Coverage report:   C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_coverage_2022_2025.csv
- Missing documents: C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_missing_documents_2022_2025.csv

In [19]:
# ============================================================
# AQA 8525 — COMPLETE DIRECT INGESTION PASS
# YEARS: 2022, 2023, 2024, 2025
#
# This cell:
# 1. Fixes shared Paper 1 mark-scheme classification.
# 2. Repairs incorrectly stored mark-scheme records.
# 3. Attempts all predictable official AQA filestore URLs.
# 4. Runs validated PDF ingestion.
# 5. Generates the final coverage report.
# ============================================================

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pandas as pd
from sqlalchemy import select
from sqlalchemy.orm import Session


# ------------------------------------------------------------
# 1. Correct Paper-code detection
# ------------------------------------------------------------

def detect_paper_code(
    text_upper: str,
    title: str,
    file_name: str,
    document_type: str,
) -> tuple[str | None, str | None]:
    """
    Detect supported AQA GCSE Computer Science 8525 papers.

    Returns:
        (paper_code, programming_language)

    Supported records:
        Question paper 1B -> ("1B", "Python")
        Shared mark scheme 1 -> ("1", "Shared across 1A/1B/1C")
        Question/mark scheme 2 -> ("2", None)
    """

    combined = re.sub(
        r"\s+",
        "",
        f"{text_upper}\n{title.upper()}\n{file_name.upper()}",
    )

    # --------------------------------------------------------
    # IMPORTANT:
    # Check shared Paper 1 mark schemes BEFORE checking 1B.
    #
    # A shared mark scheme contains references to:
    # 8525/1A, 8525/1B and 8525/1C.
    # --------------------------------------------------------

    if document_type == "mark_scheme":
        shared_paper_1_signals = (
            "8525/1A" in combined
            or "8525A/1" in combined
            or "8525/1B" in combined
            or "8525B/1" in combined
            or "8525/1C" in combined
            or "8525C/1" in combined
            or "8525/1/MS" in combined
            or "AQA-85251-MS" in combined
        )

        if shared_paper_1_signals:
            return (
                "1",
                "Shared across 1A/1B/1C",
            )

    # --------------------------------------------------------
    # Paper 1B Python question paper
    # --------------------------------------------------------

    paper_1b_signals = (
        "8525/1B" in combined
        or "8525B/1" in combined
        or "AQA-85251B-QP" in combined
    )

    if paper_1b_signals:
        return "1B", "Python"

    # --------------------------------------------------------
    # Explicitly reject Paper 1A and Paper 1C question papers
    # --------------------------------------------------------

    if document_type == "question_paper":
        unsupported_language_variant = (
            "8525/1A" in combined
            or "8525A/1" in combined
            or "AQA-85251A-QP" in combined
            or "8525/1C" in combined
            or "8525C/1" in combined
            or "AQA-85251C-QP" in combined
        )

        if unsupported_language_variant:
            return None, None

    # --------------------------------------------------------
    # Paper 2 question paper or mark scheme
    # --------------------------------------------------------

    paper_2_signals = (
        "8525/2" in combined
        or "AQA-85252-QP" in combined
        or "AQA-85252-MS" in combined
    )

    if paper_2_signals:
        return "2", None

    return None, None


print("Updated detect_paper_code() successfully.")


# ------------------------------------------------------------
# 2. Repair existing incorrectly classified Paper 1 schemes
# ------------------------------------------------------------

repaired_records: list[dict[str, Any]] = []

with Session(engine) as session:
    incorrect_mark_schemes = session.scalars(
        select(AssessmentDocument).where(
            AssessmentDocument.exam_board == "AQA",
            AssessmentDocument.specification_code == "8525",
            AssessmentDocument.document_type == "mark_scheme",
            AssessmentDocument.paper_code == "1B",
        )
    ).all()

    for record in incorrect_mark_schemes:
        old_cache_path = (
            Path(record.local_cache_path)
            if record.local_cache_path
            else None
        )

        new_cache_path = old_cache_path

        if old_cache_path is not None:
            corrected_file_name = old_cache_path.name.replace(
                "_1B_MARK_SCHEME",
                "_1_MARK_SCHEME",
            )

            new_cache_path = (
                old_cache_path.parent
                / corrected_file_name
            )

            if (
                old_cache_path.exists()
                and old_cache_path != new_cache_path
            ):
                if new_cache_path.exists():
                    # Existing corrected copy already exists.
                    old_cache_path.unlink()
                else:
                    old_cache_path.rename(new_cache_path)

        previous_paper_code = record.paper_code

        record.paper_code = "1"
        record.programming_language = (
            "Shared across 1A/1B/1C"
        )

        if new_cache_path is not None:
            record.local_cache_path = str(
                new_cache_path
            )

        record.updated_at = utc_now()

        repaired_records.append(
            {
                "database_id": str(record.id),
                "year": record.year,
                "previous_paper_code": previous_paper_code,
                "corrected_paper_code": record.paper_code,
                "local_cache_path": record.local_cache_path,
            }
        )

    session.commit()


print(
    f"Existing Paper 1 mark schemes repaired: "
    f"{len(repaired_records)}"
)

if repaired_records:
    display(
        pd.DataFrame(repaired_records)
    )


# ------------------------------------------------------------
# 3. Generate all expected official AQA URLs
# ------------------------------------------------------------

REQUIRED_YEARS = [
    2022,
    2023,
    2024,
    2025,
]

DIRECT_DOCUMENT_DEFINITIONS = [
    {
        "paper_code": "1B",
        "document_type": "question_paper",
        "title_template": (
            "Question paper: Paper 1B "
            "Computational thinking and programming skills "
            "- June {year}"
        ),
        "filename_template": (
            "AQA-85251B-QP-JUN{short_year}.PDF"
        ),
    },
    {
        "paper_code": "1",
        "document_type": "mark_scheme",
        "title_template": (
            "Mark scheme: Paper 1 "
            "Computational thinking and programming skills "
            "- June {year}"
        ),
        "filename_template": (
            "AQA-85251-MS-JUN{short_year}.PDF"
        ),
    },
    {
        "paper_code": "2",
        "document_type": "question_paper",
        "title_template": (
            "Question paper: Paper 2 "
            "Computing concepts - June {year}"
        ),
        "filename_template": (
            "AQA-85252-QP-JUN{short_year}.PDF"
        ),
    },
    {
        "paper_code": "2",
        "document_type": "mark_scheme",
        "title_template": (
            "Mark scheme: Paper 2 "
            "Computing concepts - June {year}"
        ),
        "filename_template": (
            "AQA-85252-MS-JUN{short_year}.PDF"
        ),
    },
]


official_direct_links: list[DiscoveredLink] = []

for year in REQUIRED_YEARS:
    short_year = str(year)[-2:]

    base_url = (
        "https://filestore.aqa.org.uk/"
        "sample-papers-and-mark-schemes/"
        f"{year}/june"
    )

    for definition in DIRECT_DOCUMENT_DEFINITIONS:
        file_name = definition[
            "filename_template"
        ].format(
            short_year=short_year
        )

        source_url = (
            f"{base_url}/{file_name}"
        )

        title = definition[
            "title_template"
        ].format(
            year=year
        )

        official_direct_links.append(
            DiscoveredLink(
                url=source_url,
                title=title,
                discovered_via="official_direct_pattern",
            )
        )


direct_links_df = pd.DataFrame(
    [
        link.model_dump()
        for link in official_direct_links
    ]
)

print(
    "\nOfficial direct URLs generated:",
    len(official_direct_links),
)

display(
    direct_links_df
)


# ------------------------------------------------------------
# 4. Run validated ingestion
#
# run_source_ingestion performs:
# - HTTP validation
# - %PDF validation
# - SHA-256 hashing
# - PyMuPDF content validation
# - AQA / Computer Science / 8525 validation
# - database upsert
# ------------------------------------------------------------

direct_accepted_df, direct_issues_df, direct_counts = (
    run_source_ingestion(
        official_direct_links,
        include_non_live=False,
        request_delay_seconds=0.40,
    )
)


print("\nDirect ingestion summary:")

print(
    json.dumps(
        direct_counts,
        indent=2,
    )
)


if not direct_accepted_df.empty:
    print(
        "\nDocuments accepted or matched:"
    )

    display(
        direct_accepted_df.sort_values(
            [
                "year",
                "paper",
                "document_type",
            ],
            ascending=[
                False,
                True,
                True,
            ],
        )
    )


if not direct_issues_df.empty:
    print(
        "\nURLs that could not be downloaded "
        "or classified:"
    )

    display(
        direct_issues_df
    )


# ------------------------------------------------------------
# 5. Reload complete manifest from PostgreSQL
# ------------------------------------------------------------

with Session(engine) as session:
    database_documents = session.scalars(
        select(AssessmentDocument).where(
            AssessmentDocument.exam_board == "AQA",
            AssessmentDocument.qualification == "GCSE",
            AssessmentDocument.subject == "Computer Science",
            AssessmentDocument.specification_code == "8525",
            AssessmentDocument.document_category == "live_exam",
            AssessmentDocument.year.in_(REQUIRED_YEARS),
            AssessmentDocument.download_status == "completed",
        )
    ).all()


manifest_rows: list[dict[str, Any]] = []

for record in database_documents:
    manifest_rows.append(
        {
            "database_id": str(record.id),
            "year": record.year,
            "series": record.exam_series,
            "paper_code": record.paper_code,
            "document_type": record.document_type,
            "programming_language": (
                record.programming_language
            ),
            "file_name": record.original_file_name,
            "local_cache_path": record.local_cache_path,
            "file_hash": record.file_hash,
            "source_url": record.source_url,
            "download_status": record.download_status,
            "parsing_status": record.parsing_status,
        }
    )


complete_manifest_df = pd.DataFrame(
    manifest_rows
)

if complete_manifest_df.empty:
    raise RuntimeError(
        "No AQA 8525 documents were found "
        "in PostgreSQL."
    )


complete_manifest_df = (
    complete_manifest_df
    .sort_values(
        [
            "year",
            "paper_code",
            "document_type",
        ],
        ascending=[
            False,
            True,
            True,
        ],
    )
    .reset_index(
        drop=True
    )
)


print(
    "\nComplete PostgreSQL document manifest:"
)

display(
    complete_manifest_df
)


# ------------------------------------------------------------
# 6. Coverage validation
# ------------------------------------------------------------

REQUIRED_DOCUMENTS = [
    {
        "coverage_column": (
            "paper_1b_question_paper"
        ),
        "display_name": (
            "Paper 1B Question Paper"
        ),
        "paper_code": "1B",
        "document_type": "question_paper",
    },
    {
        "coverage_column": (
            "paper_1_mark_scheme"
        ),
        "display_name": (
            "Paper 1 Mark Scheme"
        ),
        "paper_code": "1",
        "document_type": "mark_scheme",
    },
    {
        "coverage_column": (
            "paper_2_question_paper"
        ),
        "display_name": (
            "Paper 2 Question Paper"
        ),
        "paper_code": "2",
        "document_type": "question_paper",
    },
    {
        "coverage_column": (
            "paper_2_mark_scheme"
        ),
        "display_name": (
            "Paper 2 Mark Scheme"
        ),
        "paper_code": "2",
        "document_type": "mark_scheme",
    },
]


coverage_rows: list[dict[str, Any]] = []
missing_rows: list[dict[str, Any]] = []

for year in REQUIRED_YEARS:
    year_records = complete_manifest_df[
        complete_manifest_df["year"] == year
    ]

    coverage_row: dict[str, Any] = {
        "year": year
    }

    for requirement in REQUIRED_DOCUMENTS:
        matches = year_records[
            (
                year_records["paper_code"]
                == requirement["paper_code"]
            )
            & (
                year_records["document_type"]
                == requirement["document_type"]
            )
        ]

        is_present = not matches.empty

        coverage_row[
            requirement["coverage_column"]
        ] = (
            "✓"
            if is_present
            else "✗"
        )

        if not is_present:
            missing_rows.append(
                {
                    "year": year,
                    "required_document": (
                        requirement["display_name"]
                    ),
                    "paper_code": (
                        requirement["paper_code"]
                    ),
                    "document_type": (
                        requirement["document_type"]
                    ),
                    "status": "missing",
                }
            )

    coverage_rows.append(
        coverage_row
    )


coverage_df = pd.DataFrame(
    coverage_rows
)

missing_documents_df = pd.DataFrame(
    missing_rows
)


print(
    "\nAQA 8525 coverage for 2022–2025:"
)

display(
    coverage_df
)


expected_count = (
    len(REQUIRED_YEARS)
    * len(REQUIRED_DOCUMENTS)
)

present_count = (
    expected_count
    - len(missing_rows)
)


print("\n" + "=" * 62)

print(
    "AQA 8525 KNOWLEDGE-BASE COMPLETENESS"
)

print("=" * 62)

print(
    f"Expected requirements: {expected_count}"
)

print(
    f"Requirements present: {present_count}"
)

print(
    f"Requirements missing: {len(missing_rows)}"
)

print("=" * 62)


if missing_rows:
    print(
        "\nKnowledge base is still incomplete."
    )

    display(
        missing_documents_df
    )

else:
    print(
        "\nAll 16 required documents are present."
    )

    print(
        "The document knowledge base is ready "
        "for question-level parsing."
    )


# ------------------------------------------------------------
# 7. Additional consistency checks
# ------------------------------------------------------------

invalid_shared_schemes = complete_manifest_df[
    (
        complete_manifest_df["document_type"]
        == "mark_scheme"
    )
    & (
        complete_manifest_df["paper_code"]
        == "1B"
    )
]

if not invalid_shared_schemes.empty:
    print(
        "\nWARNING: Some shared Paper 1 mark schemes "
        "are still incorrectly classified as 1B."
    )

    display(
        invalid_shared_schemes
    )

else:
    print(
        "\nShared Paper 1 mark-scheme "
        "classification check passed."
    )


# ------------------------------------------------------------
# 8. Save reports
# ------------------------------------------------------------

OUTPUT_DIR = Path(
    OUTPUT_DIR
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

manifest_output_path = (
    OUTPUT_DIR
    / "aqa_8525_complete_manifest_2022_2025.csv"
)

coverage_output_path = (
    OUTPUT_DIR
    / "aqa_8525_coverage_2022_2025.csv"
)

missing_output_path = (
    OUTPUT_DIR
    / "aqa_8525_missing_documents_2022_2025.csv"
)

issues_output_path = (
    OUTPUT_DIR
    / "aqa_8525_direct_url_issues.csv"
)


complete_manifest_df.to_csv(
    manifest_output_path,
    index=False,
)

coverage_df.to_csv(
    coverage_output_path,
    index=False,
)

missing_documents_df.to_csv(
    missing_output_path,
    index=False,
)

direct_issues_df.to_csv(
    issues_output_path,
    index=False,
)


print("\nSaved reports:")

print(
    f"- Manifest: {manifest_output_path}"
)

print(
    f"- Coverage: {coverage_output_path}"
)

print(
    f"- Missing:  {missing_output_path}"
)

print(
    f"- URL issues: {issues_output_path}"
)

Updated detect_paper_code() successfully.
Existing Paper 1 mark schemes repaired: 1

,database_id,year,previous_paper_code,corrected_paper_code,local_cache_path
0,5b99ed2b-a3ba-4d16-8e85-baf965b4cfbe,2023,1B,1,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...

Official direct URLs generated: 16

,url,title,discovered_via
0,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,official_direct_pattern
1,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 1 Computational thinking an...,official_direct_pattern
2,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,official_direct_pattern
3,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 2 Computing concepts - June...,official_direct_pattern
4,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,official_direct_pattern
5,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 1 Computational thinking an...,official_direct_pattern
6,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,official_direct_pattern
7,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 2 Computing concepts - June...,official_direct_pattern
8,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,official_direct_pattern
9,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 1 Computational thinking an...,official_direct_pattern
10,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,official_direct_pattern
11,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 2 Computing concepts - June...,official_direct_pattern
12,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,official_direct_pattern
13,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 1 Computational thinking an...,official_direct_pattern
14,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,official_direct_pattern
15,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 2 Computing concepts - June...,official_direct_pattern

[1/16] Question paper: Paper 1B Computational thinking and programming skills - June 2022
[2/16] Mark scheme: Paper 1 Computational thinking and programming skills - June 2022
[3/16] Question paper: Paper 2 Computing concepts - June 2022
[4/16] Mark scheme: Paper 2 Computing concepts - June 2022
[5/16] Question paper: Paper 1B Computational thinking and programming skills - June 2023
[6/16] Mark scheme: Paper 1 Computational thinking and programming skills - June 2023
[7/16] Question paper: Paper 2 Computing concepts - June 2023
[8/16] Mark scheme: Paper 2 Computing concepts - June 2023
[9/16] Question paper: Paper 1B Computational thinking and programming skills - June 2024
[10/16] Mark scheme: Paper 1 Computational thinking and programming skills - June 2024
[11/16] Question paper: Paper 2 Computing concepts - June 2024
[12/16] Mark scheme: Paper 2 Computing concepts - June 2024
[13/16] Question paper: Paper 1B Computational thinking and programming skills - June 2025
[14/16] Mark scheme: Paper 1 Computational thinking and programming skills - June 2025
[15/16] Question paper: Paper 2 Computing concepts - June 2025
[16/16] Mark scheme: Paper 2 Computing concepts - June 2025

Direct ingestion summary:
{
  "candidates": 16,
  "accepted": 8,
  "irrelevant_or_excluded": 0,
  "download_failed": 8,
  "classification_failed": 0,
  "inserted": 3,
  "updated": 0,
  "skipped_unchanged": 5
}

Documents accepted or matched:

,database_id,year,series,paper,document_type,category,programming_language,file_hash,local_cache_path,source_url,database_action
5,5b99ed2b-a3ba-4d16-8e85-baf965b4cfbe,2023,June,1,mark_scheme,live_exam,Shared across 1A/1B/1C,04ef1087412b9376884cf60ab11bea1c23a7adecb9fb57...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://filestore.aqa.org.uk/sample-papers-and...,skipped_unchanged
4,9040b67e-56ad-4f90-b98a-8e01ca7c2ba9,2023,June,1B,question_paper,live_exam,Python,6767013c28067e540ea3942d231b2b048539a888658135...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://filestore.aqa.org.uk/sample-papers-and...,skipped_unchanged
7,1a21a37c-b64a-44af-9caa-2b4ec5b6f039,2023,June,2,mark_scheme,live_exam,NaN,f32360582e4f42933eabd545fd13e080fbf56ee6aa7e12...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://filestore.aqa.org.uk/sample-papers-and...,skipped_unchanged
6,4bd83e85-0a5d-4ee2-af33-a4640f4bc830,2023,June,2,question_paper,live_exam,NaN,8433047a46c08d03325fcb0a580ba9b744386f7d7b8dbd...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://filestore.aqa.org.uk/sample-papers-and...,skipped_unchanged
1,72187526-cf36-4dd2-8fe1-72714fcd5bc6,2022,June,1,mark_scheme,live_exam,Shared across 1A/1B/1C,bf7e27ebf6a71d97a1a8b72042e256c69e69eb3061c751...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://filestore.aqa.org.uk/sample-papers-and...,inserted
0,65ab6d7b-67a7-4ffe-b163-0d50cbd037f8,2022,June,1B,question_paper,live_exam,Python,b8c53317b668a6cfa7cf51b520246a81b6939dbf7d7f45...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://filestore.aqa.org.uk/sample-papers-and...,skipped_unchanged
3,1ba9efe8-5706-4b54-b738-0dea8412368b,2022,June,2,mark_scheme,live_exam,NaN,59dab52d0ea04346de0265d6f613a6e8b2acdb49cd0d0c...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://filestore.aqa.org.uk/sample-papers-and...,inserted
2,b973e690-5682-49d3-83e2-592bc28c8ab8,2022,June,2,question_paper,live_exam,NaN,f949a424842b867795ca8132cc9875b2eadb2476b9d6bb...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://filestore.aqa.org.uk/sample-papers-and...,inserted

URLs that could not be downloaded or classified:

,source_url,title,stage,error
0,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,download,404 Client Error: Not Found for url: https://w...
1,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 1 Computational thinking an...,download,404 Client Error: Not Found for url: https://w...
2,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,download,404 Client Error: Not Found for url: https://w...
3,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 2 Computing concepts - June...,download,404 Client Error: Not Found for url: https://w...
4,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,download,404 Client Error: Not Found for url: https://w...
5,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 1 Computational thinking an...,download,404 Client Error: Not Found for url: https://w...
6,https://filestore.aqa.org.uk/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,download,404 Client Error: Not Found for url: https://w...
7,https://filestore.aqa.org.uk/sample-papers-and...,Mark scheme: Paper 2 Computing concepts - June...,download,404 Client Error: Not Found for url: https://w...

Complete PostgreSQL document manifest:

,database_id,year,series,paper_code,document_type,programming_language,file_name,local_cache_path,file_hash,source_url,download_status,parsing_status
0,5b99ed2b-a3ba-4d16-8e85-baf965b4cfbe,2023,June,1,mark_scheme,Shared across 1A/1B/1C,AQA-85251-MS-JUN23.PDF,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,04ef1087412b9376884cf60ab11bea1c23a7adecb9fb57...,https://filestore.aqa.org.uk/sample-papers-and...,completed,pending
1,9040b67e-56ad-4f90-b98a-8e01ca7c2ba9,2023,June,1B,question_paper,Python,AQA-85251B-QP-JUN23.PDF,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,6767013c28067e540ea3942d231b2b048539a888658135...,https://filestore.aqa.org.uk/sample-papers-and...,completed,pending
2,1a21a37c-b64a-44af-9caa-2b4ec5b6f039,2023,June,2,mark_scheme,NaN,AQA-85252-MS-JUN23.PDF,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,f32360582e4f42933eabd545fd13e080fbf56ee6aa7e12...,https://filestore.aqa.org.uk/sample-papers-and...,completed,pending
3,4bd83e85-0a5d-4ee2-af33-a4640f4bc830,2023,June,2,question_paper,NaN,AQA-85252-QP-JUN23.PDF,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,8433047a46c08d03325fcb0a580ba9b744386f7d7b8dbd...,https://filestore.aqa.org.uk/sample-papers-and...,completed,pending
4,72187526-cf36-4dd2-8fe1-72714fcd5bc6,2022,June,1,mark_scheme,Shared across 1A/1B/1C,AQA-85251-MS-JUN22.PDF,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,bf7e27ebf6a71d97a1a8b72042e256c69e69eb3061c751...,https://filestore.aqa.org.uk/sample-papers-and...,completed,pending
5,65ab6d7b-67a7-4ffe-b163-0d50cbd037f8,2022,June,1B,question_paper,Python,AQA-85251B-QP-JUN22.PDF,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,b8c53317b668a6cfa7cf51b520246a81b6939dbf7d7f45...,https://filestore.aqa.org.uk/sample-papers-and...,completed,pending
6,1ba9efe8-5706-4b54-b738-0dea8412368b,2022,June,2,mark_scheme,NaN,AQA-85252-MS-JUN22.PDF,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,59dab52d0ea04346de0265d6f613a6e8b2acdb49cd0d0c...,https://filestore.aqa.org.uk/sample-papers-and...,completed,pending
7,b973e690-5682-49d3-83e2-592bc28c8ab8,2022,June,2,question_paper,NaN,AQA-85252-QP-JUN22.PDF,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,f949a424842b867795ca8132cc9875b2eadb2476b9d6bb...,https://filestore.aqa.org.uk/sample-papers-and...,completed,pending

AQA 8525 coverage for 2022–2025:

,year,paper_1b_question_paper,paper_1_mark_scheme,paper_2_question_paper,paper_2_mark_scheme
0,2022,✓,✓,✓,✓
1,2023,✓,✓,✓,✓
2,2024,✗,✗,✗,✗
3,2025,✗,✗,✗,✗

==============================================================
AQA 8525 KNOWLEDGE-BASE COMPLETENESS
==============================================================
Expected requirements: 16
Requirements present: 8
Requirements missing: 8
==============================================================

Knowledge base is still incomplete.

   year        required_document paper_code   document_type   status
0  2024  Paper 1B Question Paper         1B  question_paper  missing
1  2024      Paper 1 Mark Scheme          1     mark_scheme  missing
2  2024   Paper 2 Question Paper          2  question_paper  missing
3  2024      Paper 2 Mark Scheme          2     mark_scheme  missing
4  2025  Paper 1B Question Paper         1B  question_paper  missing
5  2025      Paper 1 Mark Scheme          1     mark_scheme  missing
6  2025   Paper 2 Question Paper          2  question_paper  missing
7  2025      Paper 2 Mark Scheme          2     mark_scheme  missing

Shared Paper 1 mark-scheme classification check passed.

Saved reports:
- Manifest: C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_complete_manifest_2022_2025.csv
- Coverage: C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_coverage_2022_2025.csv
- Missing:  C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_missing_documents_2022_2025.csv
- URL issues: C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_direct_url_issues.csv

Get 2024 question papers and mark schemes

In [20]:
# ============================================================
# TARGETED AQA RECOVERY — 2024 AND 2025
#
# Windows + Jupyter safe:
# Playwright runs in a separate Python process.
#
# Requires existing notebook objects:
# - AQA_SOURCE_PAGE
# - OUTPUT_DIR
# - DiscoveredLink
# - run_source_ingestion
# - engine
# - AssessmentDocument
# - Session
# - select
# ============================================================

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from textwrap import dedent
from typing import Any

import pandas as pd
from sqlalchemy import select
from sqlalchemy.orm import Session


# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

TARGET_YEARS = [2024, 2025]

OUTPUT_DIR = Path(OUTPUT_DIR).resolve()
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TARGET_RUNNER_PATH = (
    OUTPUT_DIR
    / "_aqa_targeted_year_search_runner.py"
)

TARGET_RESULTS_PATH = (
    OUTPUT_DIR
    / "_aqa_targeted_2024_2025_links.json"
)


# ------------------------------------------------------------
# Standalone Playwright search script
# ------------------------------------------------------------

target_runner_script = dedent(
    r'''
    from __future__ import annotations

    import argparse
    import json
    import re
    from pathlib import Path
    from urllib.parse import unquote, urljoin

    from playwright.sync_api import (
        TimeoutError as PlaywrightTimeoutError,
        sync_playwright,
    )


    PDF_URL_PATTERN = re.compile(
        r"(?i)(?:"
        r"\.pdf(?:$|[?#])"
        r"|filestore\.aqa\.org\.uk"
        r"|cdn\.sanity\.io/files/"
        r"|aqa\.org\.uk/files/"
        r")"
    )


    def normalize_url(
        url: str,
        base_url: str,
    ) -> str:
        return urljoin(
            base_url,
            unquote(url.strip()),
        )


    def accept_cookie_banner(page) -> None:
        patterns = [
            re.compile(r"accept all", re.I),
            re.compile(r"accept cookies", re.I),
            re.compile(r"allow all", re.I),
            re.compile(r"agree", re.I),
        ]

        for pattern in patterns:
            try:
                button = page.get_by_role(
                    "button",
                    name=pattern,
                ).first

                if (
                    button.count()
                    and button.is_visible()
                ):
                    button.click(timeout=3_000)
                    page.wait_for_timeout(500)
                    return

            except Exception:
                continue


    def find_search_input(page):
        selectors = [
            "input[placeholder*='Search resources' i]",
            "input[aria-label*='Search resources' i]",
            "input[type='search']",
            "input[name*='search' i]",
            "input[id*='search' i]",
        ]

        for selector in selectors:
            try:
                locator = page.locator(selector)

                for index in range(locator.count()):
                    candidate = locator.nth(index)

                    if candidate.is_visible():
                        return candidate

            except Exception:
                continue

        try:
            candidate = page.get_by_role(
                "textbox",
                name=re.compile(
                    r"search resources",
                    re.I,
                ),
            ).first

            if (
                candidate.count()
                and candidate.is_visible()
            ):
                return candidate

        except Exception:
            pass

        return None


    def get_resource_context(
        anchor,
    ) -> str:
        """
        Extract text from the anchor's surrounding result card.
        """

        try:
            context_text = anchor.evaluate(
                """
                element => {
                    let current = element;

                    for (
                        let level = 0;
                        level < 7 && current;
                        level += 1
                    ) {
                        const text = (
                            current.innerText || ""
                        ).trim();

                        if (
                            /question paper|mark scheme/i.test(text)
                            && text.length < 2500
                        ) {
                            return text;
                        }

                        current = current.parentElement;
                    }

                    return (
                        element.innerText || ""
                    ).trim();
                }
                """
            )

            return " ".join(
                context_text.split()
            )

        except Exception:
            try:
                return " ".join(
                    anchor.inner_text().split()
                )
            except Exception:
                return ""


    def collect_current_results(
        page,
        source_page: str,
        target_year: int,
    ) -> list[dict]:
        collected: list[dict] = []

        anchors = page.locator("a[href]")

        for index in range(
            anchors.count()
        ):
            anchor = anchors.nth(index)

            try:
                href = (
                    anchor.get_attribute("href")
                    or ""
                )

                if not href:
                    continue

                absolute_url = normalize_url(
                    href,
                    source_page,
                )

                context_text = (
                    get_resource_context(anchor)
                )

                combined = (
                    f"{context_text} "
                    f"{absolute_url}"
                ).lower()

                is_assessment_document = (
                    "question paper" in combined
                    or "mark scheme" in combined
                )

                if not is_assessment_document:
                    continue

                if str(target_year) not in combined:
                    continue

                # Retain only relevant paper families.
                is_relevant_paper = any(
                    phrase in combined
                    for phrase in (
                        "paper 1b",
                        "paper 1 computational",
                        "paper 2",
                        "8525/1b",
                        "8525/1",
                        "8525/2",
                        "85251b",
                        "85251-ms",
                        "85252",
                    )
                )

                if not is_relevant_paper:
                    continue

                # Exclude C# and VB.NET question papers.
                unsupported_question_variant = (
                    "question paper" in combined
                    and (
                        "paper 1a" in combined
                        or "paper 1c" in combined
                        or "8525/1a" in combined
                        or "8525/1c" in combined
                    )
                )

                if unsupported_question_variant:
                    continue

                collected.append(
                    {
                        "url": absolute_url,
                        "title": context_text,
                        "discovered_via": (
                            f"targeted_search_{target_year}"
                        ),
                    }
                )

            except Exception:
                continue

        return collected


    def click_next_if_available(
        page,
    ) -> bool:
        selectors = [
            "button:has-text('Next')",
            "a:has-text('Next')",
            "[aria-label='Next']",
            "[aria-label*='next' i]",
            "[title='Next']",
            "[title*='next' i]",
        ]

        for selector in selectors:
            try:
                locator = page.locator(
                    selector
                )

                if not locator.count():
                    continue

                candidate = locator.last

                if not candidate.is_visible():
                    continue

                aria_disabled = (
                    candidate.get_attribute(
                        "aria-disabled"
                    )
                    or ""
                ).lower()

                disabled = (
                    candidate.get_attribute(
                        "disabled"
                    )
                )

                class_name = (
                    candidate.get_attribute(
                        "class"
                    )
                    or ""
                ).lower()

                if (
                    aria_disabled == "true"
                    or disabled is not None
                    or "disabled" in class_name
                ):
                    continue

                previous_text = (
                    page.locator(
                        "body"
                    ).inner_text()
                )

                candidate.scroll_into_view_if_needed()
                candidate.click(timeout=5_000)

                try:
                    page.wait_for_load_state(
                        "networkidle",
                        timeout=15_000,
                    )
                except PlaywrightTimeoutError:
                    pass

                page.wait_for_timeout(1_500)

                current_text = (
                    page.locator(
                        "body"
                    ).inner_text()
                )

                return (
                    current_text
                    != previous_text
                )

            except Exception:
                continue

        return False


    def search_year(
        browser,
        source_page: str,
        year: int,
        max_pages: int,
    ) -> list[dict]:

        context = browser.new_context(
            viewport={
                "width": 1440,
                "height": 1100,
            },
            user_agent=(
                "Mozilla/5.0 "
                "(Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 "
                "(KHTML, like Gecko) "
                "Chrome/130.0 Safari/537.36"
            ),
        )

        page = context.new_page()

        page.goto(
            source_page,
            wait_until="domcontentloaded",
            timeout=60_000,
        )

        accept_cookie_banner(page)

        try:
            page.wait_for_load_state(
                "networkidle",
                timeout=20_000,
            )
        except PlaywrightTimeoutError:
            pass

        page.wait_for_timeout(2_000)

        search_input = find_search_input(
            page
        )

        if search_input is None:
            context.close()

            raise RuntimeError(
                "Could not find the AQA "
                "'Search resources' input."
            )

        search_term = (
            f"June {year}"
        )

        print(
            f"Searching AQA resources for: "
            f"{search_term}",
            flush=True,
        )

        search_input.fill(
            search_term
        )

        try:
            search_input.press(
                "Enter"
            )
        except Exception:
            pass

        try:
            page.wait_for_load_state(
                "networkidle",
                timeout=15_000,
            )
        except PlaywrightTimeoutError:
            pass

        page.wait_for_timeout(3_000)

        results: dict[str, dict] = {}
        seen_signatures: set[
            tuple[str, ...]
        ] = set()

        for page_number in range(
            1,
            max_pages + 1,
        ):
            page.evaluate(
                "window.scrollTo("
                "0, document.body.scrollHeight"
                ")"
            )

            page.wait_for_timeout(
                1_500
            )

            page_results = (
                collect_current_results(
                    page,
                    source_page,
                    year,
                )
            )

            for item in page_results:
                results[
                    item["url"]
                ] = item

            signature = tuple(
                sorted(
                    item["url"]
                    for item in page_results
                )
            )

            print(
                f"Year {year}, results page "
                f"{page_number}: "
                f"{len(page_results)} links",
                flush=True,
            )

            if (
                signature
                and signature
                in seen_signatures
            ):
                break

            seen_signatures.add(
                signature
            )

            if not click_next_if_available(
                page
            ):
                break

        context.close()

        return list(
            results.values()
        )


    def main() -> None:
        parser = argparse.ArgumentParser()

        parser.add_argument(
            "--source-page",
            required=True,
        )

        parser.add_argument(
            "--output-json",
            required=True,
        )

        parser.add_argument(
            "--years",
            nargs="+",
            type=int,
            required=True,
        )

        parser.add_argument(
            "--max-pages",
            type=int,
            default=10,
        )

        parser.add_argument(
            "--show-browser",
            action="store_true",
        )

        arguments = parser.parse_args()

        all_results: dict[str, dict] = {}

        with sync_playwright() as playwright:
            browser = (
                playwright.chromium.launch(
                    headless=(
                        not arguments.show_browser
                    )
                )
            )

            for year in arguments.years:
                year_results = search_year(
                    browser,
                    arguments.source_page,
                    year,
                    arguments.max_pages,
                )

                for item in year_results:
                    all_results[
                        item["url"]
                    ] = item

            browser.close()

        output_path = Path(
            arguments.output_json
        ).resolve()

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        final_results = sorted(
            all_results.values(),
            key=lambda item: (
                item["discovered_via"],
                item["title"],
                item["url"],
            ),
        )

        output_path.write_text(
            json.dumps(
                final_results,
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )

        print(
            f"Saved {len(final_results)} "
            f"targeted links to {output_path}",
            flush=True,
        )


    if __name__ == "__main__":
        main()
    '''
)


TARGET_RUNNER_PATH.write_text(
    target_runner_script,
    encoding="utf-8",
)


# ------------------------------------------------------------
# Run targeted discovery externally
# ------------------------------------------------------------

command = [
    sys.executable,
    str(TARGET_RUNNER_PATH),
    "--source-page",
    AQA_SOURCE_PAGE,
    "--output-json",
    str(TARGET_RESULTS_PATH),
    "--years",
    "2024",
    "2025",
    "--max-pages",
    "10",
]


print(
    "Starting targeted AQA search "
    "for 2024 and 2025...\n"
)

process = subprocess.run(
    command,
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace",
)


if process.stdout.strip():
    print(
        process.stdout
    )

if process.returncode != 0:
    if process.stderr.strip():
        print(
            process.stderr
        )

    raise RuntimeError(
        "Targeted Playwright search failed."
    )


# ------------------------------------------------------------
# Load discovered links
# ------------------------------------------------------------

if not TARGET_RESULTS_PATH.exists():
    raise FileNotFoundError(
        "Targeted search completed without "
        "creating the expected JSON file."
    )


raw_targeted_links = json.loads(
    TARGET_RESULTS_PATH.read_text(
        encoding="utf-8"
    )
)


targeted_links = [
    DiscoveredLink(**item)
    for item in raw_targeted_links
]


targeted_links_df = pd.DataFrame(
    [
        item.model_dump()
        for item in targeted_links
    ]
)


print(
    f"\nTargeted links found: "
    f"{len(targeted_links)}"
)

if targeted_links_df.empty:
    print(
        "No public 2024/2025 links were found."
    )

else:
    display(
        targeted_links_df
    )


# ------------------------------------------------------------
# Download, validate and register
# ------------------------------------------------------------

if targeted_links:
    (
        targeted_accepted_df,
        targeted_issues_df,
        targeted_counts,
    ) = run_source_ingestion(
        targeted_links,
        include_non_live=False,
        request_delay_seconds=0.40,
    )

    print(
        "\nTargeted ingestion summary:"
    )

    print(
        json.dumps(
            targeted_counts,
            indent=2,
        )
    )

    if not targeted_accepted_df.empty:
        display(
            targeted_accepted_df.sort_values(
                [
                    "year",
                    "paper",
                    "document_type",
                ],
                ascending=[
                    False,
                    True,
                    True,
                ],
            )
        )

    if not targeted_issues_df.empty:
        print(
            "\nTargeted ingestion issues:"
        )

        display(
            targeted_issues_df
        )


# ------------------------------------------------------------
# Reload 2024/2025 database records
# ------------------------------------------------------------

with Session(engine) as session:
    remaining_records = session.scalars(
        select(AssessmentDocument).where(
            AssessmentDocument.exam_board
            == "AQA",

            AssessmentDocument.specification_code
            == "8525",

            AssessmentDocument.year.in_(
                TARGET_YEARS
            ),

            AssessmentDocument.document_category
            == "live_exam",

            AssessmentDocument.download_status
            == "completed",
        )
    ).all()


remaining_rows: list[
    dict[str, Any]
] = []

for record in remaining_records:
    remaining_rows.append(
        {
            "database_id": str(
                record.id
            ),
            "year": record.year,
            "series": record.exam_series,
            "paper_code": (
                record.paper_code
            ),
            "document_type": (
                record.document_type
            ),
            "programming_language": (
                record.programming_language
            ),
            "local_cache_path": (
                record.local_cache_path
            ),
            "source_url": (
                record.source_url
            ),
        }
    )


remaining_manifest_df = pd.DataFrame(
    remaining_rows
)


print(
    "\nCurrent 2024/2025 database records:"
)

if remaining_manifest_df.empty:
    print(
        "No 2024/2025 documents are "
        "currently registered."
    )

else:
    display(
        remaining_manifest_df.sort_values(
            [
                "year",
                "paper_code",
                "document_type",
            ]
        )
    )


# ------------------------------------------------------------
# Coverage matrix for remaining years
# ------------------------------------------------------------

requirements = [
    (
        "paper_1b_question_paper",
        "1B",
        "question_paper",
    ),
    (
        "paper_1_mark_scheme",
        "1",
        "mark_scheme",
    ),
    (
        "paper_2_question_paper",
        "2",
        "question_paper",
    ),
    (
        "paper_2_mark_scheme",
        "2",
        "mark_scheme",
    ),
]


coverage_rows = []

for year in TARGET_YEARS:
    if remaining_manifest_df.empty:
        year_data = pd.DataFrame()

    else:
        year_data = (
            remaining_manifest_df[
                remaining_manifest_df[
                    "year"
                ]
                == year
            ]
        )

    row = {
        "year": year
    }

    for (
        column_name,
        paper_code,
        document_type,
    ) in requirements:

        if year_data.empty:
            present = False

        else:
            present = not year_data[
                (
                    year_data[
                        "paper_code"
                    ]
                    == paper_code
                )
                & (
                    year_data[
                        "document_type"
                    ]
                    == document_type
                )
            ].empty

        row[column_name] = (
            "✓"
            if present
            else "✗"
        )

    coverage_rows.append(
        row
    )


remaining_coverage_df = pd.DataFrame(
    coverage_rows
)


print(
    "\nRemaining-year coverage:"
)

display(
    remaining_coverage_df
)


remaining_coverage_path = (
    OUTPUT_DIR
    / "aqa_8525_coverage_2024_2025.csv"
)

remaining_coverage_df.to_csv(
    remaining_coverage_path,
    index=False,
)

print(
    f"\nSaved coverage report: "
    f"{remaining_coverage_path}"
)

Starting targeted AQA search for 2024 and 2025...

Searching AQA resources for: June 2024
Year 2024, results page 1: 4 links
Searching AQA resources for: June 2025
Year 2025, results page 1: 1 links
Saved 5 targeted links to C:\Users\hp\EDTECH\Agent2\OUTPUT\_aqa_targeted_2024_2025_links.json


Targeted links found: 5

,url,title,discovered_via
0,https://www.aqa.org.uk/files/sample-papers-and...,Mark scheme: Paper 1A Computational thinking a...,targeted_search_2024
1,https://www.aqa.org.uk/files/sample-papers-and...,Question paper ( Modified A4 18pt): Paper 1B C...,targeted_search_2024
2,https://www.aqa.org.uk/files/sample-papers-and...,Question paper: Paper 1B Computational thinkin...,targeted_search_2024
3,https://www.aqa.org.uk/files/sample-papers-and...,Question paper: Paper 2 Computing concepts - J...,targeted_search_2024
4,https://www.aqa.org.uk/files/fHDU1dLPgDwvQhfFo...,Question paper (Modified A4 18pt): Paper 1B Co...,targeted_search_2025

[1/5] Mark scheme: Paper 1A Computational thinking and programming skills (C#) - June 2024 - Computer Science GCSE Computer Science • PDF • 524.73 KB • Published: 11 Jul 2025
[2/5] Question paper ( Modified A4 18pt): Paper 1B Computational thinking and programming skills (Python) - June 2024 - Computer Science GCSE Computer Science • PDF • 787.42 KB • Published: 11 Jul 2025
[3/5] Question paper: Paper 1B Computational thinking and programming skills (Python) - June 2024 - Computer Science GCSE Computer Science • PDF • 1.23 MB • Published: 11 Jul 2025
[4/5] Question paper: Paper 2 Computing concepts - June 2024 - Computer Science GCSE Computer Science • PDF • 1.25 MB • Published: 11 Jul 2025
[5/5] Question paper (Modified A4 18pt): Paper 1B Computational thinking and programming skills (Python) - June 2025 - Computer Science GCSE Computer Science • PDF • 600.81 KB • Published: 10 Jul 2026

Targeted ingestion summary:
{
  "candidates": 5,
  "accepted": 5,
  "irrelevant_or_excluded": 0,
  "download_failed": 0,
  "classification_failed": 0,
  "inserted": 5,
  "updated": 0,
  "skipped_unchanged": 0
}

,database_id,year,series,paper,document_type,category,programming_language,file_hash,local_cache_path,source_url,database_action
4,b365d7ce-a0ab-4096-8c32-4577e1091415,2025,June,1B,question_paper,live_exam,Python,19613db1a65e637fe0f5ec1cbaedbd3bf965e10d30f714...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/fHDU1dLPgDwvQhfFo...,inserted
0,4a22fdb4-8d0b-42ca-9f59-bd6ee2531353,2024,June,1,mark_scheme,live_exam,Shared across 1A/1B/1C,94c7191fdd9a9c802ab20ccdc05811fe411ffe59152aeb...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted
1,bb13eb25-3502-462e-85fb-ca9f01707d92,2024,June,1B,question_paper,live_exam,Python,62114ae256c530e52a48b65b39183b09496e68f04ff21d...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted
2,5f78bf66-bc88-45f2-966b-b694ebe3adee,2024,June,1B,question_paper,live_exam,Python,d6b2cdb2a4a56f8a072b0da16b3479f10651baac605ff0...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted
3,fe122630-2a00-483b-a577-87b1c9c20910,2024,June,2,question_paper,live_exam,NaN,37d39dcb9064d0d2ccef7005b6cd339b1539712881b908...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted

Current 2024/2025 database records:

,database_id,year,series,paper_code,document_type,programming_language,local_cache_path,source_url
0,4a22fdb4-8d0b-42ca-9f59-bd6ee2531353,2024,June,1,mark_scheme,Shared across 1A/1B/1C,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...
1,bb13eb25-3502-462e-85fb-ca9f01707d92,2024,June,1B,question_paper,Python,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...
2,5f78bf66-bc88-45f2-966b-b694ebe3adee,2024,June,1B,question_paper,Python,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...
3,fe122630-2a00-483b-a577-87b1c9c20910,2024,June,2,question_paper,NaN,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...
4,b365d7ce-a0ab-4096-8c32-4577e1091415,2025,June,1B,question_paper,Python,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/fHDU1dLPgDwvQhfFo...

Remaining-year coverage:

,year,paper_1b_question_paper,paper_1_mark_scheme,paper_2_question_paper,paper_2_mark_scheme
0,2024,✓,✓,✓,✗
1,2025,✓,✗,✗,✗

Saved coverage report: C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_coverage_2024_2025.csv

Get remaining 2025 papers and mark schemes

In [21]:
# ============================================================
# EXACT RECOVERY — AQA 8525 JUNE 2025
#
# Missing target documents:
# 1. Paper 1 shared mark scheme
# 2. Paper 2 question paper
# 3. Paper 2 mark scheme
#
# Windows + Jupyter safe:
# Playwright runs in an external Python process.
# ============================================================

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from textwrap import dedent
from typing import Any

import pandas as pd
from sqlalchemy import select
from sqlalchemy.orm import Session


# ------------------------------------------------------------
# Required existing notebook objects
# ------------------------------------------------------------

required_objects = [
    "AQA_SOURCE_PAGE",
    "OUTPUT_DIR",
    "DiscoveredLink",
    "run_source_ingestion",
    "engine",
    "AssessmentDocument",
]

missing_objects = [
    name
    for name in required_objects
    if name not in globals()
]

if missing_objects:
    raise RuntimeError(
        "Run the previous Notebook 01 cells first. "
        f"Missing objects: {missing_objects}"
    )


OUTPUT_DIR = Path(OUTPUT_DIR).resolve()
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# Exact searches for missing 2025 resources
# ------------------------------------------------------------

SEARCH_TARGETS = [
    {
        "target_key": "2025_paper_1_mark_scheme",
        "expected_paper_code": "1",
        "expected_document_type": "mark_scheme",
        "queries": [
            "AQA-85251-MS-JUN25",
            "8525/1 mark scheme June 2025",
            "Paper 1 mark scheme June 2025 Computer Science",
        ],
    },
    {
        "target_key": "2025_paper_2_question_paper",
        "expected_paper_code": "2",
        "expected_document_type": "question_paper",
        "queries": [
            "AQA-85252-QP-JUN25",
            "8525/2 question paper June 2025",
            "Paper 2 Computing concepts June 2025 question paper",
        ],
    },
    {
        "target_key": "2025_paper_2_mark_scheme",
        "expected_paper_code": "2",
        "expected_document_type": "mark_scheme",
        "queries": [
            "AQA-85252-MS-JUN25",
            "8525/2 mark scheme June 2025",
            "Paper 2 Computing concepts June 2025 mark scheme",
        ],
    },
]


targets_path = (
    OUTPUT_DIR
    / "_aqa_2025_exact_search_targets.json"
)

runner_path = (
    OUTPUT_DIR
    / "_aqa_2025_exact_search_runner.py"
)

results_path = (
    OUTPUT_DIR
    / "_aqa_2025_exact_discovered_links.json"
)


targets_path.write_text(
    json.dumps(
        SEARCH_TARGETS,
        indent=2,
    ),
    encoding="utf-8",
)


# ------------------------------------------------------------
# External Playwright script
# ------------------------------------------------------------

runner_code = dedent(
    r'''
    from __future__ import annotations

    import argparse
    import json
    import re
    from pathlib import Path
    from typing import Any
    from urllib.parse import unquote, urljoin

    from playwright.sync_api import (
        TimeoutError as PlaywrightTimeoutError,
        sync_playwright,
    )


    PDF_PATTERN = re.compile(
        r"(?i)(?:"
        r"\.pdf(?:$|[?#])"
        r"|cdn\.sanity\.io/files/"
        r"|filestore\.aqa\.org\.uk"
        r"|aqa\.org\.uk/files/"
        r")"
    )


    def normalize_url(
        url: str,
        base_url: str,
    ) -> str:
        return urljoin(
            base_url,
            unquote(url.strip()),
        )


    def extract_pdf_urls(
        value: Any,
    ) -> list[str]:
        """
        Recursively search JSON values for PDF/file URLs.
        """

        found: list[str] = []

        if isinstance(value, str):
            if (
                value.lower().startswith(
                    ("http://", "https://")
                )
                and PDF_PATTERN.search(value)
            ):
                found.append(value)

            return found

        if isinstance(value, dict):
            for nested_value in value.values():
                found.extend(
                    extract_pdf_urls(
                        nested_value
                    )
                )

            return found

        if isinstance(value, list):
            for item in value:
                found.extend(
                    extract_pdf_urls(item)
                )

        return found


    def accept_cookies(page) -> None:
        patterns = [
            re.compile(
                r"accept all",
                re.I,
            ),
            re.compile(
                r"accept cookies",
                re.I,
            ),
            re.compile(
                r"allow all",
                re.I,
            ),
            re.compile(
                r"agree",
                re.I,
            ),
        ]

        for pattern in patterns:
            try:
                button = page.get_by_role(
                    "button",
                    name=pattern,
                ).first

                if (
                    button.count()
                    and button.is_visible()
                ):
                    button.click(
                        timeout=3_000
                    )

                    page.wait_for_timeout(
                        500
                    )

                    return

            except Exception:
                continue


    def locate_search_input(page):
        selectors = [
            (
                "input[placeholder*="
                "'Search resources' i]"
            ),
            (
                "input[aria-label*="
                "'Search resources' i]"
            ),
            "input[type='search']",
            "input[name*='search' i]",
            "input[id*='search' i]",
        ]

        for selector in selectors:
            try:
                locator = page.locator(
                    selector
                )

                for index in range(
                    locator.count()
                ):
                    candidate = locator.nth(
                        index
                    )

                    if candidate.is_visible():
                        return candidate

            except Exception:
                continue

        try:
            candidate = page.get_by_role(
                "textbox",
                name=re.compile(
                    r"search resources",
                    re.I,
                ),
            ).first

            if (
                candidate.count()
                and candidate.is_visible()
            ):
                return candidate

        except Exception:
            pass

        return None


    def surrounding_text(anchor) -> str:
        """
        Read the text from the closest resource card.
        """

        try:
            text = anchor.evaluate(
                """
                element => {
                    let current = element;

                    for (
                        let level = 0;
                        level < 8 && current;
                        level += 1
                    ) {
                        const content = (
                            current.innerText || ""
                        ).trim();

                        if (
                            /question paper|mark scheme/i
                            .test(content)
                            && content.length < 3000
                        ) {
                            return content;
                        }

                        current = current.parentElement;
                    }

                    return (
                        element.innerText || ""
                    ).trim();
                }
                """
            )

            return " ".join(
                text.split()
            )

        except Exception:
            try:
                return " ".join(
                    anchor.inner_text().split()
                )
            except Exception:
                return ""


    def collect_dom_links(
        page,
        *,
        source_page: str,
        query: str,
        target_key: str,
    ) -> list[dict]:

        results: list[dict] = []

        anchors = page.locator(
            "a[href]"
        )

        for index in range(
            anchors.count()
        ):
            anchor = anchors.nth(index)

            try:
                href = (
                    anchor.get_attribute(
                        "href"
                    )
                    or ""
                )

                if not href:
                    continue

                absolute_url = normalize_url(
                    href,
                    source_page,
                )

                context = surrounding_text(
                    anchor
                )

                combined = (
                    f"{context} "
                    f"{absolute_url}"
                ).lower()

                is_possible_resource = (
                    PDF_PATTERN.search(
                        absolute_url
                    )
                    or "question paper"
                    in combined
                    or "mark scheme"
                    in combined
                )

                if not is_possible_resource:
                    continue

                # We are recovering June 2025 only.
                year_signal = (
                    "2025" in combined
                    or "jun25" in combined
                    or "june 2025" in combined
                )

                if not year_signal:
                    continue

                results.append(
                    {
                        "url": absolute_url,
                        "title": (
                            f"{query} | {context}"
                        ),
                        "discovered_via": (
                            f"exact_search:{target_key}"
                        ),
                    }
                )

            except Exception:
                continue

        return results


    def run_single_query(
        browser,
        *,
        source_page: str,
        query: str,
        target_key: str,
        show_browser: bool,
    ) -> list[dict]:

        context = browser.new_context(
            viewport={
                "width": 1440,
                "height": 1100,
            },
            user_agent=(
                "Mozilla/5.0 "
                "(Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 "
                "(KHTML, like Gecko) "
                "Chrome/130.0 Safari/537.36"
            ),
        )

        page = context.new_page()

        network_pdf_urls: set[str] = set()

        def capture_response(
            response,
        ) -> None:
            try:
                content_type = (
                    response.headers.get(
                        "content-type"
                    )
                    or ""
                ).lower()

                if (
                    "application/json"
                    not in content_type
                ):
                    return

                payload = response.json()

                for url in extract_pdf_urls(
                    payload
                ):
                    network_pdf_urls.add(
                        normalize_url(
                            url,
                            source_page,
                        )
                    )

            except Exception:
                return

        page.on(
            "response",
            capture_response,
        )

        page.goto(
            source_page,
            wait_until="domcontentloaded",
            timeout=60_000,
        )

        accept_cookies(page)

        try:
            page.wait_for_load_state(
                "networkidle",
                timeout=20_000,
            )
        except PlaywrightTimeoutError:
            pass

        page.wait_for_timeout(
            1_500
        )

        search_input = locate_search_input(
            page
        )

        if search_input is None:
            context.close()

            raise RuntimeError(
                "Could not locate the "
                "Search resources input."
            )

        print(
            f"Searching: {query}",
            flush=True,
        )

        search_input.fill("")

        search_input.fill(
            query
        )

        try:
            search_input.press(
                "Enter"
            )
        except Exception:
            pass

        try:
            page.wait_for_load_state(
                "networkidle",
                timeout=20_000,
            )
        except PlaywrightTimeoutError:
            pass

        # Wait for debounce/API request/rendering.
        page.wait_for_timeout(
            3_500
        )

        page.evaluate(
            "window.scrollTo("
            "0, document.body.scrollHeight"
            ")"
        )

        page.wait_for_timeout(
            1_500
        )

        results = collect_dom_links(
            page,
            source_page=source_page,
            query=query,
            target_key=target_key,
        )

        # The exact query gives context to opaque
        # Sanity URLs found in the JSON response.
        for url in network_pdf_urls:
            results.append(
                {
                    "url": url,
                    "title": query,
                    "discovered_via": (
                        f"exact_network:"
                        f"{target_key}"
                    ),
                }
            )

        print(
            f"  DOM/network candidates: "
            f"{len(results)}",
            flush=True,
        )

        context.close()

        return results


    def main() -> None:
        parser = argparse.ArgumentParser()

        parser.add_argument(
            "--source-page",
            required=True,
        )

        parser.add_argument(
            "--targets-json",
            required=True,
        )

        parser.add_argument(
            "--output-json",
            required=True,
        )

        parser.add_argument(
            "--show-browser",
            action="store_true",
        )

        arguments = parser.parse_args()

        targets = json.loads(
            Path(
                arguments.targets_json
            ).read_text(
                encoding="utf-8"
            )
        )

        all_results: dict[
            str,
            dict
        ] = {}

        with sync_playwright() as playwright:
            browser = (
                playwright.chromium.launch(
                    headless=(
                        not arguments.show_browser
                    )
                )
            )

            for target in targets:
                target_key = target[
                    "target_key"
                ]

                for query in target[
                    "queries"
                ]:
                    query_results = (
                        run_single_query(
                            browser,
                            source_page=(
                                arguments.source_page
                            ),
                            query=query,
                            target_key=target_key,
                            show_browser=(
                                arguments.show_browser
                            ),
                        )
                    )

                    for item in query_results:
                        # Keep one record per URL.
                        existing = (
                            all_results.get(
                                item["url"]
                            )
                        )

                        if existing is None:
                            all_results[
                                item["url"]
                            ] = item

                        elif (
                            item["title"]
                            and not existing.get(
                                "title"
                            )
                        ):
                            all_results[
                                item["url"]
                            ] = item

            browser.close()

        final_results = sorted(
            all_results.values(),
            key=lambda item: (
                item["discovered_via"],
                item["url"],
            ),
        )

        output_path = Path(
            arguments.output_json
        ).resolve()

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        output_path.write_text(
            json.dumps(
                final_results,
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )

        print(
            f"Saved {len(final_results)} "
            f"unique candidate links.",
            flush=True,
        )


    if __name__ == "__main__":
        main()
    '''
)


runner_path.write_text(
    runner_code,
    encoding="utf-8",
)


# ------------------------------------------------------------
# Run exact search in external process
# ------------------------------------------------------------

command = [
    sys.executable,
    str(runner_path),
    "--source-page",
    AQA_SOURCE_PAGE,
    "--targets-json",
    str(targets_path),
    "--output-json",
    str(results_path),
]


print(
    "Starting exact recovery for "
    "the missing June 2025 documents...\n"
)

process = subprocess.run(
    command,
    capture_output=True,
    text=True,
    encoding="utf-8",
    errors="replace",
)


if process.stdout.strip():
    print(
        process.stdout
    )

if process.returncode != 0:
    if process.stderr.strip():
        print(
            process.stderr
        )

    raise RuntimeError(
        "Exact AQA 2025 discovery failed."
    )


# ------------------------------------------------------------
# Load candidates
# ------------------------------------------------------------

if not results_path.exists():
    raise FileNotFoundError(
        "Exact search did not create "
        "the expected results JSON file."
    )


raw_candidates = json.loads(
    results_path.read_text(
        encoding="utf-8"
    )
)


exact_2025_links = [
    DiscoveredLink(**item)
    for item in raw_candidates
]


exact_links_df = pd.DataFrame(
    [
        item.model_dump()
        for item in exact_2025_links
    ]
)


print(
    f"\nUnique 2025 PDF candidates found: "
    f"{len(exact_2025_links)}"
)

if exact_links_df.empty:
    print(
        "No candidates were found."
    )

else:
    display(
        exact_links_df
    )


# ------------------------------------------------------------
# Download and validate every candidate
#
# PyMuPDF classification decides whether the file is:
# - AQA
# - GCSE Computer Science
# - specification 8525
# - June 2025
# - required Paper 1/Paper 2 document
# ------------------------------------------------------------

if exact_2025_links:
    (
        accepted_2025_df,
        issues_2025_df,
        counts_2025,
    ) = run_source_ingestion(
        exact_2025_links,
        include_non_live=False,
        request_delay_seconds=0.35,
    )

    print(
        "\n2025 ingestion summary:"
    )

    print(
        json.dumps(
            counts_2025,
            indent=2,
        )
    )

    if not accepted_2025_df.empty:
        print(
            "\nAccepted 2025 documents:"
        )

        display(
            accepted_2025_df.sort_values(
                [
                    "paper",
                    "document_type",
                ]
            )
        )

    if not issues_2025_df.empty:
        print(
            "\nCandidates that failed "
            "download/classification:"
        )

        display(
            issues_2025_df
        )


# ------------------------------------------------------------
# Read final 2025 records from PostgreSQL
# ------------------------------------------------------------

with Session(engine) as session:
    records_2025 = session.scalars(
        select(
            AssessmentDocument
        ).where(
            AssessmentDocument.exam_board
            == "AQA",

            AssessmentDocument.qualification
            == "GCSE",

            AssessmentDocument.subject
            == "Computer Science",

            AssessmentDocument.specification_code
            == "8525",

            AssessmentDocument.year
            == 2025,

            AssessmentDocument.document_category
            == "live_exam",

            AssessmentDocument.download_status
            == "completed",
        )
    ).all()


manifest_2025_rows: list[
    dict[str, Any]
] = []

for record in records_2025:
    manifest_2025_rows.append(
        {
            "database_id": str(
                record.id
            ),
            "year": record.year,
            "series": record.exam_series,
            "paper_code": (
                record.paper_code
            ),
            "document_type": (
                record.document_type
            ),
            "programming_language": (
                record.programming_language
            ),
            "file_name": (
                record.original_file_name
            ),
            "local_cache_path": (
                record.local_cache_path
            ),
            "source_url": (
                record.source_url
            ),
            "file_hash": (
                record.file_hash
            ),
        }
    )


manifest_2025_df = pd.DataFrame(
    manifest_2025_rows
)


print(
    "\nCurrent June 2025 database manifest:"
)

if manifest_2025_df.empty:
    print(
        "No June 2025 records are registered."
    )

else:
    display(
        manifest_2025_df.sort_values(
            [
                "paper_code",
                "document_type",
            ]
        )
    )


# ------------------------------------------------------------
# Strict 2025 completeness validation
# ------------------------------------------------------------

REQUIRED_2025_RECORDS = [
    {
        "column": (
            "paper_1b_question_paper"
        ),
        "paper_code": "1B",
        "document_type": "question_paper",
    },
    {
        "column": (
            "paper_1_mark_scheme"
        ),
        "paper_code": "1",
        "document_type": "mark_scheme",
    },
    {
        "column": (
            "paper_2_question_paper"
        ),
        "paper_code": "2",
        "document_type": "question_paper",
    },
    {
        "column": (
            "paper_2_mark_scheme"
        ),
        "paper_code": "2",
        "document_type": "mark_scheme",
    },
]


coverage_2025 = {
    "year": 2025
}

missing_2025: list[
    dict[str, str]
] = []


for requirement in REQUIRED_2025_RECORDS:
    if manifest_2025_df.empty:
        present = False

    else:
        matches = manifest_2025_df[
            (
                manifest_2025_df[
                    "paper_code"
                ]
                == requirement[
                    "paper_code"
                ]
            )
            & (
                manifest_2025_df[
                    "document_type"
                ]
                == requirement[
                    "document_type"
                ]
            )
        ]

        present = (
            not matches.empty
        )

    coverage_2025[
        requirement["column"]
    ] = (
        "✓"
        if present
        else "✗"
    )

    if not present:
        missing_2025.append(
            {
                "paper_code": (
                    requirement[
                        "paper_code"
                    ]
                ),
                "document_type": (
                    requirement[
                        "document_type"
                    ]
                ),
                "status": "missing",
            }
        )


coverage_2025_df = pd.DataFrame(
    [coverage_2025]
)

missing_2025_df = pd.DataFrame(
    missing_2025
)


print(
    "\nFinal 2025 coverage:"
)

display(
    coverage_2025_df
)


present_count = (
    4 - len(missing_2025)
)

print(
    f"\n2025 requirements present: "
    f"{present_count}/4"
)


if missing_2025:
    print(
        "\nThe following 2025 documents "
        "are still missing:"
    )

    display(
        missing_2025_df
    )

else:
    print(
        "\nAll required June 2025 "
        "documents are present."
    )


# ------------------------------------------------------------
# Save reports
# ------------------------------------------------------------

manifest_path = (
    OUTPUT_DIR
    / "aqa_8525_manifest_2025.csv"
)

coverage_path = (
    OUTPUT_DIR
    / "aqa_8525_coverage_2025.csv"
)

missing_path = (
    OUTPUT_DIR
    / "aqa_8525_missing_2025.csv"
)


manifest_2025_df.to_csv(
    manifest_path,
    index=False,
)

coverage_2025_df.to_csv(
    coverage_path,
    index=False,
)

missing_2025_df.to_csv(
    missing_path,
    index=False,
)


print(
    "\nSaved reports:"
)

print(
    f"- 2025 manifest: {manifest_path}"
)

print(
    f"- 2025 coverage: {coverage_path}"
)

print(
    f"- Missing list:  {missing_path}"
)

Starting exact recovery for the missing June 2025 documents...

Searching: AQA-85251-MS-JUN25
  DOM/network candidates: 22
Searching: 8525/1 mark scheme June 2025
  DOM/network candidates: 23
Searching: Paper 1 mark scheme June 2025 Computer Science
  DOM/network candidates: 20
Searching: AQA-85252-QP-JUN25
  DOM/network candidates: 30
Searching: 8525/2 question paper June 2025
  DOM/network candidates: 35
Searching: Paper 2 Computing concepts June 2025 question paper
  DOM/network candidates: 32
Searching: AQA-85252-MS-JUN25
  DOM/network candidates: 22
Searching: 8525/2 mark scheme June 2025
  DOM/network candidates: 23
Searching: Paper 2 Computing concepts June 2025 mark scheme
  DOM/network candidates: 24
Saved 58 unique candidate links.


Unique 2025 PDF candidates found: 58

,url,title,discovered_via
0,https://cdn.sanity.io/files/p28bar15/green/08f...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
1,https://cdn.sanity.io/files/p28bar15/green/1a4...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
2,https://cdn.sanity.io/files/p28bar15/green/52f...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
3,https://cdn.sanity.io/files/p28bar15/green/642...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
4,https://cdn.sanity.io/files/p28bar15/green/78f...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
5,https://cdn.sanity.io/files/p28bar15/green/802...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
6,https://cdn.sanity.io/files/p28bar15/green/842...,8525/1 mark scheme June 2025,exact_network:2025_paper_1_mark_scheme
7,https://cdn.sanity.io/files/p28bar15/green/890...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
8,https://cdn.sanity.io/files/p28bar15/green/d0f...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
9,https://cdn.sanity.io/files/p28bar15/green/d1b...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
10,https://cdn.sanity.io/files/p28bar15/green/d1d...,8525/1 mark scheme June 2025,exact_network:2025_paper_1_mark_scheme
11,https://cdn.sanity.io/files/p28bar15/green/db8...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
12,https://cdn.sanity.io/files/p28bar15/green/f17...,AQA-85251-MS-JUN25,exact_network:2025_paper_1_mark_scheme
13,https://cdn.sanity.io/files/p28bar15/green/2b2...,AQA-85252-MS-JUN25,exact_network:2025_paper_2_mark_scheme
14,https://cdn.sanity.io/files/p28bar15/green/65d...,AQA-85252-MS-JUN25,exact_network:2025_paper_2_mark_scheme
15,https://cdn.sanity.io/files/p28bar15/green/0cf...,8525/2 question paper June 2025,exact_network:2025_paper_2_question_paper
16,https://cdn.sanity.io/files/p28bar15/green/0db...,AQA-85252-QP-JUN25,exact_network:2025_paper_2_question_paper
17,https://cdn.sanity.io/files/p28bar15/green/340...,AQA-85252-QP-JUN25,exact_network:2025_paper_2_question_paper
18,https://cdn.sanity.io/files/p28bar15/green/485...,AQA-85252-QP-JUN25,exact_network:2025_paper_2_question_paper
19,https://cdn.sanity.io/files/p28bar15/green/492...,8525/2 question paper June 2025,exact_network:2025_paper_2_question_paper
20,https://cdn.sanity.io/files/p28bar15/green/589...,8525/2 question paper June 2025,exact_network:2025_paper_2_question_paper
21,https://cdn.sanity.io/files/p28bar15/green/6e3...,8525/2 question paper June 2025,exact_network:2025_paper_2_question_paper
22,https://cdn.sanity.io/files/p28bar15/green/6f8...,8525/2 question paper June 2025,exact_network:2025_paper_2_question_paper
23,https://cdn.sanity.io/files/p28bar15/green/8c8...,AQA-85252-QP-JUN25,exact_network:2025_paper_2_question_paper
24,https://cdn.sanity.io/files/p28bar15/green/9c9...,AQA-85252-QP-JUN25,exact_network:2025_paper_2_question_paper
25,https://cdn.sanity.io/files/p28bar15/green/a97...,AQA-85252-QP-JUN25,exact_network:2025_paper_2_question_paper
26,https://cdn.sanity.io/files/p28bar15/green/c64...,8525/2 question paper June 2025,exact_network:2025_paper_2_question_paper
27,https://cdn.sanity.io/files/p28bar15/green/d23...,Paper 2 Computing concepts June 2025 question ...,exact_network:2025_paper_2_question_paper
28,https://cdn.sanity.io/files/p28bar15/green/d41...,8525/2 question paper June 2025,exact_network:2025_paper_2_question_paper
29,https://cdn.sanity.io/files/p28bar15/green/d5a...,8525/2 question paper June 2025,exact_network:2025_paper_2_question_paper
30,https://cdn.sanity.io/files/p28bar15/green/e8e...,AQA-85252-QP-JUN25,exact_network:2025_paper_2_question_paper
31,https://cdn.sanity.io/files/p28bar15/green/fe1...,AQA-85252-QP-JUN25,exact_network:2025_paper_2_question_paper
32,https://www.aqa.org.uk/,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
33,https://www.aqa.org.uk/files/cRIpdimsSKiybuSFv...,8525/1 mark scheme June 2025 | Mark scheme: Pa...,exact_search:2025_paper_1_mark_scheme
34,https://www.aqa.org.uk/files/cRIpdimsSKiybuSFv...,8525/1 mark scheme June 2025 | Mark scheme: Pa...,exact_search:2025_paper_1_mark_scheme
35,https://www.aqa.org.uk/files/sample-papers-and...,AQA-85251-MS-JUN25 | Mark scheme: Paper 1A Com...,exact_search:2025_paper_1_mark_scheme
36,https://www.aqa.org.uk/subjects,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
37,https://www.aqa.org.uk/subjects/computer-science,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
38,https://www.aqa.org.uk/subjects/computer-scien...,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
39,https://www.aqa.org.uk/subjects/computer-scien...,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
40,https://www.aqa.org.uk/subjects/computer-scien...,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
41,https://www.aqa.org.uk/subjects/computer-scien...,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
42,https://www.aqa.org.uk/subjects/computer-scien...,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
43,https://www.aqa.org.uk/subjects/computer-scien...,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
44,https://www.aqa.org.uk/subjects/computer-scien...,AQA-85251-MS-JUN25 | Home Subjects Computer Sc...,exact_search:2025_paper_1_mark_scheme
45,https://www.aqa.org.uk/files/sample-papers-and...,AQA-85252-MS-JUN25 | Mark scheme: Paper 2 Comp...,exact_search:2025_paper_2_mark_scheme
46,https://www.aqa.org.uk/files/2vT3LmcUzNO62qpl9...,8525/2 question paper June 2025 | Question pap...,exact_search:2025_paper_2_question_paper
47,https://www.aqa.org.uk/files/2vT3LmcUzNO62qpl9...,8525/2 question paper June 2025 | Question pap...,exact_search:2025_paper_2_question_paper
48,https://www.aqa.org.uk/files/2vT3LmcUzNO62qpl9...,8525/2 question paper June 2025 | Question pap...,exact_search:2025_paper_2_question_paper
49,https://www.aqa.org.uk/files/2vT3LmcUzNO62qpl9...,8525/2 question paper June 2025 | Question pap...,exact_search:2025_paper_2_question_paper
50,https://www.aqa.org.uk/files/cRIpdimsSKiybuSFv...,Paper 2 Computing concepts June 2025 question ...,exact_search:2025_paper_2_question_paper
51,https://www.aqa.org.uk/files/fHDU1dLPgDwvQhfFo...,8525/2 question paper June 2025 | Question pap...,exact_search:2025_paper_2_question_paper
52,https://www.aqa.org.uk/files/fHDU1dLPgDwvQhfFo...,8525/2 question paper June 2025 | Question pap...,exact_search:2025_paper_2_question_paper
53,https://www.aqa.org.uk/files/fHDU1dLPgDwvQhfFo...,8525/2 question paper June 2025 | Question pap...,exact_search:2025_paper_2_question_paper
54,https://www.aqa.org.uk/files/fHDU1dLPgDwvQhfFo...,8525/2 question paper June 2025 | Question pap...,exact_search:2025_paper_2_question_paper
55,https://www.aqa.org.uk/files/sample-papers-and...,AQA-85252-QP-JUN25 | Question paper ( Modified...,exact_search:2025_paper_2_question_paper
56,https://www.aqa.org.uk/files/sample-papers-and...,AQA-85252-QP-JUN25 | Question paper ( Modified...,exact_search:2025_paper_2_question_paper
57,https://www.aqa.org.uk/files/sample-papers-and...,AQA-85252-QP-JUN25 | Question paper: Paper 2 C...,exact_search:2025_paper_2_question_paper

[1/58] AQA-85251-MS-JUN25
[2/58] AQA-85251-MS-JUN25
[3/58] AQA-85251-MS-JUN25
[4/58] AQA-85251-MS-JUN25
[5/58] AQA-85251-MS-JUN25
[6/58] AQA-85251-MS-JUN25
[7/58] 8525/1 mark scheme June 2025
[8/58] AQA-85251-MS-JUN25
[9/58] AQA-85251-MS-JUN25
[10/58] AQA-85251-MS-JUN25
[11/58] 8525/1 mark scheme June 2025
[12/58] AQA-85251-MS-JUN25
[13/58] AQA-85251-MS-JUN25
[14/58] AQA-85252-MS-JUN25
[15/58] AQA-85252-MS-JUN25
[16/58] 8525/2 question paper June 2025
[17/58] AQA-85252-QP-JUN25
[18/58] AQA-85252-QP-JUN25
[19/58] AQA-85252-QP-JUN25
[20/58] 8525/2 question paper June 2025
[21/58] 8525/2 question paper June 2025
[22/58] 8525/2 question paper June 2025
[23/58] 8525/2 question paper June 2025
[24/58] AQA-85252-QP-JUN25
[25/58] AQA-85252-QP-JUN25
[26/58] AQA-85252-QP-JUN25
[27/58] 8525/2 question paper June 2025
[28/58] Paper 2 Computing concepts June 2025 question paper
[29/58] 8525/2 question paper June 2025
[30/58] 8525/2 question paper June 2025

KeyboardInterrupt:

## 8. Managed PDF download and hashing

In [18]:

REQUEST_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/130.0 Safari/537.36"
    ),
    "Referer": AQA_SOURCE_PAGE,
    "Accept": "application/pdf,*/*;q=0.8",
}


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def safe_filename_from_url(url: str, fallback_hash: str) -> str:
    parsed = urlparse(url)
    raw_name = Path(parsed.path).name
    raw_name = re.sub(r"[^A-Za-z0-9._-]+", "_", raw_name)

    if not raw_name.lower().endswith(".pdf"):
        raw_name = f"aqa_resource_{fallback_hash[:12]}.pdf"

    return raw_name


@dataclass(slots=True)
class DownloadedPDF:
    source_url: str
    discovery_title: str
    original_file_name: str
    temporary_path: Path
    file_hash: str
    content_type: str


def download_pdf(
    link: DiscoveredLink,
    *,
    timeout_seconds: int = 60,
    minimum_pdf_bytes: int = 1_000,
) -> DownloadedPDF:
    url_hash = hashlib.sha256(link.url.encode("utf-8")).hexdigest()
    file_name = safe_filename_from_url(link.url, url_hash)
    temp_path = DOWNLOAD_CACHE / f"_candidate_{url_hash[:12]}_{file_name}"

    response = requests.get(
        link.url,
        headers=REQUEST_HEADERS,
        timeout=timeout_seconds,
        allow_redirects=True,
    )
    response.raise_for_status()

    content_type = (response.headers.get("content-type") or "").lower()
    content = response.content

    if len(content) < minimum_pdf_bytes:
        raise ValueError(f"Downloaded file is unexpectedly small: {len(content)} bytes")

    if not content.startswith(b"%PDF"):
        raise ValueError(
            f"Downloaded content is not a PDF. Content-Type={content_type!r}"
        )

    temp_path.write_bytes(content)
    file_hash = sha256_file(temp_path)

    return DownloadedPDF(
        source_url=link.url,
        discovery_title=link.title,
        original_file_name=file_name,
        temporary_path=temp_path,
        file_hash=file_hash,
        content_type=content_type,
    )


## 9. PDF-level classification with PyMuPDF

Classification uses the document itself, not only its URL. It checks the first pages for:

- AQA GCSE Computer Science;
- specification code `8525`;
- question paper or mark scheme;
- Paper `1B`, shared Paper `1`, or Paper `2`;
- year and exam series;
- live, sample, or specimen assessment category.

Question papers `1A` and `1C`, old specification `8520`, and unrelated documents are rejected.

In [11]:

YEAR_PATTERN = re.compile(r"\b(20\d{2})\b")
SERIES_PATTERNS = {
    "June": re.compile(r"\b(?:JUNE|JUN)\b", re.I),
    "November": re.compile(r"\b(?:NOVEMBER|NOV)\b", re.I),
}


def normalized_pdf_text(path: Path, pages: int = 3) -> str:
    with fitz.open(path) as document:
        extracted = []
        for page_index in range(min(pages, document.page_count)):
            extracted.append(document.load_page(page_index).get_text("text"))

    text = "\n".join(extracted)
    text = text.replace("\u00a0", " ")
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()


def detect_document_category(text_upper: str) -> str:
    if "SPECIMEN ASSESSMENT MATERIAL" in text_upper or "SPECIMEN PAPER" in text_upper:
        return "specimen_assessment"
    if "SAMPLE ASSESSMENT MATERIAL" in text_upper or "SAMPLE PAPER" in text_upper:
        return "sample_assessment"
    return "live_exam"


def detect_year(text_upper: str, title: str, file_name: str) -> int | None:
    combined = f"{text_upper}\n{title.upper()}\n{file_name.upper()}"

    # Prefer full four-digit years.
    years = [int(value) for value in YEAR_PATTERN.findall(combined)]
    plausible = [year for year in years if 2020 <= year <= 2100]
    if plausible:
        return plausible[0]

    # AQA filenames often end in JUN24/NOV23.
    short_match = re.search(r"\b(?:JUN|NOV)(\d{2})\b", combined)
    if short_match:
        return 2000 + int(short_match.group(1))

    return None


def detect_exam_series(text_upper: str, title: str, file_name: str) -> str | None:
    combined = f"{text_upper}\n{title.upper()}\n{file_name.upper()}"
    for series, pattern in SERIES_PATTERNS.items():
        if pattern.search(combined):
            return series
    return None


def detect_document_type(text_upper: str, title: str, file_name: str) -> str | None:
    combined = f"{text_upper}\n{title.upper()}\n{file_name.upper()}"

    if "MARK SCHEME" in combined or re.search(r"(?i)-MS-", combined):
        return "mark_scheme"

    if "QUESTION PAPER" in combined or re.search(r"(?i)-QP-", combined):
        return "question_paper"

    return None


def detect_paper_code(
    text_upper: str,
    title: str,
    file_name: str,
    document_type: str,
) -> tuple[str | None, str | None]:
    combined = re.sub(
        r"\s+",
        "",
        f"{text_upper}\n{title.upper()}\n{file_name.upper()}",
    )

    # Python-specific question paper.
    if re.search(r"8525(?:/1B|B/1|1B)", combined):
        return "1B", "Python"

    # Explicitly reject the other Paper 1 language variants.
    if document_type == "question_paper" and re.search(
        r"8525(?:/1A|A/1|1A|/1C|C/1|1C)",
        combined,
    ):
        return None, None

    # Paper 2.
    if re.search(r"8525(?:/2|2(?:-|\b))", combined):
        return "2", None

    # Shared Paper 1 mark scheme may list A/1, B/1, and C/1 together.
    if document_type == "mark_scheme":
        shared_mark_scheme_signals = (
            "8525A/1" in combined
            or "8525B/1" in combined
            or "8525C/1" in combined
            or "8525/1" in combined
            or re.search(r"AQA-?85251-MS", combined)
        )
        if shared_mark_scheme_signals:
            return "1", "Shared across 1A/1B/1C"

    return None, None


def classify_downloaded_pdf(
    downloaded: DownloadedPDF,
    *,
    include_non_live: bool = False,
) -> ClassifiedAssessmentPDF | None:
    text = normalized_pdf_text(downloaded.temporary_path, pages=3)
    text_upper = text.upper()

    # Strict subject/specification scope.
    if "COMPUTER SCIENCE" not in text_upper:
        return None
    if "8525" not in re.sub(r"\s+", "", text_upper):
        return None
    if "8520" in re.sub(r"\s+", "", text_upper) and "8525" not in re.sub(
        r"\s+", "", text_upper
    ):
        return None

    document_type = detect_document_type(
        text_upper,
        downloaded.discovery_title,
        downloaded.original_file_name,
    )
    if document_type is None:
        return None

    paper_code, programming_language = detect_paper_code(
        text_upper,
        downloaded.discovery_title,
        downloaded.original_file_name,
        document_type,
    )
    if paper_code is None:
        return None

    # A Paper 1 question paper must specifically be the Python 1B variant.
    if document_type == "question_paper" and paper_code == "1":
        return None

    document_category = detect_document_category(text_upper)
    if document_category != "live_exam" and not include_non_live:
        return None

    year = detect_year(
        text_upper,
        downloaded.discovery_title,
        downloaded.original_file_name,
    )
    exam_series = detect_exam_series(
        text_upper,
        downloaded.discovery_title,
        downloaded.original_file_name,
    )

    # Live papers must have enough metadata for deterministic pairing.
    if document_category == "live_exam" and (year is None or exam_series is None):
        raise ValueError(
            "A live assessment document was identified, but year/series could not be parsed."
        )

    canonical_year = str(year) if year is not None else "UNKNOWN"
    canonical_series = (exam_series or "UNKNOWN").upper()
    canonical_name = (
        f"AQA_{SPECIFICATION_CODE}_{canonical_year}_{canonical_series}_"
        f"{paper_code}_{document_type.upper()}.pdf"
    )
    canonical_path = DOWNLOAD_CACHE / canonical_name

    if downloaded.temporary_path != canonical_path:
        if canonical_path.exists():
            existing_hash = sha256_file(canonical_path)
            if existing_hash != downloaded.file_hash:
                canonical_path = DOWNLOAD_CACHE / (
                    f"{canonical_path.stem}_{downloaded.file_hash[:8]}.pdf"
                )
        downloaded.temporary_path.replace(canonical_path)

    return ClassifiedAssessmentPDF(
        source_url=downloaded.source_url,
        discovery_title=downloaded.discovery_title,
        original_file_name=downloaded.original_file_name,
        local_cache_path=str(canonical_path),
        file_hash=downloaded.file_hash,
        year=year,
        exam_series=exam_series,
        paper_code=paper_code,
        document_type=document_type,
        document_category=document_category,
        programming_language=programming_language,
    )

## 10. PostgreSQL registration and idempotency

In [12]:

def existing_document_by_url_or_hash(
    session: Session,
    *,
    source_url: str,
    file_hash: str,
) -> AssessmentDocument | None:
    statement = select(AssessmentDocument).where(
        (AssessmentDocument.source_url == source_url)
        | (AssessmentDocument.file_hash == file_hash)
    )
    return session.scalar(statement)


def upsert_assessment_document(
    session: Session,
    item: ClassifiedAssessmentPDF,
) -> tuple[AssessmentDocument, str]:
    existing = existing_document_by_url_or_hash(
        session,
        source_url=item.source_url,
        file_hash=item.file_hash,
    )

    values = item.model_dump()

    if existing is None:
        record = AssessmentDocument(
            source_page_url=AQA_SOURCE_PAGE,
            source_url=values["source_url"],
            discovery_title=values["discovery_title"] or None,
            original_file_name=values["original_file_name"],
            local_cache_path=values["local_cache_path"],
            file_hash=values["file_hash"],
            exam_board=values["exam_board"],
            qualification=values["qualification"],
            subject=values["subject"],
            specification_code=values["specification_code"],
            year=values["year"],
            exam_series=values["exam_series"],
            paper_code=values["paper_code"],
            document_type=values["document_type"],
            document_category=values["document_category"],
            programming_language=values["programming_language"],
            download_status="completed",
            parsing_status="pending",
            downloaded_at=utc_now(),
        )
        session.add(record)
        session.flush()
        return record, "inserted"

    unchanged = (
        existing.file_hash == values["file_hash"]
        and existing.local_cache_path == values["local_cache_path"]
    )

    existing.source_url = values["source_url"]
    existing.discovery_title = values["discovery_title"] or None
    existing.original_file_name = values["original_file_name"]
    existing.local_cache_path = values["local_cache_path"]
    existing.file_hash = values["file_hash"]
    existing.year = values["year"]
    existing.exam_series = values["exam_series"]
    existing.paper_code = values["paper_code"]
    existing.document_type = values["document_type"]
    existing.document_category = values["document_category"]
    existing.programming_language = values["programming_language"]
    existing.download_status = "completed"
    existing.downloaded_at = utc_now()
    existing.error_message = None
    existing.updated_at = utc_now()

    if not unchanged:
        # A changed source document must be reparsed in later notebooks.
        existing.parsing_status = "pending"

    session.flush()
    return existing, "skipped_unchanged" if unchanged else "updated"


## 11. Batch orchestration

One failed or irrelevant PDF does not stop the remaining batch.

The function returns:

- accepted AQA 8525 assessment documents;
- skipped irrelevant candidates;
- failures requiring review;
- inserted, updated, and unchanged database counts.

In [13]:

def remove_temporary_candidate(path: Path) -> None:
    try:
        if path.exists() and path.name.startswith("_candidate_"):
            path.unlink()
    except OSError:
        pass


def run_source_ingestion(
    links: Iterable[DiscoveredLink],
    *,
    include_non_live: bool = False,
    request_delay_seconds: float = 0.35,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, int]]:
    links = list(links)
    accepted_rows: list[dict[str, Any]] = []
    issue_rows: list[dict[str, Any]] = []

    counts = {
        "candidates": len(links),
        "accepted": 0,
        "irrelevant_or_excluded": 0,
        "download_failed": 0,
        "classification_failed": 0,
        "inserted": 0,
        "updated": 0,
        "skipped_unchanged": 0,
    }

    run_id = uuid.uuid4()

    with Session(engine) as session:
        run = AssessmentIngestionRun(
            id=run_id,
            run_type="source_discovery",
            status="running",
            counts=counts.copy(),
        )
        session.add(run)
        session.commit()

    try:
        for position, link in enumerate(links, start=1):
            downloaded: DownloadedPDF | None = None
            print(f"[{position}/{len(links)}] {link.title or link.url}")

            try:
                downloaded = download_pdf(link)
            except Exception as exc:
                counts["download_failed"] += 1
                issue_rows.append(
                    {
                        "source_url": link.url,
                        "title": link.title,
                        "stage": "download",
                        "error": str(exc),
                    }
                )
                continue

            try:
                classified = classify_downloaded_pdf(
                    downloaded,
                    include_non_live=include_non_live,
                )
            except Exception as exc:
                counts["classification_failed"] += 1
                issue_rows.append(
                    {
                        "source_url": link.url,
                        "title": link.title,
                        "stage": "classification",
                        "error": str(exc),
                    }
                )
                remove_temporary_candidate(downloaded.temporary_path)
                continue

            if classified is None:
                counts["irrelevant_or_excluded"] += 1
                remove_temporary_candidate(downloaded.temporary_path)
                continue

            with Session(engine) as session:
                record, action = upsert_assessment_document(session, classified)
                session.commit()

                counts[action] += 1
                counts["accepted"] += 1

                accepted_rows.append(
                    {
                        "database_id": str(record.id),
                        "year": classified.year,
                        "series": classified.exam_series,
                        "paper": classified.paper_code,
                        "document_type": classified.document_type,
                        "category": classified.document_category,
                        "programming_language": classified.programming_language,
                        "file_hash": classified.file_hash,
                        "local_cache_path": classified.local_cache_path,
                        "source_url": classified.source_url,
                        "database_action": action,
                    }
                )

            if request_delay_seconds > 0:
                time.sleep(request_delay_seconds)

        with Session(engine) as session:
            run = session.get(AssessmentIngestionRun, run_id)
            if run is not None:
                run.status = "completed"
                run.completed_at = utc_now()
                run.counts = counts.copy()
                session.commit()

    except Exception as exc:
        with Session(engine) as session:
            run = session.get(AssessmentIngestionRun, run_id)
            if run is not None:
                run.status = "failed"
                run.completed_at = utc_now()
                run.counts = counts.copy()
                run.error_message = str(exc)
                session.commit()
        raise

    accepted_df = pd.DataFrame(accepted_rows)
    issues_df = pd.DataFrame(issue_rows)

    return accepted_df, issues_df, counts


## 12. Run the ingestion

`include_non_live=False` keeps the first implementation limited to live examination papers. We can enable specimen/sample papers later as a separately labelled dataset.

In [14]:

accepted_df, issues_df, ingestion_counts = run_source_ingestion(
    candidate_links,
    include_non_live=False,
)

print(json.dumps(ingestion_counts, indent=2))

if not accepted_df.empty:
    display(
        accepted_df.sort_values(
            ["year", "paper", "document_type"],
            ascending=[False, True, True],
        )
    )
else:
    print("No supported live AQA 8525 documents were accepted.")

if not issues_df.empty:
    display(issues_df)

[1/8] Mark scheme: Paper 1 Computational thinking and programming skills - Sample set 1 - Computer Science GCSE Computer Science • PDF • 480.36 KB • Published: 13 Dec 2019
[2/8] Question paper: Paper 1A Computational thinking and programming skills (C#) - Sample set 1 - Computer Science GCSE Computer Science • PDF • 628.49 KB • Published: 13 Dec 2019
[3/8] Question paper: Paper 2 Computing concepts - Sample set 1 (last exam 2026) - Computer Science GCSE Computer Science • PDF • 439.1 KB • Published: 13 Dec 2019
[4/8] Question paper: Paper 1B Computational thinking and programming skills (Python) - June 2022 - Computer Science GCSE Computer Science • PDF • 1.14 MB • Published: 14 Jul 2023
[5/8] Mark scheme: Paper 1 Computational thinking and programming skills - June 2023 - Computer Science GCSE Computer Science • PDF • 454.43 KB • Published: 07 Dec 2024
[6/8] Question paper: Paper 1B Computational thinking and programming skills (Python) - June 2023 - Computer Science GCSE Computer Science • PDF • 740.91 KB • Published: 07 Dec 2024
[7/8] Mark scheme: Paper 2 Computing concepts - June 2023 - Computer Science GCSE Computer Science • PDF • 362.56 KB • Published: 07 Dec 2024
[8/8] Question paper: Paper 2 Computing concepts - June 2023 - Computer Science GCSE Computer Science • PDF • 571.14 KB • Published: 07 Dec 2024
{
  "candidates": 8,
  "accepted": 5,
  "irrelevant_or_excluded": 3,
  "download_failed": 0,
  "classification_failed": 0,
  "inserted": 5,
  "updated": 0,
  "skipped_unchanged": 0
}

,database_id,year,series,paper,document_type,category,programming_language,file_hash,local_cache_path,source_url,database_action
1,5b99ed2b-a3ba-4d16-8e85-baf965b4cfbe,2023,June,1B,mark_scheme,live_exam,Python,04ef1087412b9376884cf60ab11bea1c23a7adecb9fb57...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted
2,9040b67e-56ad-4f90-b98a-8e01ca7c2ba9,2023,June,1B,question_paper,live_exam,Python,6767013c28067e540ea3942d231b2b048539a888658135...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted
3,1a21a37c-b64a-44af-9caa-2b4ec5b6f039,2023,June,2,mark_scheme,live_exam,NaN,f32360582e4f42933eabd545fd13e080fbf56ee6aa7e12...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted
4,4bd83e85-0a5d-4ee2-af33-a4640f4bc830,2023,June,2,question_paper,live_exam,NaN,8433047a46c08d03325fcb0a580ba9b744386f7d7b8dbd...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted
0,65ab6d7b-67a7-4ffe-b163-0d50cbd037f8,2022,June,1B,question_paper,live_exam,Python,b8c53317b668a6cfa7cf51b520246a81b6939dbf7d7f45...,C:\Users\hp\EDTECH\Agent2\cache\assessment_pdf...,https://www.aqa.org.uk/files/sample-papers-and...,inserted

## 13. Save human-readable manifests

In [15]:

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

accepted_path = OUTPUT_DIR / f"aqa_8525_document_manifest_{timestamp}.csv"
issues_path = OUTPUT_DIR / f"aqa_8525_discovery_issues_{timestamp}.csv"
summary_path = OUTPUT_DIR / f"aqa_8525_discovery_summary_{timestamp}.json"

accepted_df.to_csv(accepted_path, index=False)
issues_df.to_csv(issues_path, index=False)
summary_path.write_text(
    json.dumps(ingestion_counts, indent=2),
    encoding="utf-8",
)

print(f"Manifest: {accepted_path}")
print(f"Issues:   {issues_path}")
print(f"Summary:  {summary_path}")

Manifest: C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_document_manifest_20260803_154828.csv
Issues:   C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_discovery_issues_20260803_154828.csv
Summary:  C:\Users\hp\EDTECH\Agent2\OUTPUT\aqa_8525_discovery_summary_20260803_154828.json


## 14. Knowledge-base smoke checks

These checks do not prove question-level parsing yet. They verify that the document manifest is safe to use as the input to Notebook 02.

In [16]:

def run_document_manifest_checks(dataframe: pd.DataFrame) -> dict[str, bool]:
    if dataframe.empty:
        return {
            "has_documents": False,
            "only_supported_papers": False,
            "only_supported_document_types": False,
            "unique_source_urls": False,
            "unique_database_ids": False,
            "cache_files_exist": False,
            "hashes_present": False,
        }

    checks = {
        "has_documents": len(dataframe) > 0,
        "only_supported_papers": set(dataframe["paper"]).issubset({"1B", "1", "2"}),
        "only_supported_document_types": set(dataframe["document_type"]).issubset(
            {"question_paper", "mark_scheme"}
        ),
        "unique_source_urls": dataframe["source_url"].is_unique,
        "unique_database_ids": dataframe["database_id"].is_unique,
        "cache_files_exist": dataframe["local_cache_path"].map(
            lambda value: Path(value).exists()
        ).all(),
        "hashes_present": dataframe["file_hash"].str.fullmatch(r"[0-9a-f]{64}").all(),
    }
    return {key: bool(value) for key, value in checks.items()}


manifest_checks = run_document_manifest_checks(accepted_df)
display(pd.DataFrame(
    [{"check": key, "passed": value} for key, value in manifest_checks.items()]
))

failed_checks = [key for key, passed in manifest_checks.items() if not passed]
if failed_checks:
    print("Checks needing attention:", failed_checks)
else:
    print("All document-manifest checks passed.")

                           check  passed
0                  has_documents    True
1          only_supported_papers    True
2  only_supported_document_types    True
3             unique_source_urls    True
4            unique_database_ids    True
5              cache_files_exist    True
6                 hashes_present    True

All document-manifest checks passed.


## Output of Notebook 01

After a successful run:

### PostgreSQL

- `assessment_documents`
- `assessment_ingestion_runs`

### Local cache

```text
cache/assessment_pdfs/
├── AQA_8525_2024_JUNE_1B_QUESTION_PAPER.pdf
├── AQA_8525_2024_JUNE_1_MARK_SCHEME.pdf
├── AQA_8525_2024_JUNE_2_QUESTION_PAPER.pdf
└── AQA_8525_2024_JUNE_2_MARK_SCHEME.pdf
```

### Human-readable reports

```text
OUTPUT/
├── aqa_8525_document_manifest_<timestamp>.csv
├── aqa_8525_discovery_issues_<timestamp>.csv
└── aqa_8525_discovery_summary_<timestamp>.json
```

## Next implementation notebook

`02_question_paper_parsing.ipynb` will read only `assessment_documents` rows where:

```text
document_type = question_paper
parsing_status = pending
```

It will then split each paper into question-level records and create stable `QuestionID` values.