# Agent 2 — AQA GCSE Computer Science Topical Assessment Knowledge Base

## Notebook 01: PMT topical source discovery, download, pairing, and PostgreSQL registration

This notebook replaces the **official full-paper discovery stage** for the new Agent 2 approach.

It uses the public AQA GCSE Computer Science topical pages on Physics & Maths Tutor (PMT) to:

- discover all eight main topic pages;
- discover subtopic-wise Question Paper (`QP`) and Mark Scheme (`MS`) PDFs;
- keep **Python / Paper 1B** resources for programming-language topics;
- download every topical PDF into a managed local cache;
- generate one deterministic `pair_key` for each QP/MS pair;
- register topic metadata and document metadata in PostgreSQL;
- detect explicit `8520` and `8525` markers inside downloaded PDFs;
- preserve an audit manifest for later question-level parsing.

### Frozen project scope

- **Exam board:** AQA
- **Qualification:** GCSE
- **Subject:** Computer Science
- **Current target specification:** 8525
- **Programming language:** Python / Paper 1B
- **Primary source structure:** PMT Questions by Topic
- **Database:** PostgreSQL
- **Original PDFs:** local managed cache
- **Embeddings:** Qdrant in a later notebook

This notebook does **not** parse individual questions yet. It creates a reliable, topic-labelled document layer for the next notebook.

## Important decision about 2018–2024 packs

PMT publishes these resources as combined **2018–2024 topical packs**. Therefore, the notebook cannot choose only 2022–2024 before downloading because the year range is bundled inside each topical PDF.

The production policy used here is:

```text
Download the complete topical QP/MS pack
        ↓
Record the known PMT topic and subtopic
        ↓
Detect explicit 8520 / 8525 markers
        ↓
Later question-level parser:
    - 8525 question → eligible by default
    - 8520 question → legacy, disabled by default
    - uncertain source → review flag
```

Configuration stored by this notebook:

```text
target_specification_code = 8525
legacy_8520_retrieval_enabled = False
requires_question_level_spec_filter = True
```

This avoids incorrectly presenting an old-specification question as a current 8525 question while still preserving the complete topical source pack for controlled processing.

> Use these downloads only where your organisation has the appropriate permission. This notebook follows public PDF links, uses rate limiting, and does not bypass authentication or access controls.

## Pipeline implemented here

```text
PMT AQA GCSE Computer Science landing page
        ↓
Discover Topic 1 to Topic 8 pages
        ↓
Read each topic page
        ↓
Discover subtopic-wise QP and MS links
        ↓
Topic 1 and Topic 2:
    keep Python / 1B only
        ↓
Validate complete QP ↔ MS pairs
        ↓
Download PDFs with retries and rate limiting
        ↓
Validate PDF signature and page count with PyMuPDF
        ↓
Detect explicit 8520 / 8525 markers
        ↓
Register:
    assessment_topical_topics
    assessment_topical_documents
    assessment_topical_ingestion_runs
        ↓
Write CSV and JSON manifests
```

## 1. Install dependencies

Run this cell once in the active Agent 2 Jupyter kernel.

In [1]:
%pip install -q \
    requests \
    beautifulsoup4 \
    pymupdf \
    pandas \
    pydantic \
    python-dotenv \
    "sqlalchemy>=2.0" \
    "psycopg[binary]>=3.1"

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## 2. Imports and project configuration

The notebook supports either of these project layouts:

```text
Agent2/
├── Notebooks/
├── cache/
├── OUTPUT/
└── .env
```

or:

```text
Agent_2/
├── notebooks/
├── cache/
├── OUTPUT/
└── .env
```

In [2]:
from __future__ import annotations

import hashlib
import json
import os
import re
import time
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import unquote, urljoin, urlparse

import fitz  # PyMuPDF
import pandas as pd
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from pydantic import BaseModel, ConfigDict, field_validator
from requests.adapters import HTTPAdapter
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    create_engine,
    select,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column
from urllib3.util.retry import Retry


PMT_LANDING_PAGE = (
    "https://www.physicsandmathstutor.com/"
    "computer-science-revision/gcse-aqa/"
)

EXAM_BOARD = "AQA"
QUALIFICATION = "GCSE"
SUBJECT = "Computer Science"
TARGET_SPECIFICATION_CODE = "8525"
SOURCE_PROVIDER = "PMT"
SELECTED_PROGRAMMING_LANGUAGE = "Python"

# PMT labels the available topical packs as 2018-2024.
DEFAULT_SOURCE_COVERAGE = "2018-2024"

# Legacy questions may exist inside the combined packs.
LEGACY_8520_RETRIEVAL_ENABLED = False
REQUIRES_QUESTION_LEVEL_SPEC_FILTER = True

# Safe operational settings.
REQUEST_TIMEOUT_SECONDS = 60
REQUEST_DELAY_SECONDS = 0.60
FORCE_REDOWNLOAD = False
WRITE_TO_POSTGRES = True

# Current PMT page structure: 35 topical pairs = 70 PDFs after
# selecting Python only for Topics 1 and 2.
EXPECTED_MAIN_TOPICS = 8
EXPECTED_TOPIC_PAIRS = 35
EXPECTED_DOCUMENTS = 70

cwd = Path.cwd().resolve()
if cwd.name.lower() in {"notebooks", "notebook"}:
    PROJECT_ROOT = cwd.parent
else:
    PROJECT_ROOT = cwd

CACHE_ROOT = PROJECT_ROOT / "cache"
DOWNLOAD_CACHE = CACHE_ROOT / "pmt_topical_pdfs"
OUTPUT_DIR = PROJECT_ROOT / "OUTPUT"

for folder in (CACHE_ROOT, DOWNLOAD_CACHE, OUTPUT_DIR):
    folder.mkdir(parents=True, exist_ok=True)

load_dotenv(PROJECT_ROOT / ".env")
DATABASE_URL = os.getenv("AGENT2_DATABASE_URL", "").strip()

print(f"Project root:       {PROJECT_ROOT}")
print(f"PMT PDF cache:      {DOWNLOAD_CACHE}")
print(f"Output directory:   {OUTPUT_DIR}")
print(f"PostgreSQL enabled: {WRITE_TO_POSTGRES}")
print(f"DB configured:      {bool(DATABASE_URL)}")
print(f"Selected language:  {SELECTED_PROGRAMMING_LANGUAGE}")
print(f"Legacy 8520 active: {LEGACY_8520_RETRIEVAL_ENABLED}")

Project root:       C:\Users\hp\EDTECH\Agent2
PMT PDF cache:      C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pdfs
Output directory:   C:\Users\hp\EDTECH\Agent2\OUTPUT
PostgreSQL enabled: True
DB configured:      True
Selected language:  Python
Legacy 8520 active: False

## 3. PostgreSQL environment variable

Add the following to `Agent2/.env` or `Agent_2/.env`:

```env
AGENT2_DATABASE_URL=postgresql+psycopg://postgres:YOUR_PASSWORD@localhost:5432/edtech
```

Set `WRITE_TO_POSTGRES = False` in the configuration cell when you only want to test discovery and downloading without database writes.

In [3]:
if WRITE_TO_POSTGRES and not DATABASE_URL:
    raise RuntimeError(
        "AGENT2_DATABASE_URL is missing. Add it to the Agent 2 .env file, "
        "restart the kernel, and rerun the configuration cell. "
        "For a download-only dry run, set WRITE_TO_POSTGRES = False."
    )

## 4. PostgreSQL schema

The topical pipeline uses separate tables so it does not conflict with the earlier full-paper pipeline.

### `assessment_topical_topics`

One row per PMT subtopic and selected programming language.

### `assessment_topical_documents`

One row per topical QP or MS PDF.

QP and MS are connected through the same deterministic `pair_key`.

### `assessment_topical_ingestion_runs`

Stores run-level status and counts.

In [4]:
class Base(DeclarativeBase):
    pass


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class AssessmentTopicalTopic(Base):
    __tablename__ = "assessment_topical_topics"
    __table_args__ = (
        UniqueConstraint(
            "topic_key",
            name="uq_assessment_topical_topics_topic_key",
        ),
        CheckConstraint(
            "paper_code IN ('1', '2')",
            name="ck_assessment_topical_topics_paper_code",
        ),
        Index(
            "ix_assessment_topical_topics_lookup",
            "exam_board",
            "qualification",
            "subject",
            "pmt_topic_number",
            "pmt_subtopic_code",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    topic_key: Mapped[str] = mapped_column(String(180), nullable=False)
    source_provider: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default=SOURCE_PROVIDER,
    )
    source_topic_page_url: Mapped[str] = mapped_column(Text, nullable=False)

    exam_board: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default=EXAM_BOARD,
    )
    qualification: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=QUALIFICATION,
    )
    subject: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default=SUBJECT,
    )
    target_specification_code: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=TARGET_SPECIFICATION_CODE,
    )

    pmt_topic_number: Mapped[int] = mapped_column(Integer, nullable=False)
    pmt_topic_name: Mapped[str] = mapped_column(Text, nullable=False)
    pmt_subtopic_code: Mapped[str] = mapped_column(String(30), nullable=False)
    pmt_subtopic_name: Mapped[str] = mapped_column(Text, nullable=False)

    paper_code: Mapped[str] = mapped_column(String(10), nullable=False)
    programming_language: Mapped[str | None] = mapped_column(String(50))
    source_coverage: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default=DEFAULT_SOURCE_COVERAGE,
    )

    legacy_8520_retrieval_enabled: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )
    requires_question_level_spec_filter: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )


class AssessmentTopicalDocument(Base):
    __tablename__ = "assessment_topical_documents"
    __table_args__ = (
        UniqueConstraint(
            "source_url",
            name="uq_assessment_topical_documents_source_url",
        ),
        UniqueConstraint(
            "pair_key",
            "document_type",
            name="uq_assessment_topical_documents_pair_type",
        ),
        CheckConstraint(
            "document_type IN ('question_paper', 'mark_scheme')",
            name="ck_assessment_topical_documents_document_type",
        ),
        Index(
            "ix_assessment_topical_documents_pair",
            "pair_key",
            "document_type",
        ),
        Index(
            "ix_assessment_topical_documents_status",
            "download_status",
            "parsing_status",
        ),
        Index(
            "ix_assessment_topical_documents_hash",
            "file_hash",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    topic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey(
            "assessment_topical_topics.id",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    pair_key: Mapped[str] = mapped_column(String(180), nullable=False)
    source_provider: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default=SOURCE_PROVIDER,
    )
    source_page_url: Mapped[str] = mapped_column(Text, nullable=False)
    source_url: Mapped[str] = mapped_column(Text, nullable=False)
    discovery_title: Mapped[str] = mapped_column(Text, nullable=False)

    document_type: Mapped[str] = mapped_column(String(30), nullable=False)
    programming_language: Mapped[str | None] = mapped_column(String(50))
    source_coverage: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default=DEFAULT_SOURCE_COVERAGE,
    )

    original_file_name: Mapped[str | None] = mapped_column(Text)
    local_cache_path: Mapped[str | None] = mapped_column(Text)
    file_hash: Mapped[str | None] = mapped_column(String(64))
    file_size_bytes: Mapped[int | None] = mapped_column(Integer)
    page_count: Mapped[int | None] = mapped_column(Integer)

    contains_8520_marker: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )
    contains_8525_marker: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )
    specification_scope: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="not_inspected",
    )

    download_status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="discovered",
    )
    parsing_status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="pending",
    )
    error_message: Mapped[str | None] = mapped_column(Text)

    discovered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )
    downloaded_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True)
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )


class AssessmentTopicalIngestionRun(Base):
    __tablename__ = "assessment_topical_ingestion_runs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    run_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="pmt_topical_discovery",
    )
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="running",
    )
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True)
    )
    counts: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
    )
    error_message: Mapped[str | None] = mapped_column(Text)


engine = None

if WRITE_TO_POSTGRES:
    engine = create_engine(
        DATABASE_URL,
        pool_pre_ping=True,
        future=True,
    )
    Base.metadata.create_all(engine)

    with engine.connect() as connection:
        connection.exec_driver_sql("SELECT 1")

    print("PostgreSQL connection successful.")
    print("Created/verified tables:")
    print("- assessment_topical_topics")
    print("- assessment_topical_documents")
    print("- assessment_topical_ingestion_runs")
else:
    print("PostgreSQL writes are disabled for this run.")

PostgreSQL connection successful.
Created/verified tables:
- assessment_topical_topics
- assessment_topical_documents
- assessment_topical_ingestion_runs

## 5. Validated discovery models

In [5]:
class TopicPageLink(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    topic_number: int
    topic_name: str
    url: str

    @field_validator("url")
    @classmethod
    def validate_http_url(cls, value: str) -> str:
        if not value.lower().startswith(("http://", "https://")):
            raise ValueError("Only HTTP(S) URLs are accepted.")
        return value


class TopicalDocumentCandidate(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    topic_number: int
    topic_name: str
    subtopic_code: str
    subtopic_name: str
    paper_code: str
    programming_language: str | None = None
    source_coverage: str = DEFAULT_SOURCE_COVERAGE

    topic_key: str
    pair_key: str
    document_type: str

    source_page_url: str
    source_url: str
    discovery_title: str

    @field_validator("document_type")
    @classmethod
    def validate_document_type(cls, value: str) -> str:
        allowed = {"question_paper", "mark_scheme"}
        if value not in allowed:
            raise ValueError(f"document_type must be one of {allowed}")
        return value

    @field_validator("paper_code")
    @classmethod
    def validate_paper_code(cls, value: str) -> str:
        if value not in {"1", "2"}:
            raise ValueError("paper_code must be '1' or '2'")
        return value


class DownloadedTopicalPDF(BaseModel):
    candidate: TopicalDocumentCandidate
    original_file_name: str
    local_cache_path: str
    file_hash: str
    file_size_bytes: int
    page_count: int
    contains_8520_marker: bool
    contains_8525_marker: bool
    specification_scope: str
    reused_existing_file: bool = False

## 6. HTTP session, retries, and text helpers

Requests are made sequentially with a delay between PDF downloads. No parallel downloader is used.

In [6]:
REQUEST_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/130.0 Safari/537.36"
    ),
    "Accept": (
        "text/html,application/xhtml+xml,application/pdf,"
        "*/*;q=0.8"
    ),
}


def build_http_session() -> requests.Session:
    retry = Retry(
        total=4,
        connect=4,
        read=4,
        backoff_factor=1.0,
        status_forcelist=(429, 500, 502, 503, 504),
        allowed_methods=frozenset({"GET", "HEAD"}),
        raise_on_status=False,
    )

    adapter = HTTPAdapter(
        max_retries=retry,
        pool_connections=4,
        pool_maxsize=4,
    )

    session = requests.Session()
    session.headers.update(REQUEST_HEADERS)
    session.mount("https://", adapter)
    session.mount("http://", adapter)
    return session


http_session = build_http_session()


def normalise_whitespace(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()


def safe_slug(value: str, max_length: int = 90) -> str:
    value = unquote(value)
    value = value.replace("&", " and ")
    value = re.sub(r"[^A-Za-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_").lower()
    return (value[:max_length] or "item").strip("_")


def get_soup(url: str) -> BeautifulSoup:
    response = http_session.get(
        url,
        timeout=REQUEST_TIMEOUT_SECONDS,
    )
    response.raise_for_status()

    content_type = (
        response.headers.get("content-type") or ""
    ).lower()
    if "html" not in content_type and "<html" not in response.text[:500].lower():
        raise ValueError(
            f"Expected HTML from {url}, got Content-Type={content_type!r}"
        )

    return BeautifulSoup(response.text, "html.parser")

## 7. Discover the eight PMT topic pages

In [7]:
TOPIC_HEADER_PATTERN = re.compile(
    r"^\s*Topic\s*(\d+)\s*[:\-–]\s*(.+?)\s*$",
    re.IGNORECASE,
)


def discover_topic_pages(
    landing_page_url: str = PMT_LANDING_PAGE,
) -> list[TopicPageLink]:
    soup = get_soup(landing_page_url)
    discovered: dict[int, TopicPageLink] = {}

    for anchor in soup.select("a[href]"):
        title = normalise_whitespace(
            anchor.get_text(" ", strip=True)
        )
        match = TOPIC_HEADER_PATTERN.match(title)
        if not match:
            continue

        topic_number = int(match.group(1))
        topic_name = normalise_whitespace(match.group(2))
        absolute_url = urljoin(
            landing_page_url,
            anchor.get("href", ""),
        )

        parsed = urlparse(absolute_url)
        if parsed.netloc.lower() != "www.physicsandmathstutor.com":
            continue
        if (
            "/computer-science-revision/gcse-aqa/"
            not in parsed.path.lower()
        ):
            continue

        discovered[topic_number] = TopicPageLink(
            topic_number=topic_number,
            topic_name=topic_name,
            url=absolute_url,
        )

    topic_pages = [
        discovered[number]
        for number in sorted(discovered)
    ]

    if not topic_pages:
        raise RuntimeError(
            "No PMT topic pages were discovered. "
            "The website structure may have changed."
        )

    return topic_pages


topic_pages = discover_topic_pages()
topic_pages_df = pd.DataFrame(
    [item.model_dump() for item in topic_pages]
)
display(topic_pages_df)

print(f"Discovered topic pages: {len(topic_pages)}")

,topic_number,topic_name,url
0,1,Fundamentals of Algorithms,https://www.physicsandmathstutor.com/computer-...
1,2,Programming,https://www.physicsandmathstutor.com/computer-...
2,3,Fundamentals of Data Representation,https://www.physicsandmathstutor.com/computer-...
3,4,Computer Systems,https://www.physicsandmathstutor.com/computer-...
4,5,Fundamentals of Computer Networks,https://www.physicsandmathstutor.com/computer-...
5,6,Cyber Security,https://www.physicsandmathstutor.com/computer-...
6,7,Relational Databases and Structured Query Lang...,https://www.physicsandmathstutor.com/computer-...
7,8,"Ethical, Legal and Environmental Impacts of Di...",https://www.physicsandmathstutor.com/computer-...

Discovered topic pages: 8

## 8. Discover subtopic-wise QP and MS PDFs

For Topic 1 and Topic 2, PMT exposes C#, Python, and VB.Net variants. The URL path contains:

```text
/1A/ → C#
/1B/ → Python
/1C/ → VB.Net
```

This notebook keeps only `/1B/` for those two topics.

Theory topics do not have a programming-language variant.

In [8]:
TOPICAL_PDF_TITLE_PATTERN = re.compile(
    r"^\s*(\d+(?:\.\d+)?)\s+(.+?)\s+(QP|MS)\s*$",
    re.IGNORECASE,
)

PMT_TOPICAL_DOWNLOAD_PATH = (
    "/download/computer-science/gcse/topic-qs/aqa/"
)


def infer_programming_language(url: str) -> str | None:
    path = unquote(urlparse(url).path).replace("\\", "/")
    upper_path = path.upper()

    if "/1A/" in upper_path:
        return "C#"
    if "/1B/" in upper_path:
        return "Python"
    if "/1C/" in upper_path:
        return "VB.Net"
    return None


def parse_topic_page_header(
    soup: BeautifulSoup,
    fallback: TopicPageLink,
) -> tuple[int, str]:
    header = soup.find("h1")
    header_text = normalise_whitespace(
        header.get_text(" ", strip=True) if header else ""
    )
    match = TOPIC_HEADER_PATTERN.match(header_text)

    if not match:
        return fallback.topic_number, fallback.topic_name

    return (
        int(match.group(1)),
        normalise_whitespace(match.group(2)),
    )


def infer_paper_code(
    soup: BeautifulSoup,
    topic_number: int,
) -> str:
    page_text = normalise_whitespace(
        soup.get_text(" ", strip=True)
    )
    match = re.search(
        r"included\s+in\s+Paper\s+([12])",
        page_text,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(1)

    # Stable AQA split used as a guarded fallback.
    return "1" if topic_number in {1, 2} else "2"


def infer_source_coverage(soup: BeautifulSoup) -> str:
    page_text = normalise_whitespace(
        soup.get_text(" ", strip=True)
    )
    match = re.search(
        r"\b(20\d{2}\s*-\s*20\d{2})\s+papers\b",
        page_text,
        flags=re.IGNORECASE,
    )
    if not match:
        return DEFAULT_SOURCE_COVERAGE

    return re.sub(r"\s+", "", match.group(1))


def build_topic_key(
    topic_number: int,
    subtopic_code: str,
    programming_language: str | None,
) -> str:
    language_part = (
        safe_slug(programming_language).upper()
        if programming_language
        else "THEORY"
    )
    code_part = safe_slug(subtopic_code).upper()
    return (
        f"AQA_GCSE_CS_PMT_T{topic_number}_"
        f"{code_part}_{language_part}"
    )


def build_pair_key(
    topic_number: int,
    subtopic_code: str,
    programming_language: str | None,
) -> str:
    return build_topic_key(
        topic_number,
        subtopic_code,
        programming_language,
    )


def discover_documents_from_topic_page(
    topic_page: TopicPageLink,
) -> list[TopicalDocumentCandidate]:
    soup = get_soup(topic_page.url)
    topic_number, topic_name = parse_topic_page_header(
        soup,
        topic_page,
    )
    paper_code = infer_paper_code(soup, topic_number)
    source_coverage = infer_source_coverage(soup)

    candidates: list[TopicalDocumentCandidate] = []

    for anchor in soup.select("a[href]"):
        title = normalise_whitespace(
            anchor.get_text(" ", strip=True)
        )
        title_match = TOPICAL_PDF_TITLE_PATTERN.match(title)
        if not title_match:
            continue

        absolute_url = urljoin(
            topic_page.url,
            anchor.get("href", ""),
        )
        parsed = urlparse(absolute_url)

        if (
            PMT_TOPICAL_DOWNLOAD_PATH
            not in parsed.path.lower()
        ):
            continue

        subtopic_code = title_match.group(1)
        subtopic_name = normalise_whitespace(
            title_match.group(2)
        )
        short_type = title_match.group(3).upper()
        document_type = (
            "question_paper"
            if short_type == "QP"
            else "mark_scheme"
        )

        programming_language = infer_programming_language(
            absolute_url
        )

        if topic_number in {1, 2}:
            if (
                programming_language
                != SELECTED_PROGRAMMING_LANGUAGE
            ):
                continue
        else:
            # Theory topics should not be language-specific.
            programming_language = None

        topic_key = build_topic_key(
            topic_number,
            subtopic_code,
            programming_language,
        )
        pair_key = build_pair_key(
            topic_number,
            subtopic_code,
            programming_language,
        )

        candidates.append(
            TopicalDocumentCandidate(
                topic_number=topic_number,
                topic_name=topic_name,
                subtopic_code=subtopic_code,
                subtopic_name=subtopic_name,
                paper_code=paper_code,
                programming_language=programming_language,
                source_coverage=source_coverage,
                topic_key=topic_key,
                pair_key=pair_key,
                document_type=document_type,
                source_page_url=topic_page.url,
                source_url=absolute_url,
                discovery_title=title,
            )
        )

    # Deduplicate repeated anchors without losing deterministic order.
    unique: dict[
        tuple[str, str],
        TopicalDocumentCandidate,
    ] = {}
    for candidate in candidates:
        unique[
            (
                candidate.source_url,
                candidate.document_type,
            )
        ] = candidate

    return list(unique.values())


discovered_documents: list[TopicalDocumentCandidate] = []
discovery_failures: list[dict[str, Any]] = []

for position, topic_page in enumerate(topic_pages, start=1):
    print(
        f"[{position}/{len(topic_pages)}] "
        f"Discovering Topic {topic_page.topic_number}: "
        f"{topic_page.topic_name}"
    )
    try:
        discovered_documents.extend(
            discover_documents_from_topic_page(topic_page)
        )
    except Exception as exc:
        discovery_failures.append(
            {
                "topic_number": topic_page.topic_number,
                "topic_name": topic_page.topic_name,
                "source_page_url": topic_page.url,
                "error": str(exc),
            }
        )

discovery_df = pd.DataFrame(
    [item.model_dump() for item in discovered_documents]
)
discovery_failures_df = pd.DataFrame(discovery_failures)

if not discovery_df.empty:
    discovery_df = discovery_df.sort_values(
        [
            "topic_number",
            "subtopic_code",
            "document_type",
        ]
    ).reset_index(drop=True)

display(discovery_df)

if not discovery_failures_df.empty:
    print("Topic-page discovery failures:")
    display(discovery_failures_df)

print(f"Discovered topical PDFs: {len(discovery_df)}")

[1/8] Discovering Topic 1: Fundamentals of Algorithms
[2/8] Discovering Topic 2: Programming
[3/8] Discovering Topic 3: Fundamentals of Data Representation
[4/8] Discovering Topic 4: Computer Systems
[5/8] Discovering Topic 5: Fundamentals of Computer Networks
[6/8] Discovering Topic 6: Cyber Security
[7/8] Discovering Topic 7: Relational Databases and Structured Query Language (SQL)
[8/8] Discovering Topic 8: Ethical, Legal and Environmental Impacts of Digital Technology on Wider Society, including Issues of Privacy

,topic_number,topic_name,subtopic_code,subtopic_name,paper_code,programming_language,source_coverage,topic_key,pair_key,document_type,source_page_url,source_url,discovery_title
0,1,Fundamentals of Algorithms,1.1,Representing Algorithms,1,Python,2018-2024,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,mark_scheme,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,1.1 Representing Algorithms MS
1,1,Fundamentals of Algorithms,1.1,Representing Algorithms,1,Python,2018-2024,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,question_paper,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,1.1 Representing Algorithms QP
2,1,Fundamentals of Algorithms,1.2,Efficiency of Algorithms,1,Python,2018-2024,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,mark_scheme,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,1.2 Efficiency of Algorithms MS
3,1,Fundamentals of Algorithms,1.2,Efficiency of Algorithms,1,Python,2018-2024,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,question_paper,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,1.2 Efficiency of Algorithms QP
4,1,Fundamentals of Algorithms,1.3,Searching Algorithms,1,Python,2018-2024,AQA_GCSE_CS_PMT_T1_1_3_PYTHON,AQA_GCSE_CS_PMT_T1_1_3_PYTHON,mark_scheme,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,1.3 Searching Algorithms MS
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,7,Relational Databases and Structured Query Lang...,7.1,Relational Databases,2,NaN,2018-2024,AQA_GCSE_CS_PMT_T7_7_1_THEORY,AQA_GCSE_CS_PMT_T7_7_1_THEORY,question_paper,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,7.1 Relational Databases QP
66,7,Relational Databases and Structured Query Lang...,7.2,Structured Query Language (SQL),2,NaN,2018-2024,AQA_GCSE_CS_PMT_T7_7_2_THEORY,AQA_GCSE_CS_PMT_T7_7_2_THEORY,mark_scheme,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,7.2 Structured Query Language (SQL) MS
67,7,Relational Databases and Structured Query Lang...,7.2,Structured Query Language (SQL),2,NaN,2018-2024,AQA_GCSE_CS_PMT_T7_7_2_THEORY,AQA_GCSE_CS_PMT_T7_7_2_THEORY,question_paper,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,7.2 Structured Query Language (SQL) QP
68,8,"Ethical, Legal and Environmental Impacts of Di...",8,"Ethical, Legal and Environmental Impacts of Di...",2,NaN,2018-2024,AQA_GCSE_CS_PMT_T8_8_THEORY,AQA_GCSE_CS_PMT_T8_8_THEORY,mark_scheme,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,"8 Ethical, Legal and Environmental Impacts of ..."
69,8,"Ethical, Legal and Environmental Impacts of Di...",8,"Ethical, Legal and Environmental Impacts of Di...",2,NaN,2018-2024,AQA_GCSE_CS_PMT_T8_8_THEORY,AQA_GCSE_CS_PMT_T8_8_THEORY,question_paper,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,"8 Ethical, Legal and Environmental Impacts of ..."

Discovered topical PDFs: 70

## 9. Validate QP/MS coverage before downloading

Every `pair_key` should contain:

- exactly one `question_paper`;
- exactly one `mark_scheme`.

The checks warn when PMT changes its page structure, removes a resource, or adds new subtopics.

### Correction applied

"
            "The coverage calculation groups directly by `pair_key`. "
            "This avoids the Pandas Cartesian-product issue caused by "
            "`pivot_table(dropna=False)` when theory topics have "
            "`programming_language=None`."

In [9]:
def build_pair_coverage(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build one coverage row per deterministic pair_key.

    Important:
    We intentionally avoid pivot_table(dropna=False) here because theory
    topics have programming_language=None. Some Pandas versions expand the
    index combinations into a Cartesian product, which creates fake
    incomplete QP/MS pairs.
    """
    if dataframe.empty:
        return pd.DataFrame(
            columns=[
                "pair_key",
                "topic_number",
                "topic_name",
                "subtopic_code",
                "subtopic_name",
                "paper_code",
                "programming_language",
                "question_paper",
                "mark_scheme",
                "pair_complete",
            ]
        )

    pair_coverage = (
        dataframe.groupby(
            "pair_key",
            dropna=False,
            as_index=False,
        )
        .agg(
            topic_number=("topic_number", "first"),
            topic_name=("topic_name", "first"),
            subtopic_code=("subtopic_code", "first"),
            subtopic_name=("subtopic_name", "first"),
            paper_code=("paper_code", "first"),
            programming_language=(
                "programming_language",
                "first",
            ),
            question_paper=(
                "document_type",
                lambda values: int(
                    (values == "question_paper").sum()
                ),
            ),
            mark_scheme=(
                "document_type",
                lambda values: int(
                    (values == "mark_scheme").sum()
                ),
            ),
        )
    )

    pair_coverage["pair_complete"] = (
        pair_coverage["question_paper"].eq(1)
        & pair_coverage["mark_scheme"].eq(1)
    )

    return pair_coverage.sort_values(
        ["topic_number", "subtopic_code"]
    ).reset_index(drop=True)


pair_coverage_df = build_pair_coverage(discovery_df)
display(pair_coverage_df)

incomplete_pairs_df = pair_coverage_df[
    ~pair_coverage_df["pair_complete"]
].copy()

discovery_checks = {
    "eight_main_topic_pages_found": (
        len(topic_pages) == EXPECTED_MAIN_TOPICS
    ),
    "expected_pair_count_found": (
        len(pair_coverage_df) == EXPECTED_TOPIC_PAIRS
    ),
    "expected_document_count_found": (
        len(discovery_df) == EXPECTED_DOCUMENTS
    ),
    "all_pairs_complete": incomplete_pairs_df.empty,
    "unique_source_urls": (
        not discovery_df.empty
        and discovery_df["source_url"].is_unique
    ),
    "only_qp_and_ms": (
        not discovery_df.empty
        and set(discovery_df["document_type"]).issubset(
            {"question_paper", "mark_scheme"}
        )
    ),
    "topic_1_and_2_are_python_only": (
        discovery_df[
            discovery_df["topic_number"].isin([1, 2])
        ]["programming_language"]
        .eq(SELECTED_PROGRAMMING_LANGUAGE)
        .all()
    ),
    "theory_topics_have_no_language_variant": (
        discovery_df[
            ~discovery_df["topic_number"].isin([1, 2])
        ]["programming_language"]
        .isna()
        .all()
    ),
}

discovery_checks_df = pd.DataFrame(
    [
        {"check": name, "passed": bool(passed)}
        for name, passed in discovery_checks.items()
    ]
)
display(discovery_checks_df)

failed_discovery_checks = [
    name
    for name, passed in discovery_checks.items()
    if not passed
]

if failed_discovery_checks:
    print(
        "Discovery checks needing attention:",
        failed_discovery_checks,
    )
else:
    print("All PMT topical discovery checks passed.")

if not incomplete_pairs_df.empty:
    print("Genuine incomplete QP/MS pairs:")
    display(incomplete_pairs_df)

,pair_key,topic_number,topic_name,subtopic_code,subtopic_name,paper_code,programming_language,question_paper,mark_scheme,pair_complete
0,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,1,Fundamentals of Algorithms,1.1,Representing Algorithms,1,Python,1,1,True
1,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,1,Fundamentals of Algorithms,1.2,Efficiency of Algorithms,1,Python,1,1,True
2,AQA_GCSE_CS_PMT_T1_1_3_PYTHON,1,Fundamentals of Algorithms,1.3,Searching Algorithms,1,Python,1,1,True
3,AQA_GCSE_CS_PMT_T1_1_4_PYTHON,1,Fundamentals of Algorithms,1.4,Sorting Algorithms,1,Python,1,1,True
4,AQA_GCSE_CS_PMT_T2_2_01_PYTHON,2,Programming,2.01,Data Types,1,Python,1,1,True
5,AQA_GCSE_CS_PMT_T2_2_02_PYTHON,2,Programming,2.02,Programming Concepts,1,Python,1,1,True
6,AQA_GCSE_CS_PMT_T2_2_03_PYTHON,2,Programming,2.03,Arithmetic Operations,1,Python,1,1,True
7,AQA_GCSE_CS_PMT_T2_2_04_PYTHON,2,Programming,2.04,Relational Operations,1,Python,1,1,True
8,AQA_GCSE_CS_PMT_T2_2_05_PYTHON,2,Programming,2.05,Boolean Operations,1,Python,1,1,True
9,AQA_GCSE_CS_PMT_T2_2_06_PYTHON,2,Programming,2.06,Data Structures,1,Python,1,1,True
10,AQA_GCSE_CS_PMT_T2_2_07_PYTHON,2,Programming,2.07,Input or Output,1,Python,1,1,True
11,AQA_GCSE_CS_PMT_T2_2_08_PYTHON,2,Programming,2.08,String Handling,1,Python,1,1,True
12,AQA_GCSE_CS_PMT_T2_2_09_PYTHON,2,Programming,2.09,Random Number Generation,1,Python,1,1,True
13,AQA_GCSE_CS_PMT_T2_2_10_PYTHON,2,Programming,2.10,Structured Programming and Subroutines,1,Python,1,1,True
14,AQA_GCSE_CS_PMT_T2_2_11_PYTHON,2,Programming,2.11,Robust and Secure Programming,1,Python,1,1,True
15,AQA_GCSE_CS_PMT_T3_3_1_THEORY,3,Fundamentals of Data Representation,3.1,Number Bases,2,NaN,1,1,True
16,AQA_GCSE_CS_PMT_T3_3_2_THEORY,3,Fundamentals of Data Representation,3.2,Converting Between Number Bases,2,NaN,1,1,True
17,AQA_GCSE_CS_PMT_T3_3_3_THEORY,3,Fundamentals of Data Representation,3.3,Units of Information,2,NaN,1,1,True
18,AQA_GCSE_CS_PMT_T3_3_4_THEORY,3,Fundamentals of Data Representation,3.4,Binary Arithmetic,2,NaN,1,1,True
19,AQA_GCSE_CS_PMT_T3_3_5_THEORY,3,Fundamentals of Data Representation,3.5,Character Encoding,2,NaN,1,1,True
20,AQA_GCSE_CS_PMT_T3_3_6_THEORY,3,Fundamentals of Data Representation,3.6,Representing Images,2,NaN,1,1,True
21,AQA_GCSE_CS_PMT_T3_3_7_THEORY,3,Fundamentals of Data Representation,3.7,Representing Sound,2,NaN,1,1,True
22,AQA_GCSE_CS_PMT_T3_3_8_THEORY,3,Fundamentals of Data Representation,3.8,Data Compression,2,NaN,1,1,True
23,AQA_GCSE_CS_PMT_T4_4_1_THEORY,4,Computer Systems,4.1,Hardware and Software,2,NaN,1,1,True
24,AQA_GCSE_CS_PMT_T4_4_2_THEORY,4,Computer Systems,4.2,Boolean Logic,2,NaN,1,1,True
25,AQA_GCSE_CS_PMT_T4_4_3_THEORY,4,Computer Systems,4.3,Software Classification,2,NaN,1,1,True
26,AQA_GCSE_CS_PMT_T4_4_4_THEORY,4,Computer Systems,4.4,Classification of Programming Languages and Tr...,2,NaN,1,1,True
27,AQA_GCSE_CS_PMT_T4_4_5_THEORY,4,Computer Systems,4.5,Systems Architecture,2,NaN,1,1,True
28,AQA_GCSE_CS_PMT_T5_5_THEORY,5,Fundamentals of Computer Networks,5,Fundamentals of Computer Networks,2,NaN,1,1,True
29,AQA_GCSE_CS_PMT_T6_6_1_THEORY,6,Cyber Security,6.1,Fundamentals of Cyber Security,2,NaN,1,1,True
30,AQA_GCSE_CS_PMT_T6_6_2_THEORY,6,Cyber Security,6.2,Cyber Security Threats,2,NaN,1,1,True
31,AQA_GCSE_CS_PMT_T6_6_3_THEORY,6,Cyber Security,6.3,Methods to Detect and Prevent Cyber Security T...,2,NaN,1,1,True
32,AQA_GCSE_CS_PMT_T7_7_1_THEORY,7,Relational Databases and Structured Query Lang...,7.1,Relational Databases,2,NaN,1,1,True
33,AQA_GCSE_CS_PMT_T7_7_2_THEORY,7,Relational Databases and Structured Query Lang...,7.2,Structured Query Language (SQL),2,NaN,1,1,True
34,AQA_GCSE_CS_PMT_T8_8_THEORY,8,"Ethical, Legal and Environmental Impacts of Di...",8,"Ethical, Legal and Environmental Impacts of Di...",2,NaN,1,1,True

                                    check  passed
0            eight_main_topic_pages_found    True
1               expected_pair_count_found    True
2           expected_document_count_found    True
3                      all_pairs_complete    True
4                      unique_source_urls    True
5                          only_qp_and_ms    True
6           topic_1_and_2_are_python_only    True
7  theory_topics_have_no_language_variant    True

All PMT topical discovery checks passed.

## 10. Managed PDF download, hashing, and marker inspection

A PDF is accepted only when:

- the response starts with `%PDF`;
- PyMuPDF can open it;
- it contains at least one page.

Existing files are reused unless `FORCE_REDOWNLOAD = True`.

In [10]:
def sha256_file(
    path: Path,
    chunk_size: int = 1024 * 1024,
) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(
            lambda: file.read(chunk_size),
            b"",
        ):
            digest.update(chunk)
    return digest.hexdigest()


def build_local_pdf_path(
    candidate: TopicalDocumentCandidate,
) -> Path:
    # Keep paths deliberately short for Windows compatibility.
    topic_folder = (
        DOWNLOAD_CACHE
        / f"topic_{candidate.topic_number:02d}"
        / f"subtopic_{safe_slug(candidate.subtopic_code, max_length=24)}"
    )
    topic_folder.mkdir(parents=True, exist_ok=True)

    type_suffix = (
        "QP"
        if candidate.document_type == "question_paper"
        else "MS"
    )
    pair_slug = safe_slug(
        candidate.pair_key,
        max_length=100,
    ).upper()
    file_name = f"{pair_slug}_{type_suffix}.pdf"

    return topic_folder / file_name


def inspect_pdf(
    path: Path,
) -> tuple[int, bool, bool, str]:
    with fitz.open(path) as document:
        if document.page_count <= 0:
            raise ValueError("PDF contains no pages.")

        page_count = document.page_count
        extracted_text_parts: list[str] = []
        for page in document:
            extracted_text_parts.append(
                page.get_text("text")
            )

        extracted_text = "\n".join(
            extracted_text_parts
        )

    contains_8520 = bool(
        re.search(r"8520(?:/|\b)", extracted_text)
    )
    contains_8525 = bool(
        re.search(r"8525(?:/|\b)", extracted_text)
    )

    if contains_8520 and contains_8525:
        scope = "mixed_8520_and_8525_markers"
    elif contains_8520:
        scope = "8520_marker_detected"
    elif contains_8525:
        scope = "8525_marker_detected"
    else:
        scope = "source_not_explicit_in_extracted_text"

    return (
        page_count,
        contains_8520,
        contains_8525,
        scope,
    )


def validate_existing_pdf(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(path)
    if path.stat().st_size < 1_000:
        raise ValueError(
            f"Existing PDF is unexpectedly small: {path}"
        )
    with path.open("rb") as file:
        signature = file.read(5)
    if signature != b"%PDF-":
        raise ValueError(
            f"Existing file is not a valid PDF: {path}"
        )


def download_topical_pdf(
    candidate: TopicalDocumentCandidate,
) -> DownloadedTopicalPDF:
    destination = build_local_pdf_path(candidate)
    reused_existing = False

    if destination.exists() and not FORCE_REDOWNLOAD:
        validate_existing_pdf(destination)
        reused_existing = True
    else:
        temporary_path = destination.with_suffix(".part")

        response = http_session.get(
            candidate.source_url,
            timeout=REQUEST_TIMEOUT_SECONDS,
            stream=True,
            headers={
                "Referer": candidate.source_page_url,
            },
        )
        response.raise_for_status()

        with temporary_path.open("wb") as output_file:
            first_chunk = True
            for chunk in response.iter_content(
                chunk_size=1024 * 256
            ):
                if not chunk:
                    continue
                if first_chunk:
                    if not chunk.startswith(b"%PDF"):
                        temporary_path.unlink(
                            missing_ok=True
                        )
                        raise ValueError(
                            "Downloaded response is not a PDF."
                        )
                    first_chunk = False
                output_file.write(chunk)

        if not temporary_path.exists():
            raise RuntimeError(
                "The temporary PDF was not created."
            )
        if temporary_path.stat().st_size < 1_000:
            temporary_path.unlink(missing_ok=True)
            raise ValueError(
                "Downloaded PDF is unexpectedly small."
            )

        temporary_path.replace(destination)

    page_count, contains_8520, contains_8525, scope = (
        inspect_pdf(destination)
    )

    return DownloadedTopicalPDF(
        candidate=candidate,
        original_file_name=destination.name,
        local_cache_path=str(destination.resolve()),
        file_hash=sha256_file(destination),
        file_size_bytes=destination.stat().st_size,
        page_count=page_count,
        contains_8520_marker=contains_8520,
        contains_8525_marker=contains_8525,
        specification_scope=scope,
        reused_existing_file=reused_existing,
    )

## 11. PostgreSQL upsert functions

The upsert is idempotent:

- the same PMT URL is not inserted twice;
- the same `pair_key + document_type` is not inserted twice;
- a changed file hash resets `parsing_status` to `pending`;
- an unchanged cached file is recorded as `skipped_unchanged`.

In [11]:
def upsert_topical_topic(
    session: Session,
    candidate: TopicalDocumentCandidate,
) -> AssessmentTopicalTopic:
    statement = select(
        AssessmentTopicalTopic
    ).where(
        AssessmentTopicalTopic.topic_key
        == candidate.topic_key
    )
    existing = session.scalar(statement)

    values = {
        "source_topic_page_url": (
            candidate.source_page_url
        ),
        "pmt_topic_number": candidate.topic_number,
        "pmt_topic_name": candidate.topic_name,
        "pmt_subtopic_code": (
            candidate.subtopic_code
        ),
        "pmt_subtopic_name": (
            candidate.subtopic_name
        ),
        "paper_code": candidate.paper_code,
        "programming_language": (
            candidate.programming_language
        ),
        "source_coverage": (
            candidate.source_coverage
        ),
        "legacy_8520_retrieval_enabled": (
            LEGACY_8520_RETRIEVAL_ENABLED
        ),
        "requires_question_level_spec_filter": (
            REQUIRES_QUESTION_LEVEL_SPEC_FILTER
        ),
    }

    if existing is None:
        existing = AssessmentTopicalTopic(
            topic_key=candidate.topic_key,
            **values,
        )
        session.add(existing)
        session.flush()
        return existing

    for field_name, value in values.items():
        setattr(existing, field_name, value)

    existing.updated_at = utc_now()
    session.flush()
    return existing


def find_existing_topical_document(
    session: Session,
    downloaded: DownloadedTopicalPDF,
) -> AssessmentTopicalDocument | None:
    candidate = downloaded.candidate

    statement = select(
        AssessmentTopicalDocument
    ).where(
        (
            AssessmentTopicalDocument.source_url
            == candidate.source_url
        )
        | (
            (
                AssessmentTopicalDocument.pair_key
                == candidate.pair_key
            )
            & (
                AssessmentTopicalDocument.document_type
                == candidate.document_type
            )
        )
    )
    return session.scalar(statement)


def upsert_topical_document(
    session: Session,
    downloaded: DownloadedTopicalPDF,
) -> tuple[AssessmentTopicalDocument, str]:
    candidate = downloaded.candidate
    topic = upsert_topical_topic(
        session,
        candidate,
    )
    existing = find_existing_topical_document(
        session,
        downloaded,
    )

    values = {
        "topic_id": topic.id,
        "pair_key": candidate.pair_key,
        "source_page_url": (
            candidate.source_page_url
        ),
        "source_url": candidate.source_url,
        "discovery_title": (
            candidate.discovery_title
        ),
        "document_type": (
            candidate.document_type
        ),
        "programming_language": (
            candidate.programming_language
        ),
        "source_coverage": (
            candidate.source_coverage
        ),
        "original_file_name": (
            downloaded.original_file_name
        ),
        "local_cache_path": (
            downloaded.local_cache_path
        ),
        "file_hash": downloaded.file_hash,
        "file_size_bytes": (
            downloaded.file_size_bytes
        ),
        "page_count": downloaded.page_count,
        "contains_8520_marker": (
            downloaded.contains_8520_marker
        ),
        "contains_8525_marker": (
            downloaded.contains_8525_marker
        ),
        "specification_scope": (
            downloaded.specification_scope
        ),
    }

    if existing is None:
        record = AssessmentTopicalDocument(
            **values,
            download_status="completed",
            parsing_status="pending",
            downloaded_at=utc_now(),
        )
        session.add(record)
        session.flush()
        return record, "inserted"

    unchanged = (
        existing.file_hash
        == downloaded.file_hash
        and existing.local_cache_path
        == downloaded.local_cache_path
    )

    for field_name, value in values.items():
        setattr(existing, field_name, value)

    existing.download_status = "completed"
    existing.downloaded_at = utc_now()
    existing.error_message = None
    existing.updated_at = utc_now()

    if not unchanged:
        existing.parsing_status = "pending"

    session.flush()
    action = (
        "skipped_unchanged"
        if unchanged
        else "updated"
    )
    return existing, action

## 12. Batch ingestion orchestration

One failed PDF does not stop the remaining batch.

In [12]:
def run_pmt_topical_ingestion(
    candidates: Iterable[
        TopicalDocumentCandidate
    ],
    *,
    request_delay_seconds: float = (
        REQUEST_DELAY_SECONDS
    ),
) -> tuple[
    pd.DataFrame,
    pd.DataFrame,
    dict[str, int],
]:
    candidates = list(candidates)

    accepted_rows: list[dict[str, Any]] = []
    issue_rows: list[dict[str, Any]] = []

    counts = {
        "candidates": len(candidates),
        "downloaded_or_reused": 0,
        "inserted": 0,
        "updated": 0,
        "skipped_unchanged": 0,
        "download_or_validation_failed": 0,
        "contains_8520_marker": 0,
        "contains_8525_marker": 0,
        "source_not_explicit": 0,
    }

    run_id = uuid.uuid4()

    if WRITE_TO_POSTGRES:
        with Session(engine) as session:
            run = AssessmentTopicalIngestionRun(
                id=run_id,
                run_type="pmt_topical_discovery",
                status="running",
                counts=counts.copy(),
            )
            session.add(run)
            session.commit()

    try:
        for position, candidate in enumerate(
            candidates,
            start=1,
        ):
            print(
                f"[{position}/{len(candidates)}] "
                f"{candidate.discovery_title}"
            )

            try:
                downloaded = download_topical_pdf(
                    candidate
                )
            except Exception as exc:
                counts[
                    "download_or_validation_failed"
                ] += 1
                issue_rows.append(
                    {
                        "topic_number": (
                            candidate.topic_number
                        ),
                        "subtopic_code": (
                            candidate.subtopic_code
                        ),
                        "subtopic_name": (
                            candidate.subtopic_name
                        ),
                        "document_type": (
                            candidate.document_type
                        ),
                        "source_url": (
                            candidate.source_url
                        ),
                        "stage": (
                            "download_or_validation"
                        ),
                        "error": str(exc),
                    }
                )
                continue

            counts["downloaded_or_reused"] += 1
            if downloaded.contains_8520_marker:
                counts[
                    "contains_8520_marker"
                ] += 1
            if downloaded.contains_8525_marker:
                counts[
                    "contains_8525_marker"
                ] += 1
            if (
                downloaded.specification_scope
                == "source_not_explicit_in_extracted_text"
            ):
                counts["source_not_explicit"] += 1

            database_id: str | None = None
            database_action = "database_disabled"

            if WRITE_TO_POSTGRES:
                with Session(engine) as session:
                    record, database_action = (
                        upsert_topical_document(
                            session,
                            downloaded,
                        )
                    )
                    session.commit()
                    database_id = str(record.id)
                    counts[database_action] += 1

            accepted_rows.append(
                {
                    "database_id": database_id,
                    "topic_key": candidate.topic_key,
                    "pair_key": candidate.pair_key,
                    "topic_number": (
                        candidate.topic_number
                    ),
                    "topic_name": (
                        candidate.topic_name
                    ),
                    "subtopic_code": (
                        candidate.subtopic_code
                    ),
                    "subtopic_name": (
                        candidate.subtopic_name
                    ),
                    "paper_code": (
                        candidate.paper_code
                    ),
                    "programming_language": (
                        candidate.programming_language
                    ),
                    "document_type": (
                        candidate.document_type
                    ),
                    "source_coverage": (
                        candidate.source_coverage
                    ),
                    "contains_8520_marker": (
                        downloaded.contains_8520_marker
                    ),
                    "contains_8525_marker": (
                        downloaded.contains_8525_marker
                    ),
                    "specification_scope": (
                        downloaded.specification_scope
                    ),
                    "page_count": (
                        downloaded.page_count
                    ),
                    "file_size_bytes": (
                        downloaded.file_size_bytes
                    ),
                    "file_hash": (
                        downloaded.file_hash
                    ),
                    "local_cache_path": (
                        downloaded.local_cache_path
                    ),
                    "source_page_url": (
                        candidate.source_page_url
                    ),
                    "source_url": (
                        candidate.source_url
                    ),
                    "reused_existing_file": (
                        downloaded.reused_existing_file
                    ),
                    "database_action": (
                        database_action
                    ),
                }
            )

            if request_delay_seconds > 0:
                time.sleep(request_delay_seconds)

        if WRITE_TO_POSTGRES:
            with Session(engine) as session:
                run = session.get(
                    AssessmentTopicalIngestionRun,
                    run_id,
                )
                if run is not None:
                    run.status = "completed"
                    run.completed_at = utc_now()
                    run.counts = counts.copy()
                    session.commit()

    except Exception as exc:
        if WRITE_TO_POSTGRES:
            with Session(engine) as session:
                run = session.get(
                    AssessmentTopicalIngestionRun,
                    run_id,
                )
                if run is not None:
                    run.status = "failed"
                    run.completed_at = utc_now()
                    run.counts = counts.copy()
                    run.error_message = str(exc)
                    session.commit()
        raise

    accepted_df = pd.DataFrame(accepted_rows)
    issues_df = pd.DataFrame(issue_rows)

    return accepted_df, issues_df, counts

## 13. Run the topical ingestion

This downloads all currently discovered topical QP/MS PDFs. With the current PMT structure, the expected result is 70 PDFs.

To test only a few resources first, use:

```python
candidates_to_run = discovered_documents[:4]
```

The default cell below processes the complete discovered set.

In [13]:
complete_pair_keys = set(
    pair_coverage_df.loc[
        pair_coverage_df["pair_complete"],
        "pair_key",
    ]
)

candidates_to_run = [
    candidate
    for candidate in discovered_documents
    if candidate.pair_key in complete_pair_keys
]

if not incomplete_pairs_df.empty:
    print(
        "Warning: incomplete PMT pairs were excluded. "
        "Complete pairs will still be downloaded."
    )
    display(incomplete_pairs_df)

if not candidates_to_run:
    raise RuntimeError(
        "No complete PMT QP/MS pairs were discovered. "
        "Review discovery_df and pair_coverage_df."
    )

print(
    f"Downloading {len(candidates_to_run)} documents "
    f"from {len(complete_pair_keys)} complete QP/MS pairs."
)

accepted_df, issues_df, ingestion_counts = (
    run_pmt_topical_ingestion(
        candidates_to_run,
        request_delay_seconds=(
            REQUEST_DELAY_SECONDS
        ),
    )
)

print(json.dumps(ingestion_counts, indent=2))

if not accepted_df.empty:
    display(
        accepted_df.sort_values(
            [
                "topic_number",
                "subtopic_code",
                "document_type",
            ]
        ).reset_index(drop=True)
    )

if not issues_df.empty:
    print("Ingestion issues:")
    display(issues_df)

Downloading 70 documents from 35 complete QP/MS pairs.
[1/70] 1.1 Representing Algorithms MS
[2/70] 1.1 Representing Algorithms QP
[3/70] 1.2 Efficiency of Algorithms MS
[4/70] 1.2 Efficiency of Algorithms QP
[5/70] 1.3 Searching Algorithms MS
[6/70] 1.3 Searching Algorithms QP
[7/70] 1.4 Sorting Algorithms MS
[8/70] 1.4 Sorting Algorithms QP
[9/70] 2.01 Data Types MS
[10/70] 2.01 Data Types QP
[11/70] 2.02 Programming Concepts MS
[12/70] 2.02 Programming Concepts QP
[13/70] 2.03 Arithmetic Operations MS
[14/70] 2.03 Arithmetic Operations QP
[15/70] 2.04 Relational Operations MS
[16/70] 2.04 Relational Operations QP
[17/70] 2.05 Boolean Operations MS
[18/70] 2.05 Boolean Operations QP
[19/70] 2.06 Data Structures MS
[20/70] 2.06 Data Structures QP
[21/70] 2.07 Input or Output MS
[22/70] 2.07 Input or Output QP
[23/70] 2.08 String Handling MS
[24/70] 2.08 String Handling QP
[25/70] 2.09 Random Number Generation MS
[26/70] 2.09 Random Number Generation QP
[27/70] 2.10 Structured Programming and Subroutines MS
[28/70] 2.10 Structured Programming and Subroutines QP
[29/70] 2.11 Robust and Secure Programming MS
[30/70] 2.11 Robust and Secure Programming QP
[31/70] 3.1 Number Bases MS
[32/70] 3.1 Number Bases QP
[33/70] 3.2 Converting Between Number Bases MS
[34/70] 3.2 Converting Between Number Bases QP
[35/70] 3.3 Units of Information MS
[36/70] 3.3 Units of Information QP
[37/70] 3.4 Binary Arithmetic MS
[38/70] 3.4 Binary Arithmetic QP
[39/70] 3.5 Character Encoding MS
[40/70] 3.5 Character Encoding QP
[41/70] 3.6 Representing Images MS
[42/70] 3.6 Representing Images QP
[43/70] 3.7 Representing Sound MS
[44/70] 3.7 Representing Sound QP
[45/70] 3.8 Data Compression MS
[46/70] 3.8 Data Compression QP
[47/70] 4.1 Hardware and Software MS
[48/70] 4.1 Hardware and Software QP
[49/70] 4.2 Boolean Logic MS
[50/70] 4.2 Boolean Logic QP
[51/70] 4.3 Software Classification MS
[52/70] 4.3 Software Classification QP
[53/70] 4.4 Classification of Programming Languages and Translators MS
[54/70] 4.4 Classification of Programming Languages and Translators QP
[55/70] 4.5 Systems Architecture MS
[56/70] 4.5 Systems Architecture QP
[57/70] 5 Fundamentals of Computer Networks MS
[58/70] 5 Fundamentals of Computer Networks QP
[59/70] 6.1 Fundamentals of Cyber Security MS
[60/70] 6.1 Fundamentals of Cyber Security QP
[61/70] 6.2 Cyber Security Threats MS
[62/70] 6.2 Cyber Security Threats QP
[63/70] 6.3 Methods to Detect and Prevent Cyber Security Threats MS
[64/70] 6.3 Methods to Detect and Prevent Cyber Security Threats QP
[65/70] 7.1 Relational Databases MS
[66/70] 7.1 Relational Databases QP
[67/70] 7.2 Structured Query Language (SQL) MS
[68/70] 7.2 Structured Query Language (SQL) QP
[69/70] 8 Ethical, Legal and Environmental Impacts of Digital Technology on Society MS
[70/70] 8 Ethical, Legal and Environmental Impacts of Digital Technology on Society QP
{
  "candidates": 70,
  "downloaded_or_reused": 70,
  "inserted": 70,
  "updated": 0,
  "skipped_unchanged": 0,
  "download_or_validation_failed": 0,
  "contains_8520_marker": 2,
  "contains_8525_marker": 0,
  "source_not_explicit": 68
}

,database_id,topic_key,pair_key,topic_number,topic_name,subtopic_code,subtopic_name,paper_code,programming_language,document_type,...,contains_8525_marker,specification_scope,page_count,file_size_bytes,file_hash,local_cache_path,source_page_url,source_url,reused_existing_file,database_action
0,e6147a06-b5cd-42ab-bc62-9a29b876e4cf,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,1,Fundamentals of Algorithms,1.1,Representing Algorithms,1,Python,mark_scheme,...,False,source_not_explicit_in_extracted_text,37,3086912,ec57bba268d68a972e4fc14bad71341f5a5bb47c24bf74...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
1,f63642ec-794e-465f-8623-5d6e9693be56,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,AQA_GCSE_CS_PMT_T1_1_1_PYTHON,1,Fundamentals of Algorithms,1.1,Representing Algorithms,1,Python,question_paper,...,False,source_not_explicit_in_extracted_text,44,6442167,f9f8a56144b05a6f8d7fb0c69b970cae1f4725e4f163be...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
2,b597227d-b204-4c23-8e2d-be47592c94a0,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,1,Fundamentals of Algorithms,1.2,Efficiency of Algorithms,1,Python,mark_scheme,...,False,source_not_explicit_in_extracted_text,4,1176054,95044deeb0562eda8312fe2a97eda7fd58b1a42f558343...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
3,1d3a0d0d-8343-4c38-8945-78d524785e90,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,AQA_GCSE_CS_PMT_T1_1_2_PYTHON,1,Fundamentals of Algorithms,1.2,Efficiency of Algorithms,1,Python,question_paper,...,False,source_not_explicit_in_extracted_text,5,1698919,323d7ed48d57db6ae0fc82cc425eaedbd2d5427f91cc57...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
4,5c55fcfa-ff27-441b-af7a-46223676500d,AQA_GCSE_CS_PMT_T1_1_3_PYTHON,AQA_GCSE_CS_PMT_T1_1_3_PYTHON,1,Fundamentals of Algorithms,1.3,Searching Algorithms,1,Python,mark_scheme,...,False,source_not_explicit_in_extracted_text,9,1329372,36bd55d04823d73264e275029da5641a8886532360a8de...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,816fcee2-ef78-4674-909c-dc2feb1eb04e,AQA_GCSE_CS_PMT_T7_7_1_THEORY,AQA_GCSE_CS_PMT_T7_7_1_THEORY,7,Relational Databases and Structured Query Lang...,7.1,Relational Databases,2,NaN,question_paper,...,False,source_not_explicit_in_extracted_text,9,2421717,3623cf6ec4b0a6f2bcdf4c2898855a8317194dd4f6f78d...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
66,4afd1fba-b8e0-4fe5-add1-e324c54e078f,AQA_GCSE_CS_PMT_T7_7_2_THEORY,AQA_GCSE_CS_PMT_T7_7_2_THEORY,7,Relational Databases and Structured Query Lang...,7.2,Structured Query Language (SQL),2,NaN,mark_scheme,...,False,source_not_explicit_in_extracted_text,8,1518199,960d4b4d68ce3de180ce9d747ce763cd7d37afd328ac10...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
67,20c87cb8-b0d8-447b-a80e-e83f92a73ae7,AQA_GCSE_CS_PMT_T7_7_2_THEORY,AQA_GCSE_CS_PMT_T7_7_2_THEORY,7,Relational Databases and Structured Query Lang...,7.2,Structured Query Language (SQL),2,NaN,question_paper,...,False,source_not_explicit_in_extracted_text,9,2504044,fe7eee2d9578181a2c70a70d9d51ddadeb92f7da9badcc...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
68,cd0ce9eb-fb60-40de-9651-600de0eb7066,AQA_GCSE_CS_PMT_T8_8_THEORY,AQA_GCSE_CS_PMT_T8_8_THEORY,8,"Ethical, Legal and Environmental Impacts of Di...",8,"Ethical, Legal and Environmental Impacts of Di...",2,NaN,mark_scheme,...,False,source_not_explicit_in_extracted_text,9,1492175,69e82036f90c6ea24129b44fa0bcfbe0c54964de499730...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted
69,a0953e03-e20b-4c1a-ae32-d57eb96323f2,AQA_GCSE_CS_PMT_T8_8_THEORY,AQA_GCSE_CS_PMT_T8_8_THEORY,8,"Ethical, Legal and Environmental Impacts of Di...",8,"Ethical, Legal and Environmental Impacts of Di...",2,NaN,question_paper,...,False,source_not_explicit_in_extracted_text,7,2001013,2fcfc05df2a6595f75c49861ba5cddcdedd92a6125e860...,C:\Users\hp\EDTECH\Agent2\cache\pmt_topical_pd...,https://www.physicsandmathstutor.com/computer-...,https://pmt.physicsandmathstutor.com/download/...,False,inserted

## 14. Save human-readable manifests

In [15]:
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

discovery_path = (
    OUTPUT_DIR
    / f"pmt_topical_discovery_manifest_{timestamp}.csv"
)

pair_coverage_path = (
    OUTPUT_DIR
    / f"pmt_topical_pair_coverage_{timestamp}.csv"
)

accepted_path = (
    OUTPUT_DIR
    / f"pmt_topical_document_manifest_{timestamp}.csv"
)

issues_path = (
    OUTPUT_DIR
    / f"pmt_topical_ingestion_issues_{timestamp}.csv"
)

summary_path = (
    OUTPUT_DIR
    / f"pmt_topical_ingestion_summary_{timestamp}.json"
)


# Save CSV files
discovery_df.to_csv(
    discovery_path,
    index=False,
)

pair_coverage_df.to_csv(
    pair_coverage_path,
    index=False,
)

accepted_df.to_csv(
    accepted_path,
    index=False,
)

issues_df.to_csv(
    issues_path,
    index=False,
)


def make_json_safe(value):
    """
    Convert Pandas, NumPy, Path, datetime and UUID objects
    into values supported by json.dumps().
    """

    if value is None or isinstance(
        value,
        (str, int, float, bool),
    ):
        return value

    if isinstance(value, dict):
        return {
            str(key): make_json_safe(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple, set)):
        return [
            make_json_safe(item)
            for item in value
        ]

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, datetime):
        return value.isoformat()

    if isinstance(value, uuid.UUID):
        return str(value)

    # Handles NumPy and Pandas scalar types:
    # np.bool_, np.int64, np.float64, etc.
    if hasattr(value, "item"):
        try:
            return make_json_safe(value.item())
        except (TypeError, ValueError):
            pass

    return str(value)


summary_payload = {
    "generated_at_utc": utc_now().isoformat(),
    "source_provider": SOURCE_PROVIDER,
    "source_landing_page": PMT_LANDING_PAGE,
    "exam_board": EXAM_BOARD,
    "qualification": QUALIFICATION,
    "subject": SUBJECT,
    "target_specification_code": (
        TARGET_SPECIFICATION_CODE
    ),
    "selected_programming_language": (
        SELECTED_PROGRAMMING_LANGUAGE
    ),
    "source_coverage": DEFAULT_SOURCE_COVERAGE,
    "legacy_8520_retrieval_enabled": (
        LEGACY_8520_RETRIEVAL_ENABLED
    ),
    "requires_question_level_spec_filter": (
        REQUIRES_QUESTION_LEVEL_SPEC_FILTER
    ),
    "discovery_checks": discovery_checks,
    "ingestion_counts": ingestion_counts,
    "output_files": {
        "discovery_manifest": str(
            discovery_path.resolve()
        ),
        "pair_coverage": str(
            pair_coverage_path.resolve()
        ),
        "document_manifest": str(
            accepted_path.resolve()
        ),
        "issues": str(
            issues_path.resolve()
        ),
    },
}


json_safe_summary_payload = make_json_safe(
    summary_payload
)


summary_path.write_text(
    json.dumps(
        json_safe_summary_payload,
        indent=2,
        ensure_ascii=False,
    ),
    encoding="utf-8",
)


print("Saved successfully:")
print(f"- {discovery_path}")
print(f"- {pair_coverage_path}")
print(f"- {accepted_path}")
print(f"- {issues_path}")
print(f"- {summary_path}")

Saved successfully:
- C:\Users\hp\EDTECH\Agent2\OUTPUT\pmt_topical_discovery_manifest_20260804_174108.csv
- C:\Users\hp\EDTECH\Agent2\OUTPUT\pmt_topical_pair_coverage_20260804_174108.csv
- C:\Users\hp\EDTECH\Agent2\OUTPUT\pmt_topical_document_manifest_20260804_174108.csv
- C:\Users\hp\EDTECH\Agent2\OUTPUT\pmt_topical_ingestion_issues_20260804_174108.csv
- C:\Users\hp\EDTECH\Agent2\OUTPUT\pmt_topical_ingestion_summary_20260804_174108.json

## 15. Final cache and database smoke checks

In [16]:
def run_topical_manifest_checks(
    dataframe: pd.DataFrame,
) -> dict[str, bool]:

    if dataframe.empty:
        return {
            "has_documents": False,
            "expected_document_count": False,
            "expected_pair_count": False,
            "all_cache_files_exist": False,
            "all_pdfs_have_pages": False,
            "all_hashes_valid": False,
            "all_pairs_complete": False,
            "source_urls_unique": False,
        }

    pair_counts = (
        dataframe.groupby(
            ["pair_key", "document_type"]
        )
        .size()
        .unstack(fill_value=0)
    )

    for column in (
        "question_paper",
        "mark_scheme",
    ):
        if column not in pair_counts.columns:
            pair_counts[column] = 0

    all_pairs_complete = (
        pair_counts["question_paper"].eq(1)
        & pair_counts["mark_scheme"].eq(1)
    ).all()

    checks = {
        "has_documents": len(dataframe) > 0,

        "expected_document_count": (
            len(dataframe) == EXPECTED_DOCUMENTS
        ),

        "expected_pair_count": (
            dataframe["pair_key"].nunique()
            == EXPECTED_TOPIC_PAIRS
        ),

        "all_cache_files_exist": (
            dataframe["local_cache_path"]
            .map(
                lambda value: Path(value).exists()
            )
            .all()
        ),

        "all_pdfs_have_pages": (
            dataframe["page_count"]
            .fillna(0)
            .gt(0)
            .all()
        ),

        "all_hashes_valid": (
            dataframe["file_hash"]
            .fillna("")
            .str.fullmatch(r"[0-9a-f]{64}")
            .all()
        ),

        "all_pairs_complete": bool(
            all_pairs_complete
        ),

        "source_urls_unique": (
            dataframe["source_url"].is_unique
        ),

        "only_python_for_paper_1": (
            dataframe[
                dataframe["paper_code"].eq("1")
            ]["programming_language"]
            .eq(SELECTED_PROGRAMMING_LANGUAGE)
            .all()
        ),

        "legacy_8520_disabled": (
            LEGACY_8520_RETRIEVAL_ENABLED
            is False
        ),
    }

    return {
        key: bool(value)
        for key, value in checks.items()
    }


final_checks = run_topical_manifest_checks(
    accepted_df
)


final_checks_df = pd.DataFrame(
    [
        {
            "check": check_name,
            "passed": passed,
        }
        for check_name, passed
        in final_checks.items()
    ]
)


display(final_checks_df)


failed_final_checks = [
    check_name
    for check_name, passed
    in final_checks.items()
    if not passed
]


if failed_final_checks:
    print("Checks needing attention:")

    for check_name in failed_final_checks:
        print(f"- {check_name}")

else:
    print(
        "All PMT topical source-ingestion "
        "checks passed."
    )

                     check  passed
0            has_documents    True
1  expected_document_count    True
2      expected_pair_count    True
3    all_cache_files_exist    True
4      all_pdfs_have_pages    True
5         all_hashes_valid    True
6       all_pairs_complete    True
7       source_urls_unique    True
8  only_python_for_paper_1    True
9     legacy_8520_disabled    True

All PMT topical source-ingestion checks passed.

## 16. Optional PostgreSQL verification query

In [17]:
if WRITE_TO_POSTGRES:

    with Session(engine) as session:

        topic_rows = session.scalars(
            select(
                AssessmentTopicalTopic
            ).order_by(
                AssessmentTopicalTopic.pmt_topic_number,
                AssessmentTopicalTopic.pmt_subtopic_code,
            )
        ).all()

        document_rows = session.scalars(
            select(
                AssessmentTopicalDocument
            ).order_by(
                AssessmentTopicalDocument.pair_key,
                AssessmentTopicalDocument.document_type,
            )
        ).all()


    unique_pair_keys = {
        row.pair_key
        for row in document_rows
    }


    database_summary = pd.DataFrame(
        [
            {
                "metric": (
                    "assessment_topical_topics"
                ),
                "value": len(topic_rows),
            },
            {
                "metric": (
                    "assessment_topical_documents"
                ),
                "value": len(document_rows),
            },
            {
                "metric": "complete_pair_keys",
                "value": len(unique_pair_keys),
            },
            {
                "metric": (
                    "documents_with_8520_marker"
                ),
                "value": sum(
                    bool(
                        row.contains_8520_marker
                    )
                    for row in document_rows
                ),
            },
            {
                "metric": (
                    "documents_with_8525_marker"
                ),
                "value": sum(
                    bool(
                        row.contains_8525_marker
                    )
                    for row in document_rows
                ),
            },
            {
                "metric": (
                    "documents_pending_parsing"
                ),
                "value": sum(
                    row.parsing_status == "pending"
                    for row in document_rows
                ),
            },
        ]
    )


    display(database_summary)


    print("\nExpected values:")
    print(
        f"- Topics/subtopics: "
        f"{EXPECTED_TOPIC_PAIRS}"
    )
    print(
        f"- Documents: "
        f"{EXPECTED_DOCUMENTS}"
    )
    print(
        f"- QP/MS pair keys: "
        f"{EXPECTED_TOPIC_PAIRS}"
    )

else:
    print(
        "Database verification skipped because "
        "WRITE_TO_POSTGRES = False."
    )

                         metric  value
0     assessment_topical_topics     35
1  assessment_topical_documents     70
2            complete_pair_keys     35
3    documents_with_8520_marker      2
4    documents_with_8525_marker      0
5     documents_pending_parsing     70

Expected values:
- Topics/subtopics: 35
- Documents: 70
- QP/MS pair keys: 35

# Notebook output

After a successful run:

## PostgreSQL

```text
assessment_topical_topics
assessment_topical_documents
assessment_topical_ingestion_runs
```

## Local cache

```text
cache/pmt_topical_pdfs/
├── topic_01/
│   ├── subtopic_1_1/
│   │   ├── AQA_GCSE_CS_PMT_T1_1_1_PYTHON_QP.pdf
│   │   └── AQA_GCSE_CS_PMT_T1_1_1_PYTHON_MS.pdf
│   └── ...
├── topic_02/
└── ...
```

## OUTPUT

```text
pmt_topical_discovery_manifest_<timestamp>.csv
pmt_topical_pair_coverage_<timestamp>.csv
pmt_topical_document_manifest_<timestamp>.csv
pmt_topical_ingestion_issues_<timestamp>.csv
pmt_topical_ingestion_summary_<timestamp>.json
```

## Next notebook

The next notebook should be:

```text
02_pmt_topical_question_and_mark_scheme_parsing.ipynb
```

It should:

1. load each complete `pair_key`;
2. parse the topical QP into individual question records;
3. parse the matching topical MS in the same order;
4. link every question to its marking guidance;
5. preserve the already-known topic/subtopic metadata;
6. detect and disable explicit 8520 questions by default;
7. save question-level records for Qdrant embedding and retrieval.

The previous official full-paper source discovery and parsing notebooks are no longer required for this PMT-first MVP. Keep them only as archived work until the new topical parser has been validated end to end.